(()=>{
const $=id=>document.getElementById(id);
const profile=(()=>{try{return Object.assign({science:0,coins:500,medals:0,clears:{}},JSON.parse(localStorage.getItem('chronicle_phaser_v2'))||{})}catch{return{science:0,coins:500,medals:0,clears:{}}}})();
const save=()=>localStorage.setItem('chronicle_phaser_v2',JSON.stringify(profile));
let activeMap='constantinople',activeDiff='recruit',sceneRef=null,state=null,game=null,speed=1,currentPath=[];
const maps={
 constantinople:{name:'CONSTANTINOPLE',unlock:()=>true,baseGold:0,path:[[-20,330],[100,330],[165,270],[260,270],[330,370],[430,370],[505,300],[595,300],[680,225],[770,225],[850,285],[990,285]]},
 bursa:{name:'BURSA',unlock:()=>!!profile.clears['constantinople:recruit'],baseGold:40,path:[[-20,185],[110,185],[185,255],[280,255],[355,175],[455,175],[535,300],[630,300],[710,390],[800,390],[865,325],[990,325]]}
};
const towers={archer:{name:'Archer Post',cost:180,damage:19,range:135,rate:.86,base:'k-base-a',top:'k-simple'},ballista:{name:'Ballista',cost:270,damage:58,range:178,rate:.36,base:'k-base-b',top:'k-power'},watchtower:{name:'Watchtower',cost:145,damage:13,range:202,rate:.68,base:'k-base-a',top:'k-range'}};
const diffs={recruit:{waves:12,gold:900,hp:.72,speed:.94,rewardScience:90,rewardCoins:180},veteran:{waves:18,gold:780,hp:1,speed:1,rewardScience:170,rewardCoins:320},general:{waves:24,gold:690,hp:1.34,speed:1.05,rewardScience:290,rewardCoins:520}};
function sync(){['science','science2'].forEach(id=>$(id).textContent=profile.science);['coins','coins2'].forEach(id=>$(id).textContent=profile.coins);['medals','medals2'].forEach(id=>$(id).textContent=profile.medals);document.querySelectorAll('[data-map-card]').forEach(card=>{const m=card.dataset.mapCard,u=maps[m].unlock();card.classList.toggle('locked',!u);const badge=card.querySelector('.mapart span');if(badge)badge.textContent=u?(m==='constantinople'?'1':'2'):'🔒';const stars=card.querySelector('.stars');if(stars)stars.textContent=['recruit','veteran','general'].map(d=>profile.clears[`${m}:${d}`]?'★':'☆').join(' ');card.querySelectorAll('[data-diff]').forEach(b=>b.disabled=!u)});const p=document.querySelector('.progress p');if(p)p.textContent=maps.bursa.unlock()?'Bursa unlocked · campaign progressing':'Clear Constantinople on Recruit to unlock Bursa.'}
function screen(name){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$(name).classList.add('active');sync();if(name==='battle'){if(!window.__phaserStarted)startGame();else if(sceneRef){sceneRef.scene.restart();sceneRef.scene.resume()}}else if(sceneRef&&!sceneRef.scene.isPaused())sceneRef.scene.pause()}
$('play').onclick=()=>screen('maps');$('home-btn').onclick=()=>screen('home');$('back-maps').onclick=()=>screen('maps');$('result-map').onclick=()=>screen('maps');
document.querySelectorAll('[data-map-card] [data-diff]').forEach(b=>b.onclick=()=>{const m=b.closest('[data-map-card]').dataset.mapCard;if(!maps[m].unlock())return;activeMap=m;activeDiff=b.dataset.diff;screen('battle')});sync();
function ui(){if(!state)return;const d=diffs[activeDiff];$('wave').textContent=`${state.wave}/${d.waves}`;$('lives').textContent=state.lives;$('gold').textContent=Math.floor(state.gold);$('battle-map-name').textContent=maps[activeMap].name;document.querySelectorAll('.tower-card').forEach(b=>b.classList.toggle('poor',state.gold<towers[b.dataset.tower].cost))}
const setMsg=t=>$('message').textContent=t;
const K='https://raw.githubusercontent.com/jhonnold/tower-defense-v2/master/img/PNG/Retina/';
function preload(){this.load.image('k-base-a',K+'towerDefense_tile180.png');this.load.image('k-base-b',K+'towerDefense_tile181.png');this.load.image('k-simple',K+'towerDefense_tile249.png');this.load.image('k-power',K+'towerDefense_tile205.png');this.load.image('k-range',K+'towerDefense_tile206.png');this.load.svg('enemy-light','assets/enemy-light.svg',{width:96,height:96});this.load.svg('enemy-heavy','assets/enemy-heavy.svg',{width:96,height:96});this.load.svg('enemy-runner','assets/enemy-runner.svg',{width:96,height:96})}
function startGame(){window.__phaserStarted=true;game=new Phaser.Game({type:Phaser.AUTO,parent:'game',width:960,height:600,backgroundColor:'#365b45',render:{antialias:true,pixelArt:false},scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH},scene:{preload,create,update}})}
function create(){sceneRef=this;resetBattle();drawWorld(this);setupInput(this);this.cameras.main.fadeIn(260,5,15,13)}
function resetBattle(){const d=diffs[activeDiff];currentPath=maps[activeMap].path.map(([x,y])=>new Phaser.Math.Vector2(x,y));state={gold:d.gold+maps[activeMap].baseGold,lives:20,wave:0,active:false,left:0,spawnTimer:0,enemies:[],towers:[],shots:[],selected:null,dragType:null,dragGhost:null,ended:false,water:[],boats:[]};speed=1;$('speed').textContent='×1';$('result').classList.remove('show');$('tower-panel').classList.remove('show');$('start-wave').disabled=false;setMsg(`Defend ${maps[activeMap].name}. Drag a defence onto open ground.`);ui()}
function drawPath(g){g.beginPath();currentPath.forEach((p,i)=>i?g.lineTo(p.x,p.y):g.moveTo(p.x,p.y));g.strokePath()}
function distanceToPath(x,y){let best=999;for(let i=0;i<currentPath.length-1;i++){const a=currentPath[i],b=currentPath[i+1],dx=b.x-a.x,dy=b.y-a.y,l=dx*dx+dy*dy,t=Math.max(0,Math.min(1,((x-a.x)*dx+(y-a.y)*dy)/l)),px=a.x+t*dx,py=a.y+t*dy;best=Math.min(best,Math.hypot(x-px,y-py))}return best}
function drawWorld(s){const g=s.add.graphics();if(activeMap==='constantinople'){g.fillGradientStyle(0x8fad79,0x718f67,0x3d674b,0x315743,1);g.fillRect(0,0,960,600);g.fillGradientStyle(0x3b95ab,0x2b7e93,0x1d6075,0x164e62,1);g.fillRect(0,0,154,600);g.fillStyle(0xdcc995,1);g.fillRect(145,0,20,600);for(let y=18;y<600;y+=22){const w=s.add.rectangle(70,y,118,2,0xd8f5f4,.28).setDepth(1);state.water.push({obj:w,base:y,phase:y*.08})}for(const [x,y] of [[58,116],[94,447]]){const c=s.add.container(x,y).setDepth(3),h=s.add.ellipse(0,0,34,11,0x513a29),mast=s.add.rectangle(0,-17,3,36,0x735238),sail=s.add.triangle(12,-24,0,0,0,27,20,20,0xe2d7b6);c.add([h,mast,sail]);state.boats.push({obj:c,base:y,phase:y*.03})}g.fillStyle(0x826f57,1);g.fillRect(892,174,68,180);g.fillStyle(0xb09a75,1);for(let i=0;i<5;i++)g.fillRect(894+i*15,160,11,20);g.fillStyle(0x30261f,1);g.fillRect(918,276,26,78);for(const [x,y,r] of [[826,104,38],[760,125,29],[696,143,24]]){g.fillStyle(0x234038,.95);g.fillRect(x-r*.72,y,r*1.44,78);g.fillCircle(x,y,r);g.fillRect(x-3,y-78,6,78);g.fillTriangle(x-7,y-78,x+7,y-78,x,y-99)}}else{g.fillGradientStyle(0xa7ad79,0x889d67,0x536d47,0x415b3d,1);g.fillRect(0,0,960,600);g.fillStyle(0x718466,.36);g.fillEllipse(240,130,420,190);g.fillStyle(0x425e40,.35);g.fillEllipse(760,505,580,240);g.fillStyle(0x87916e,.62);for(let i=0;i<8;i++){const x=80+i*130,y=76+(i%2)*20;g.fillTriangle(x-100,y+100,x,y-42,x+112,y+100)}g.fillStyle(0x674f3b,1);g.fillRect(828,210,132,152);g.fillStyle(0x957552,1);for(let i=0;i<8;i++)g.fillRect(830+i*18,195,12,22);g.fillStyle(0x2e241d,1);g.fillRect(882,300,30,62)}for(let i=0;i<110;i++){const x=(i*173+47)%960,y=(i*97+31)%600;if((activeMap==='constantinople'&&x<170)||distanceToPath(x,y)<68)continue;const r=5+(i%7);g.fillStyle(i%8===0?0x8b8069:0x3d7044,.9);g.fillCircle(x,y,r)}g.lineStyle(70,0x171915,.28);drawPath(g);g.lineStyle(60,0x756248,.5);drawPath(g);g.lineStyle(50,activeMap==='bursa'?0xd2b77d:0xc9ad77,1);drawPath(g);g.lineStyle(3,0xf5e4b3,.22);drawPath(g);s.add.text(20,76,maps[activeMap].name,{fontFamily:'Georgia',fontSize:'18px',color:'#f6dfab',stroke:'#17221e',strokeThickness:4}).setDepth(5)}
function validPos(x,y){return x>35&&x<910&&y>88&&y<550&&(activeMap!=='constantinople'||x>170)&&distanceToPath(x,y)>58&&!state.towers.some(t=>Phaser.Math.Distance.Between(x,y,t.x,t.y)<72)}
function setupInput(s){document.querySelectorAll('.tower-card').forEach(btn=>{btn.onpointerdown=e=>{if(!state||state.ended)return;const type=btn.dataset.tower,t=towers[type];if(state.gold<t.cost){setMsg('Not enough Gold.');return}e.preventDefault();state.dragType=type;const p=toWorld(e);state.dragGhost=createTowerVisual(s,p.x,p.y,type,true);window.addEventListener('pointermove',dragMove,{passive:false});window.addEventListener('pointerup',dragEnd,{once:true})}});$('start-wave').onclick=startWave;$('speed').onclick=()=>{speed=speed===1?2:1;$('speed').textContent=`×${speed}`;setMsg(speed===2?'Battle speed doubled.':'Battle speed normal.')};$('close-tower').onclick=()=>{$('tower-panel').classList.remove('show');if(state){state.selected=null;state.towers.forEach(x=>x.visual.ring.setVisible(false))}};$('sell').onclick=sellSelected}
function toWorld(e){const canvas=$('game').querySelector('canvas'),rect=(canvas||$('game')).getBoundingClientRect();return{x:(e.clientX-rect.left)*960/rect.width,y:(e.clientY-rect.top)*600/rect.height}}
function dragMove(e){if(!state?.dragGhost)return;e.preventDefault();const p=toWorld(e),ok=validPos(p.x,p.y);state.dragGhost.container.setPosition(p.x,p.y);state.dragGhost.ring.setStrokeStyle(4,ok?0x91e9a0:0xff786d,.92);state.dragGhost.zone.setFillStyle(ok?0x59c773:0xe24e45,.13);state.dragGhost.container.setAlpha(ok?.98:.48)}
function dragEnd(e){window.removeEventListener('pointermove',dragMove);if(!state?.dragGhost)return;const p=toWorld(e),type=state.dragType;state.dragGhost.container.destroy();state.dragGhost=null;state.dragType=null;if(validPos(p.x,p.y))placeTower(type,p.x,p.y);else setMsg('Invalid placement — keep towers off the road.')}
function createTowerVisual(s,x,y,type,ghost=false){const t=towers[type],c=s.add.container(x,y),shadow=s.add.ellipse(3,28,72,22,0x000000,.28),zone=s.add.circle(0,0,t.range,ghost?0x59c773:0,ghost?.12:0),ring=s.add.circle(0,0,t.range,0,0).setStrokeStyle(ghost?4:0,0x91e9a0,.8),base=s.add.image(0,-8,t.base).setDisplaySize(78,78),turret=s.add.image(0,-8,t.top).setDisplaySize(78,78);if(ghost){base.setTint(0xc9ffd2);turret.setTint(0xc9ffd2)}c.add([shadow,zone,ring,base,turret]);c.setDepth(20+y/10);if(!ghost)c.setInteractive(new Phaser.Geom.Circle(0,0,38),Phaser.Geom.Circle.Contains).on('pointerdown',()=>selectTower(c.__tower));return{container:c,ring,zone,aimer:turret,base,turret}}
function placeTower(type,x,y){const d=towers[type];state.gold-=d.cost;const visual=createTowerVisual(sceneRef,x,y,type,false),tower={type,x,y,tier:1,branch:null,damage:d.damage,range:d.range,rate:d.rate,cd:0,spent:d.cost,visual};visual.container.__tower=tower;visual.ring.setVisible(false);visual.zone.setVisible(false);state.towers.push(tower);particles(x,y,0xe0c37e,14);floatText(x,y-48,'DEPLOYED',0xf6dea4);ui()}
function selectTower(t){state.selected=t;$('tower-panel').classList.add('show');$('tower-name').textContent=towers[t.type].name;$('tower-stats').textContent=`Tier ${t.tier} · Damage ${Math.round(t.damage)} · Range ${Math.round(t.range)} · Rate ${t.rate.toFixed(2)}/s`;state.towers.forEach(x=>x.visual.ring.setVisible(x===t).setRadius(x.range));const opts=t.tier===1?[{name:'Heavy Training',cost:.75,damage:1.35,range:1.05,branch:'power'},{name:'Rapid Drill',cost:.7,rate:1.32,range:1.08,branch:'speed'}]:t.tier===2?[{name:t.branch==='power'?'Elite Battery':'Veteran Crew',cost:1.15,damage:1.38,rate:1.18,range:1.12,branch:t.branch}]:[];$('upgrade-options').innerHTML=opts.map((o,i)=>`<button data-up="${i}"><b>${o.name}</b><br><small>${Math.round(towers[t.type].cost*o.cost)} GOLD</small></button>`).join('')||'<p>Maximum tier reached.</p>';document.querySelectorAll('[data-up]').forEach((b,i)=>b.onclick=()=>upgradeTower(opts[i]))}
function upgradeTower(o){const t=state.selected,c=Math.round(towers[t.type].cost*o.cost);if(state.gold<c){setMsg('Not enough Gold.');return}state.gold-=c;t.spent+=c;t.tier++;t.branch=o.branch;t.damage*=o.damage||1;t.range*=o.range||1;t.rate*=o.rate||1;t.visual.container.setScale(1+.08*(t.tier-1));t.visual.turret.setTint(t.tier===3?0xffe19b:0xffffff);particles(t.x,t.y,0xf1cf6e,20);floatText(t.x,t.y-52,`TIER ${t.tier}`,0xffe293);selectTower(t);ui()}
function sellSelected(){const t=state?.selected;if(!t)return;state.gold+=Math.round(t.spent*.62);t.visual.container.destroy();state.towers.splice(state.towers.indexOf(t),1);state.selected=null;$('tower-panel').classList.remove('show');ui()}
function startWave(){const d=diffs[activeDiff];if(state.active||state.ended||state.wave>=d.waves)return;state.wave++;state.left=4+Math.ceil(state.wave*1.15);state.spawnTimer=0;state.active=true;$('start-wave').disabled=true;setMsg(`Wave ${state.wave}: enemy formations approaching.`);ui()}
function spawnEnemy(){const d=diffs[activeDiff],heavy=state.wave>7&&Math.random()<.28,runner=!heavy&&Math.random()<.2,key=heavy?'enemy-heavy':runner?'enemy-runner':'enemy-light',hp=(heavy?220:runner?68:95)*d.hp*(1+state.wave*.04),speed0=(heavy?34:runner?70:44)*d.speed,c=sceneRef.add.container(currentPath[0].x,currentPath[0].y),shadow=sceneRef.add.ellipse(2,16,34,10,0x000000,.26),sprite=sceneRef.add.image(0,-4,key).setDisplaySize(48,48),barBg=sceneRef.add.rectangle(0,-29,36,5,0x141a18),bar=sceneRef.add.rectangle(-17,-29,34,3,0x6ed783).setOrigin(0,.5);c.add([shadow,sprite,barBg,bar]);c.setDepth(30);state.enemies.push({x:currentPath[0].x,y:currentPath[0].y,pi:0,hp,maxHp:hp,speed:speed0,reward:heavy?24:runner?16:14,container:c,sprite,bar,phase:Math.random()*6})}
function shoot(t,target){const a=Phaser.Math.Angle.Between(t.x,t.y,target.x,target.y);t.visual.aimer.setRotation(a);if(t.type==='ballista')sceneRef.tweens.add({targets:t.visual.aimer,scaleX:.84,scaleY:.84,yoyo:true,duration:90});const obj=t.type==='ballista'?sceneRef.add.rectangle(t.x,t.y,14,4,0x3b2c20).setRotation(a):sceneRef.add.circle(t.x,t.y,3,0xffdf9a);obj.setDepth(40);state.shots.push({x:t.x,y:t.y,target,damage:t.damage,obj,kind:t.type})}
function update(time,delta){if(!state||state.ended)return;const dt=Math.min(.035,delta/1000)*speed;state.water.forEach(w=>{w.obj.x=70+Math.sin(time*.0018+w.phase)*8});state.boats.forEach(b=>{b.obj.y=b.base+Math.sin(time*.0014+b.phase)*4;b.obj.x+=.012*speed});if(state.active&&state.left>0){state.spawnTimer-=dt;if(state.spawnTimer<=0){spawnEnemy();state.left--;state.spawnTimer=.8}}for(let i=state.enemies.length-1;i>=0;i--){const e=state.enemies[i],q=currentPath[e.pi+1];if(!q){e.container.destroy();state.enemies.splice(i,1);state.lives--;sceneRef.cameras.main.shake(110,.004);if(state.lives<=0){finish(false);return}continue}const dx=q.x-e.x,dy=q.y-e.y,dist=Math.hypot(dx,dy),m=e.speed*dt;if(dist<=m){e.x=q.x;e.y=q.y;e.pi++}else{e.x+=dx/dist*m;e.y+=dy/dist*m}e.container.setPosition(e.x,e.y+Math.sin(time*.012+e.phase)*2);e.sprite.setRotation(Math.sin(time*.018+e.phase)*.03);e.bar.width=34*Math.max(0,e.hp/e.maxHp)}for(const t of state.towers){t.cd-=dt;if(t.cd>0)continue;let target=null,best=-1;for(const e of state.enemies)if(Phaser.Math.Distance.Between(t.x,t.y,e.x,e.y)<=t.range&&e.pi>=best){target=e;best=e.pi}if(target){t.cd=1/t.rate;shoot(t,target)}}for(let i=state.shots.length-1;i>=0;i--){const p=state.shots[i];if(!state.enemies.includes(p.target)){p.obj.destroy();state.shots.splice(i,1);continue}const dx=p.target.x-p.x,dy=p.target.y-p.y,dist=Math.hypot(dx,dy),m=760*dt;if(dist<m+7){p.target.hp-=p.damage;p.obj.destroy();state.shots.splice(i,1);particles(p.target.x,p.target.y,p.kind==='ballista'?0xc69558:0xffd785,p.kind==='ballista'?9:5);if(p.target.hp<=0){const idx=state.enemies.indexOf(p.target);if(idx>=0){p.target.container.destroy();state.enemies.splice(idx,1);state.gold+=p.target.reward;floatText(p.target.x,p.target.y-24,`+${p.target.reward}`,0xf2d273)}}}else{p.x+=dx/dist*m;p.y+=dy/dist*m;p.obj.setPosition(p.x,p.y)}}if(state.active&&!state.left&&!state.enemies.length){state.active=false;$('start-wave').disabled=false;if(state.wave>=diffs[activeDiff].waves)finish(true);else setMsg(`Wave ${state.wave} cleared. Upgrade or continue.`)}ui()}
function particles(x,y,color,n){for(let i=0;i<n;i++){const p=sceneRef.add.circle(x,y,2+Math.random()*3,color,.9).setDepth(50),tx=x+(Math.random()-.5)*70,ty=y+(Math.random()-.6)*55;sceneRef.tweens.add({targets:p,x:tx,y:ty,alpha:0,scale:.2,duration:350+Math.random()*250,onComplete:()=>p.destroy()})}}
function floatText(x,y,text,color){const t=sceneRef.add.text(x,y,text,{fontFamily:'Georgia',fontSize:'13px',fontStyle:'bold',color:'#'+color.toString(16).padStart(6,'0'),stroke:'#1a1a14',strokeThickness:3}).setOrigin(.5).setDepth(60);sceneRef.tweens.add({targets:t,y:y-24,alpha:0,duration:650,onComplete:()=>t.destroy()})}
function finish(win){state.ended=true;$('start-wave').disabled=true;$('result').classList.add('show');if(win){const d=diffs[activeDiff],kk=`${activeMap}:${activeDiff}`,first=!profile.clears[kk];profile.science+=d.rewardScience;profile.coins+=d.rewardCoins;if(first){profile.medals++;profile.clears[kk]=true}save();sync();$('result-title').textContent=`${maps[activeMap].name} CLEARED`;$('result-text').textContent=`${first?'New medal earned. ':'Replay complete. '}+${d.rewardScience} Science · +${d.rewardCoins} Coins.`}else{$('result-title').textContent='DEFEAT';$('result-text').textContent=`Reached wave ${state.wave}/${diffs[activeDiff].waves}.`}}
})();