(()=>{
const $=id=>document.getElementById(id);
const profile=(()=>{try{return JSON.parse(localStorage.getItem('chronicle_phaser_v2'))||{science:0,coins:500,medals:0,clears:{}}}catch{return{science:0,coins:500,medals:0,clears:{}}}})();
const save=()=>localStorage.setItem('chronicle_phaser_v2',JSON.stringify(profile));
const syncResources=()=>{for(const id of ['science','science2'])$(id).textContent=profile.science;for(const id of ['coins','coins2'])$(id).textContent=profile.coins;for(const id of ['medals','medals2'])$(id).textContent=profile.medals};
let activeDiff='recruit',sceneRef=null,state=null,game=null,speed=1;
function screen(name){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$(name).classList.add('active');syncResources();if(name==='battle'){if(!window.__phaserStarted)startGame();else if(sceneRef){sceneRef.scene.restart();sceneRef.scene.resume();}}else if(sceneRef&&!sceneRef.scene.isPaused())sceneRef.scene.pause();}
$('play').onclick=()=>screen('maps');$('home-btn').onclick=()=>screen('home');$('back-maps').onclick=()=>screen('maps');$('result-map').onclick=()=>screen('maps');
document.querySelectorAll('[data-diff]').forEach(b=>b.onclick=()=>{activeDiff=b.dataset.diff;screen('battle')});syncResources();
const towers={archer:{name:'Archer Post',cost:180,damage:19,range:135,rate:.82,color:0x8f2d2b},ballista:{name:'Ballista',cost:270,damage:52,range:175,rate:.38,color:0x725933},watchtower:{name:'Watchtower',cost:145,damage:13,range:198,rate:.62,color:0x486c52}};
const diffs={recruit:{waves:12,gold:900,hp:.72,speed:.94,rewardScience:90,rewardCoins:180},veteran:{waves:18,gold:780,hp:1,speed:1,rewardScience:170,rewardCoins:320},general:{waves:24,gold:690,hp:1.34,speed:1.05,rewardScience:290,rewardCoins:520}};
function ui(){if(!state)return;const d=diffs[activeDiff];$('wave').textContent=`${state.wave}/${d.waves}`;$('lives').textContent=state.lives;$('gold').textContent=Math.floor(state.gold);document.querySelectorAll('.tower-card').forEach(b=>b.classList.toggle('poor',state.gold<towers[b.dataset.tower].cost));}
function setMsg(t){$('message').textContent=t}
function startGame(){window.__phaserStarted=true;try{const config={type:Phaser.AUTO,parent:'game',width:960,height:600,backgroundColor:'#395c48',render:{antialias:true,pixelArt:false},scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH},scene:{create,update}};game=new Phaser.Game(config);}catch(err){setMsg('Battle engine failed to start. Reload this page.');console.error(err)}}
function create(){sceneRef=this;resetBattle();drawWorld(this);setupInput(this);this.cameras.main.fadeIn(280,5,15,13);}
function resetBattle(){const d=diffs[activeDiff];state={gold:d.gold,lives:20,wave:0,active:false,left:0,spawnTimer:0,enemies:[],towers:[],shots:[],selected:null,dragType:null,dragGhost:null,ended:false};speed=1;$('speed').textContent='×1';$('result').classList.remove('show');$('tower-panel').classList.remove('show');$('start-wave').disabled=false;setMsg('Drag a defence from the arsenal onto open ground.');ui();}
const path=[[-20,330],[100,330],[165,270],[260,270],[330,370],[430,370],[505,300],[595,300],[680,225],[770,225],[850,285],[990,285]].map(([x,y])=>new Phaser.Math.Vector2(x,y));
function drawWorld(s){
const g=s.add.graphics();g.fillGradientStyle(0x7f9b68,0x6e8d61,0x3c674b,0x365b45,1);g.fillRect(0,0,960,600);
// Bosphorus and shoreline
g.fillStyle(0x2b748a,1);g.fillRect(0,0,142,600);g.fillStyle(0x4b91a1,.45);g.fillRect(14,0,6,600);g.fillRect(72,0,4,600);g.fillStyle(0xd7c28b,1);g.fillRect(138,0,20,600);g.fillStyle(0x9a835d,.5);g.fillRect(154,0,8,600);
for(let y=18;y<600;y+=25){g.lineStyle(2,0xb9e2e4,.25);g.beginPath();g.moveTo(10,y);g.bezierCurveTo(46,y-5,82,y+4,126,y);g.strokePath()}
// terrain clusters
for(let i=0;i<72;i++){const x=(i*173+47)%960,y=(i*97+31)%600;if(x<170||distanceToPath(x,y)<62)continue;const r=5+(i%7);g.fillStyle(i%6===0?0x847861:0x315f3b,1);g.fillCircle(x,y,r);if(i%6!==0){g.fillStyle(0x233d2c,1);g.fillRect(x-2,y,4,10);g.fillStyle(0x47774c,.8);g.fillCircle(x-5,y-3,r*.65)}}
// road
g.lineStyle(62,0x302922,.48);drawPath(g);g.lineStyle(50,0xbda26f,1);drawPath(g);g.lineStyle(3,0xe7d6a5,.2);drawPath(g);
// city wall and gate
const wall=s.add.graphics();wall.fillStyle(0x76644e,1);wall.fillRect(900,185,60,160);wall.fillStyle(0xa18c6d,1);for(let i=0;i<5;i++)wall.fillRect(900+i*14,172,10,18);wall.fillStyle(0x332a22,1);wall.fillRect(922,276,22,69);wall.lineStyle(3,0x4d4033,.8);wall.strokeRect(900,185,60,160);
// skyline silhouettes
for(const [x,y,r] of [[820,110,35],[760,130,26],[700,145,22]]){g.fillStyle(0x31443c,.92);g.fillRect(x-r*.7,y,r*1.4,70);g.fillCircle(x,y,r);g.fillStyle(0x31443c,.92);g.fillRect(x-3,y-72,6,72);g.fillTriangle(x-7,y-72,x+7,y-72,x,y-92)}
// flag
g.fillStyle(0xc98a3d,1);g.fillRect(861,170,8,74);g.fillStyle(0x9f302c,1);g.fillTriangle(869,170,869,207,917,184);
s.add.text(22,76,'CONSTANTINOPLE',{fontFamily:'Georgia',fontSize:'18px',color:'#f6dfab',stroke:'#17221e',strokeThickness:4}).setDepth(4);
}
function drawPath(g){g.beginPath();path.forEach((p,i)=>i?g.lineTo(p.x,p.y):g.moveTo(p.x,p.y));g.strokePath()}
function distanceToPath(x,y){let best=999;for(let i=0;i<path.length-1;i++){const a=path[i],b=path[i+1],dx=b.x-a.x,dy=b.y-a.y,l=dx*dx+dy*dy,t=Math.max(0,Math.min(1,((x-a.x)*dx+(y-a.y)*dy)/l)),px=a.x+t*dx,py=a.y+t*dy;best=Math.min(best,Math.hypot(x-px,y-py))}return best}
function validPos(x,y){return x>170&&x<895&&y>88&&y<552&&distanceToPath(x,y)>54&&!state.towers.some(t=>Phaser.Math.Distance.Between(x,y,t.x,t.y)<60)}
function setupInput(s){document.querySelectorAll('.tower-card').forEach(btn=>{btn.onpointerdown=e=>{if(!state||state.ended)return;const type=btn.dataset.tower,t=towers[type];if(state.gold<t.cost){setMsg('Not enough Gold.');return}e.preventDefault();state.dragType=type;const p=toWorld(e);state.dragGhost=createTowerVisual(s,p.x,p.y,type,true);window.addEventListener('pointermove',dragMove,{passive:false});window.addEventListener('pointerup',dragEnd,{once:true})};btn.onclick=()=>{if(!state||state.ended)return;setMsg(`Hold and drag ${towers[btn.dataset.tower].name} onto the battlefield.`)}});$('start-wave').onclick=startWave;$('speed').onclick=()=>{speed=speed===1?2:1;$('speed').textContent=`×${speed}`};$('close-tower').onclick=()=>{$('tower-panel').classList.remove('show');if(state){state.selected=null;state.towers.forEach(x=>x.visual.ring.setVisible(false))}};$('sell').onclick=sellSelected;}
function toWorld(e){const canvas=$('game').querySelector('canvas');const rect=(canvas||$('game')).getBoundingClientRect();return{x:(e.clientX-rect.left)*960/rect.width,y:(e.clientY-rect.top)*600/rect.height}}
function dragMove(e){if(!state?.dragGhost)return;e.preventDefault();const p=toWorld(e);state.dragGhost.container.setPosition(p.x,p.y);const ok=validPos(p.x,p.y);state.dragGhost.ring.setStrokeStyle(3,ok?0x85e39a:0xff7a72,.9);state.dragGhost.container.setAlpha(ok?.94:.5)}
function dragEnd(e){window.removeEventListener('pointermove',dragMove);if(!state?.dragGhost)return;const p=toWorld(e),type=state.dragType,ghost=state.dragGhost;ghost.container.destroy();state.dragGhost=null;state.dragType=null;if(validPos(p.x,p.y))placeTower(type,p.x,p.y);else setMsg('Invalid placement — keep towers off the road and shoreline.')}
function createTowerVisual(s,x,y,type,ghost=false){const t=towers[type],c=s.add.container(x,y),shadow=s.add.ellipse(4,20,52,18,0x000000,.3),ring=s.add.circle(0,0,t.range,0x000000,0).setStrokeStyle(ghost?3:0,0x85e39a,.75),base=s.add.ellipse(0,12,46,22,0x65583f,1).setStrokeStyle(2,0x3d3428),parts=[];c.add([shadow,ring,base]);if(type==='ballista'){const deck=s.add.rectangle(0,1,32,14,0x7b684b).setStrokeStyle(2,0x3c3428),arm1=s.add.rectangle(9,-8,48,5,0x2f342e).setRotation(-.28),arm2=s.add.rectangle(-7,-9,26,4,0x3f3127).setRotation(.45),wheel1=s.add.circle(-12,10,7,0x3a3027).setStrokeStyle(2,0x8b7655),wheel2=s.add.circle(12,10,7,0x3a3027).setStrokeStyle(2,0x8b7655);parts.push(wheel1,wheel2,deck,arm1,arm2)}else if(type==='watchtower'){const legs=s.add.rectangle(0,0,28,34,0x65583e).setStrokeStyle(2,0x3b3025),top=s.add.polygon(0,-17,[[-22,10],[22,10],[16,-8],[-16,-8]],0x4a5f42).setStrokeStyle(2,0x26362d),banner=s.add.rectangle(14,-30,4,27,0xc7923c),flag=s.add.triangle(25,-39,0,0,0,17,25,8,0x9b2e2b);parts.push(legs,top,banner,flag)}else{const wall=s.add.ellipse(0,1,39,18,0x77704f).setStrokeStyle(2,0x3e382b);parts.push(wall);for(let i=0;i<2;i++){const ox=-7+i*14,body=s.add.rectangle(ox,0,8,18,0xcbb894),head=s.add.circle(ox,-12,6,0xd6b892),cap=s.add.circle(ox,-15,6,t.color),bow=s.add.arc(ox+4,-4,10,270,90,false,0,0).setStrokeStyle(2,0x3a2d23);parts.push(body,head,cap,bow)}}c.add(parts);c.setDepth(20+y/10);if(!ghost)c.setInteractive(new Phaser.Geom.Circle(0,0,30),Phaser.Geom.Circle.Contains).on('pointerdown',()=>selectTower(c.__tower));return{container:c,ring}}
function placeTower(type,x,y){const d=towers[type];state.gold-=d.cost;const visual=createTowerVisual(sceneRef,x,y,type,false),tower={type,x,y,tier:1,branch:null,damage:d.damage,range:d.range,rate:d.rate,cd:0,spent:d.cost,visual};visual.container.__tower=tower;visual.ring.setRadius(1).setVisible(false);state.towers.push(tower);particles(x,y,0xd7bb72,11);setMsg(`${d.name} deployed.`);ui()}
function selectTower(t){state.selected=t;$('tower-panel').classList.add('show');$('tower-name').textContent=towers[t.type].name;$('tower-stats').textContent=`Tier ${t.tier} · Damage ${Math.round(t.damage)} · Range ${Math.round(t.range)} · Rate ${t.rate.toFixed(2)}/s`;state.towers.forEach(x=>x.visual.ring.setVisible(x===t).setRadius(x.range));const options=t.tier===1?[{name:'Heavy Training',cost:.75,damage:1.35,range:1.05,branch:'power'},{name:'Rapid Drill',cost:.7,rate:1.32,range:1.08,branch:'speed'}]:t.tier===2?[{name:t.branch==='power'?'Elite Battery':'Veteran Crew',cost:1.15,damage:1.38,rate:1.18,range:1.12,branch:t.branch}]:[];$('upgrade-options').innerHTML=options.map((o,i)=>`<button data-up="${i}"><b>${o.name}</b><br><small>${Math.round(towers[t.type].cost*o.cost)} GOLD</small></button>`).join('')||'<p>Maximum tier reached.</p>';document.querySelectorAll('[data-up]').forEach((b,i)=>b.onclick=()=>upgradeTower(options[i]))}
function upgradeTower(o){const t=state.selected,cost=Math.round(towers[t.type].cost*o.cost);if(state.gold<cost){setMsg('Not enough Gold.');return}state.gold-=cost;t.spent+=cost;t.tier++;t.branch=o.branch;t.damage*=o.damage||1;t.range*=o.range||1;t.rate*=o.rate||1;t.visual.container.setScale(1+.08*(t.tier-1));particles(t.x,t.y,0xeac863,17);selectTower(t);ui()}
function sellSelected(){const t=state?.selected;if(!t)return;state.gold+=Math.round(t.spent*.62);t.visual.container.destroy();state.towers.splice(state.towers.indexOf(t),1);state.selected=null;$('tower-panel').classList.remove('show');ui()}
function startWave(){const d=diffs[activeDiff];if(state.active||state.ended||state.wave>=d.waves)return;state.wave++;state.left=4+Math.ceil(state.wave*1.15);state.spawnTimer=0;state.active=true;$('start-wave').disabled=true;setMsg(`Wave ${state.wave}: enemy formations approaching.`);ui()}
function spawnEnemy(){const d=diffs[activeDiff],heavy=state.wave>7&&Math.random()<.28,runner=!heavy&&Math.random()<.2;const hp=(heavy?220:runner?68:95)*d.hp*(1+state.wave*.04),speed0=(heavy?34:runner?70:44)*d.speed,c=sceneRef.add.container(path[0].x,path[0].y),shadow=sceneRef.add.ellipse(2,13,30,9,0x000000,.28),body=sceneRef.add.rectangle(0,2,15,23,heavy?0x584339:runner?0x456148:0x743f35).setStrokeStyle(1,0x2a211e),head=sceneRef.add.circle(0,-10,6,0xd2ae88),helmet=sceneRef.add.arc(0,-13,12,180,360,false,heavy?0x343b35:0x5d302c),weapon=sceneRef.add.rectangle(9,0,3,24,0x342b23).setRotation(-.35),barBg=sceneRef.add.rectangle(0,-25,34,5,0x131918),bar=sceneRef.add.rectangle(-16,-25,32,3,0x6ed783).setOrigin(0,.5);c.add([shadow,body,head,helmet,weapon,barBg,bar]);c.setDepth(30);state.enemies.push({x:path[0].x,y:path[0].y,pi:0,hp,maxHp:hp,speed:speed0,reward:heavy?24:runner?16:14,container:c,bar})}
function update(time,delta){if(!state||state.ended)return;const dt=Math.min(.035,delta/1000)*speed;if(state.active&&state.left>0){state.spawnTimer-=dt;if(state.spawnTimer<=0){spawnEnemy();state.left--;state.spawnTimer=.8}}for(let i=state.enemies.length-1;i>=0;i--){const e=state.enemies[i],q=path[e.pi+1];if(!q){e.container.destroy();state.enemies.splice(i,1);state.lives--;sceneRef.cameras.main.shake(110,.004);if(state.lives<=0){finish(false);return}continue}const dx=q.x-e.x,dy=q.y-e.y,dist=Math.hypot(dx,dy),m=e.speed*dt;if(dist<=m){e.x=q.x;e.y=q.y;e.pi++}else{e.x+=dx/dist*m;e.y+=dy/dist*m}e.container.setPosition(e.x,e.y);e.bar.width=32*Math.max(0,e.hp/e.maxHp)}for(const t of state.towers){t.cd-=dt;if(t.cd>0)continue;let target=null,best=-1;for(const e of state.enemies)if(Phaser.Math.Distance.Between(t.x,t.y,e.x,e.y)<=t.range&&e.pi>=best){target=e;best=e.pi}if(target){t.cd=1/t.rate;shoot(t,target)}}for(let i=state.shots.length-1;i>=0;i--){const p=state.shots[i];if(!state.enemies.includes(p.target)){p.obj.destroy();state.shots.splice(i,1);continue}const dx=p.target.x-p.x,dy=p.target.y-p.y,dist=Math.hypot(dx,dy),m=760*dt;if(dist<m+7){p.target.hp-=p.damage;p.obj.destroy();state.shots.splice(i,1);particles(p.target.x,p.target.y,p.kind==='ballista'?0xb58b52:0xffd785,p.kind==='ballista'?9:5);if(p.target.hp<=0){const idx=state.enemies.indexOf(p.target);if(idx>=0){p.target.container.destroy();state.enemies.splice(idx,1);state.gold+=p.target.reward}}}else{p.x+=dx/dist*m;p.y+=dy/dist*m;p.obj.setPosition(p.x,p.y)}}if(state.active&&!state.left&&!state.enemies.length){state.active=false;$('start-wave').disabled=false;if(state.wave>=diffs[activeDiff].waves)finish(true);else setMsg(`Wave ${state.wave} cleared. Upgrade or continue.`)}ui()}
function shoot(t,target){const obj=t.type==='ballista'?sceneRef.add.rectangle(t.x,t.y,11,3,0x3c3024).setRotation(Phaser.Math.Angle.Between(t.x,t.y,target.x,target.y)):sceneRef.add.circle(t.x,t.y,3,0xffe0a1);obj.setDepth(40);state.shots.push({x:t.x,y:t.y,target,damage:t.damage,obj,kind:t.type})}
function particles(x,y,color,n){for(let i=0;i<n;i++){const p=sceneRef.add.circle(x,y,2+Math.random()*3,color,.9).setDepth(50),tx=x+(Math.random()-.5)*70,ty=y+(Math.random()-.6)*55;sceneRef.tweens.add({targets:p,x:tx,y:ty,alpha:0,scale:.2,duration:350+Math.random()*250,onComplete:()=>p.destroy()})}}
function finish(win){state.ended=true;$('start-wave').disabled=true;$('result').classList.add('show');if(win){const d=diffs[activeDiff],first=!profile.clears[activeDiff];profile.science+=d.rewardScience;profile.coins+=d.rewardCoins;if(first){profile.medals++;profile.clears[activeDiff]=true}save();syncResources();$('result-title').textContent='CONSTANTINOPLE CLEARED';$('result-text').textContent=`${first?'New medal earned. ':'Replay complete. '}+${d.rewardScience} Science · +${d.rewardCoins} Coins. Progress saved.`}else{$('result-title').textContent='DEFEAT';$('result-text').textContent=`Reached wave ${state.wave}/${diffs[activeDiff].waves}. No permanent progress lost.`}}
})();