(()=>{
const $=id=>document.getElementById(id);
const profile=(()=>{try{return Object.assign({science:0,coins:500,medals:0,clears:{}},JSON.parse(localStorage.getItem('chronicle_phaser_v2'))||{})}catch{return{science:0,coins:500,medals:0,clears:{}}}})();
const save=()=>localStorage.setItem('chronicle_phaser_v2',JSON.stringify(profile));
let activeMap='constantinople',activeDiff='recruit',sceneRef=null,state=null,game=null,speed=1,currentPath=[];
const maps={constantinople:{name:'CONSTANTINOPLE',unlock:()=>true,baseGold:0,path:[[-20,355],[90,355],[165,300],[255,300],[325,392],[420,392],[500,330],[590,330],[680,245],[775,245],[850,305],[990,305]]},bursa:{name:'BURSA',unlock:()=>!!profile.clears['constantinople:recruit'],baseGold:40,path:[[-20,205],[105,205],[180,270],[275,270],[355,185],[450,185],[530,305],[625,305],[705,398],[800,398],[870,335],[990,335]]}};
const towers={archer:{name:'Archer Post',cost:180,damage:19,range:135,rate:.86,tex:'tower-archer'},ballista:{name:'Ballista',cost:270,damage:58,range:178,rate:.36,tex:'tower-ballista'},watchtower:{name:'Watchtower',cost:145,damage:13,range:202,rate:.68,tex:'tower-watch'}};
const diffs={recruit:{waves:12,gold:900,hp:.72,speed:.94,rewardScience:90,rewardCoins:180},veteran:{waves:18,gold:780,hp:1,speed:1,rewardScience:170,rewardCoins:320},general:{waves:24,gold:690,hp:1.34,speed:1.05,rewardScience:290,rewardCoins:520}};
const K='https://raw.githubusercontent.com/fklska/Hobbie1/2e402400daa4d93b2153f3eb65098cf65e9536de/kenney_medieval-rts/Retina/';
function sync(){['science','science2'].forEach(id=>$(id).textContent=profile.science);['coins','coins2'].forEach(id=>$(id).textContent=profile.coins);['medals','medals2'].forEach(id=>$(id).textContent=profile.medals);document.querySelectorAll('[data-map-card]').forEach(card=>{const m=card.dataset.mapCard;if(!m||!maps[m])return;const u=maps[m].unlock();card.classList.toggle('locked',!u);const badge=card.querySelector('.mapart span');if(badge)badge.textContent=u?(m==='constantinople'?'1':'2'):'🔒';const stars=card.querySelector('.stars');if(stars)stars.textContent=['recruit','veteran','general'].map(d=>profile.clears[`${m}:${d}`]?'★':'☆').join(' ');card.querySelectorAll('[data-diff]').forEach(b=>b.disabled=!u)});const p=document.querySelector('.progress p');if(p)p.textContent=maps.bursa.unlock()?'Bursa unlocked · campaign progressing':'Clear Constantinople on Recruit to unlock Bursa.'}
function screen(name){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$(name).classList.add('active');sync();if(name==='battle'){if(!window.__phaserStarted)startGame();else if(sceneRef){sceneRef.scene.restart();sceneRef.scene.resume()}}else if(sceneRef&&!sceneRef.scene.isPaused())sceneRef.scene.pause()}
$('play').onclick=()=>screen('maps');$('home-btn').onclick=()=>screen('home');$('back-maps').onclick=()=>screen('maps');$('result-map').onclick=()=>screen('maps');document.querySelectorAll('[data-map-card] [data-diff]').forEach(b=>b.onclick=()=>{const m=b.closest('[data-map-card]').dataset.mapCard;if(!maps[m]?.unlock())return;activeMap=m;activeDiff=b.dataset.diff;screen('battle')});sync();
function ui(){if(!state)return;const d=diffs[activeDiff];$('wave').textContent=`${state.wave}/${d.waves}`;$('lives').textContent=state.lives;$('gold').textContent=Math.floor(state.gold);$('battle-map-name').textContent=maps[activeMap].name;document.querySelectorAll('.tower-card').forEach(b=>b.classList.toggle('poor',state.gold<towers[b.dataset.tower].cost))}
const setMsg=t=>$('message').textContent=t;
function preload(){this.load.image('tower-archer','assets/v11/archer.png');this.load.image('tower-ballista',K+'Structure/medievalStructure_09.png');this.load.image('tower-watch',K+'Structure/medievalStructure_03.png');this.load.image('unit-light',K+'Unit/medievalUnit_01.png');this.load.image('unit-heavy',K+'Unit/medievalUnit_07.png');this.load.image('unit-runner',K+'Unit/medievalUnit_13.png');[1,2,3,4,5,6].forEach(n=>this.load.image('tree'+n,K+`Environment/medievalEnvironment_0${n}.png`));[1,2,3,4,5,6,7,8].forEach(n=>this.load.image('building'+n,K+`Structure/medievalStructure_0${n}.png`))}
function startGame(){window.__phaserStarted=true;game=new Phaser.Game({type:Phaser.AUTO,parent:'game',width:960,height:600,backgroundColor:'#20382c',render:{antialias:true,pixelArt:false},scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH},scene:{preload,create,update}})}
function create(){sceneRef=this;resetBattle();drawWorld(this);setupInput(this);this.cameras.main.fadeIn(250,4,8,8)}
function resetBattle(){const d=diffs[activeDiff];currentPath=maps[activeMap].path.map(([x,y])=>new Phaser.Math.Vector2(x,y));state={gold:d.gold+maps[activeMap].baseGold,lives:20,wave:0,active:false,left:0,spawnTimer:0,enemies:[],towers:[],shots:[],selected:null,dragType:null,dragGhost:null,ended:false,ambient:[]};speed=1;$('speed').textContent='×1';$('result').classList.remove('show');$('tower-panel').classList.remove('show');$('start-wave').disabled=false;setMsg(`Defend ${maps[activeMap].name}. Drag a defence onto open ground.`);ui()}
function drawPath(g){g.beginPath();currentPath.forEach((p,i)=>i?g.lineTo(p.x,p.y):g.moveTo(p.x,p.y));g.strokePath()}
function distanceToPath(x,y){let best=999;for(let i=0;i<currentPath.length-1;i++){const a=currentPath[i],b=currentPath[i+1],dx=b.x-a.x,dy=b.y-a.y,l=dx*dx+dy*dy,t=Math.max(0,Math.min(1,((x-a.x)*dx+(y-a.y)*dy)/l)),px=a.x+t*dx,py=a.y+t*dy;best=Math.min(best,Math.hypot(x-px,y-py))}return best}
function drawWorld(s){const g=s.add.graphics().setDepth(0);g.fillGradientStyle(activeMap==='constantinople'?0x1b5668:0x415d48,activeMap==='constantinople'?0x245f73:0x587151,0x183b45,0x2c4435,1);g.fillRect(0,0,960,600);if(activeMap==='constantinople'){g.fillGradientStyle(0x2f725b,0x456d45,0x274c37,0x203e31,1);g.fillRoundedRect(138,-30,850,660,36);g.fillStyle(0xd0bf91,1);g.fillRect(132,0,13,600);g.fillStyle(0x87775d,.8);g.fillRect(145,0,7,600);for(let y=14;y<600;y+=27){g.lineStyle(2,0x87c5d2,.20);g.lineBetween(20,y,112,y+3)}}else{g.fillGradientStyle(0x668056,0x718a5a,0x354d37,0x2a402e,1);g.fillRect(0,0,960,600)}g.lineStyle(78,0x132019,.42);drawPath(g);g.lineStyle(68,0x7a6548,.92);drawPath(g);g.lineStyle(57,0xcdb27b,1);drawPath(g);g.lineStyle(3,0xf6e2ad,.42);drawPath(g);for(let i=0;i<currentPath.length-1;i++){const a=currentPath[i],b=currentPath[i+1];for(let t=.08;t<.96;t+=.14){const x=Phaser.Math.Linear(a.x,b.x,t),y=Phaser.Math.Linear(a.y,b.y,t);g.fillStyle(0x937b58,.22);g.fillEllipse(x,y,8,3)}}if(activeMap==='constantinople'){g.fillStyle(0x5f5544,1);g.fillRect(870,120,90,300);g.fillStyle(0x988469,1);g.fillRect(882,120,78,300);g.fillStyle(0x2b241d,1);g.fillRoundedRect(906,275,31,102,8);for(let y=125;y<420;y+=22){g.lineStyle(1,0xb9a88e,.45);g.lineBetween(884,y,958,y)}for(let x=884;x<960;x+=25){g.fillStyle(0xb39a77,1);g.fillRect(x,102,17,24)}}const buildings=activeMap==='constantinople'?[[800,110,1,.92],[730,125,2,.85],[640,105,5,.78],[820,450,4,.82],[720,475,6,.72],[250,120,7,.68]]:[[820,145,1,.9],[730,115,5,.8],[650,480,2,.74],[250,95,4,.72]];buildings.forEach(([x,y,n,sc])=>{if(s.textures.exists('building'+n)){const im=s.add.image(x,y,'building'+n).setScale(sc).setDepth(5+y/20);im.setAlpha(.96)}});const trees=activeMap==='constantinople'?[[210,110,1],[300,110,2],[565,105,3],[630,475,4],[770,500,5],[520,505,2],[350,505,6]]:[[110,80,2],[220,90,4],[620,95,1],[760,100,5],[600,500,3],[350,500,6]];trees.forEach(([x,y,n],i)=>{if(s.textures.exists('tree'+n)){const im=s.add.image(x,y,'tree'+n).setScale(.72+(i%3)*.08).setDepth(7+y/20);state.ambient.push(im);s.tweens.add({targets:im,angle:{from:-.7,to:.7},duration:2400+i*180,yoyo:true,repeat:-1,ease:'Sine.inOut'})}});for(const [x,y,r] of [[245,220,120],[565,260,150],[780,360,130]]){g.fillStyle(0xf0c477,.045);g.fillCircle(x,y,r)}s.add.text(22,76,maps[activeMap].name,{fontFamily:'Georgia',fontSize:'18px',fontStyle:'bold',color:'#ffe1a2',stroke:'#0b1510',strokeThickness:5}).setDepth(50)}
function validPos(x,y){return x>35&&x<910&&y>95&&y<545&&(activeMap!=='constantinople'||x>155)&&distanceToPath(x,y)>60&&!state.towers.some(t=>Phaser.Math.Distance.Between(x,y,t.x,t.y)<78)}
function setupInput(s){document.querySelectorAll('.tower-card').forEach(btn=>{btn.onpointerdown=e=>{if(!state||state.ended)return;const type=btn.dataset.tower,t=towers[type];if(state.gold<t.cost){setMsg('Not enough Gold.');return}e.preventDefault();state.dragType=type;const p=toWorld(e);state.dragGhost=createTowerVisual(s,p.x,p.y,type,true);window.addEventListener('pointermove',dragMove,{passive:false});window.addEventListener('pointerup',dragEnd,{once:true})}});$('start-wave').onclick=startWave;$('speed').onclick=()=>{speed=speed===1?2:1;$('speed').textContent=`×${speed}`;setMsg(speed===2?'Battle speed doubled.':'Battle speed normal.')};$('close-tower').onclick=()=>{$('tower-panel').classList.remove('show');if(state){state.selected=null;state.towers.forEach(x=>x.visual.ring.setVisible(false))}};$('sell').onclick=sellSelected}
function toWorld(e){const canvas=$('game').querySelector('canvas'),rect=(canvas||$('game')).getBoundingClientRect();return{x:(e.clientX-rect.left)*960/rect.width,y:(e.clientY-rect.top)*600/rect.height}}
function dragMove(e){if(!state?.dragGhost)return;e.preventDefault();const p=toWorld(e),ok=validPos(p.x,p.y);state.dragGhost.container.setPosition(p.x,p.y);state.dragGhost.ring.setStrokeStyle(3,ok?0x78f0a0:0xff665f,.95);state.dragGhost.zone.setFillStyle(ok?0x4fd57a:0xe34c45,.14);state.dragGhost.container.setAlpha(ok?.95:.45)}
function dragEnd(e){window.removeEventListener('pointermove',dragMove);if(!state?.dragGhost)return;const p=toWorld(e),type=state.dragType;state.dragGhost.container.destroy();state.dragGhost=null;state.dragType=null;if(validPos(p.x,p.y))placeTower(type,p.x,p.y);else setMsg('Invalid placement — keep towers off the road.')}
function createTowerVisual(s,x,y,type,ghost=false){const t=towers[type],c=s.add.container(x,y),shadow=s.add.ellipse(4,31,74,23,0x000000,.36),zone=s.add.circle(0,0,t.range,ghost?0x52d77b:0,ghost?.12:0),ring=s.add.circle(0,0,t.range,0,0).setStrokeStyle(ghost?3:0,0x7ef0a4,.82),sprite=s.add.image(0,-16,t.tex);const targetSize=type==='ballista'?92:type==='watchtower'?100:104;sprite.setDisplaySize(targetSize,targetSize);if(ghost)sprite.setTint(0xb9ffd0);c.add([shadow,zone,ring,sprite]);c.setDepth(40+y/10);if(!ghost)c.setInteractive(new Phaser.Geom.Circle(0,0,45),Phaser.Geom.Circle.Contains).on('pointerdown',()=>selectTower(c.__tower));return{container:c,ring,zone,aimer:sprite,sprite}}
function placeTower(type,x,y){const d=towers[type];state.gold-=d.cost;const visual=createTowerVisual(sceneRef,x,y,type,false),tower={type,x,y,tier:1,branch:null,damage:d.damage,range:d.range,rate:d.rate,cd:0,spent:d.cost,visual};visual.container.__tower=tower;visual.ring.setVisible(false);visual.zone.setVisible(false);state.towers.push(tower);sceneRef.tweens.add({targets:visual.container,scale:{from:.65,to:1},duration:250,ease:'Back.Out'});particles(x,y,0xffcf72,18);floatText(x,y-58,'DEPLOYED',0xffe4a0);ui()}
function selectTower(t){state.selected=t;$('tower-panel').classList.add('show');$('tower-name').textContent=towers[t.type].name;$('tower-stats').textContent=`Tier ${t.tier} · Damage ${Math.round(t.damage)} · Range ${Math.round(t.range)} · Rate ${t.rate.toFixed(2)}/s`;state.towers.forEach(x=>x.visual.ring.setVisible(x===t).setRadius(x.range));const opts=t.tier===1?[{name:'Heavy Training',cost:.75,damage:1.35,range:1.05,branch:'power'},{name:'Rapid Drill',cost:.7,rate:1.32,range:1.08,branch:'speed'}]:t.tier===2?[{name:t.branch==='power'?'Elite Battery':'Veteran Crew',cost:1.15,damage:1.38,rate:1.18,range:1.12,branch:t.branch}]:[];$('upgrade-options').innerHTML=opts.map((o,i)=>`<button data-up="${i}"><b>${o.name}</b><br><small>${Math.round(towers[t.type].cost*o.cost)} GOLD</small></button>`).join('')||'<p>Maximum tier reached.</p>';document.querySelectorAll('[data-up]').forEach((b,i)=>b.onclick=()=>upgradeTower(opts[i]))}
function upgradeTower(o){const t=state.selected,c=Math.round(towers[t.type].cost*o.cost);if(state.gold<c){setMsg('Not enough Gold.');return}state.gold-=c;t.spent+=c;t.tier++;t.branch=o.branch;t.damage*=o.damage||1;t.range*=o.range||1;t.rate*=o.rate||1;t.visual.container.setScale(1+.08*(t.tier-1));t.visual.sprite.setTint(t.tier===3?0xffdf9c:0xffffff);particles(t.x,t.y,0xffd273,25);floatText(t.x,t.y-60,`TIER ${t.tier}`,0xffe398);selectTower(t);ui()}
function sellSelected(){const t=state?.selected;if(!t)return;state.gold+=Math.round(t.spent*.62);t.visual.container.destroy();state.towers.splice(state.towers.indexOf(t),1);state.selected=null;$('tower-panel').classList.remove('show');ui()}
function startWave(){const d=diffs[activeDiff];if(state.active||state.ended||state.wave>=d.waves)return;state.wave++;state.active=true;state.left=7+state.wave*2;state.spawnTimer=0;$('start-wave').disabled=true;setMsg(`Wave ${state.wave}: enemy formations approaching.`);ui()}
function spawnEnemy(){const d=diffs[activeDiff],r=Math.random(),kind=r<.18?'heavy':r<.40?'runner':'light',base=kind==='heavy'?170:kind==='runner'?68:100,hp=base*d.hp*(1+state.wave*.12),spd=(kind==='heavy'?38:kind==='runner'?78:52)*d.speed;const tex=kind==='heavy'?'unit-heavy':kind==='runner'?'unit-runner':'unit-light';const p=currentPath[0],shadow=sceneRef.add.ellipse(p.x,p.y+15,30,10,0x000000,.35).setDepth(59),spr=sceneRef.add.image(p.x,p.y,tex).setDisplaySize(kind==='heavy'?48:42,kind==='heavy'?48:42).setDepth(60);if(kind==='heavy')spr.setTint(0xd7b7aa);else if(kind==='runner')spr.setTint(0xf3c388);else spr.setTint(0xe4d0c1);const barbg=sceneRef.add.rectangle(p.x,p.y-25,34,5,0x17100f,.85).setDepth(62),bar=sceneRef.add.rectangle(p.x-16,p.y-25,32,3,0xe34438,1).setOrigin(0,.5).setDepth(63);const e={kind,hp,maxHp:hp,speed:spd,pathIndex:0,x:p.x,y:p.y,spr,shadow,bar,bg:barbg,bob:Math.random()*6.28,dead:false};state.enemies.push(e)}
function enemyStep(e,dt){let remain=e.speed*dt;while(remain>0&&!e.dead){const next=currentPath[e.pathIndex+1];if(!next){breach(e);return}const dx=next.x-e.x,dy=next.y-e.y,dist=Math.hypot(dx,dy);if(dist<=remain){e.x=next.x;e.y=next.y;e.pathIndex++;remain-=dist}else{e.x+=dx/dist*remain;e.y+=dy/dist*remain;remain=0}}e.bob+=dt*9;const by=Math.sin(e.bob)*2;e.spr.setPosition(e.x,e.y+by).setDepth(60+e.y/20);e.shadow.setPosition(e.x,e.y+17).setDepth(59+e.y/20);e.bg.setPosition(e.x,e.y-25+by);e.bar.setPosition(e.x-16,e.y-25+by);e.bar.width=32*Math.max(0,e.hp/e.maxHp);const n=currentPath[Math.min(e.pathIndex+1,currentPath.length-1)],ang=Math.atan2(n.y-e.y,n.x-e.x);e.spr.setFlipX(Math.cos(ang)<0)}
function breach(e){state.lives--;killEnemy(e,false);sceneRef.cameras.main.shake(110,.006);floatText(820,110,'BREACH!',0xff7869);ui();if(state.lives<=0)finish(false)}
function killEnemy(e,reward=true){if(e.dead)return;e.dead=true;if(reward){state.gold+=e.kind==='heavy'?34:e.kind==='runner'?18:24;particles(e.x,e.y,0xd8b06d,11);floatText(e.x,e.y-20,`+${e.kind==='heavy'?34:e.kind==='runner'?18:24}`,0xffdc80)}[e.spr,e.shadow,e.bar,e.bg].forEach(o=>o.destroy());if(reward)ui()}
function fireTower(t,target){t.cd=1/t.rate;const dx=target.x-t.x,dy=target.y-t.y,ang=Math.atan2(dy,dx);t.visual.aimer.setRotation(ang+Math.PI/2);sceneRef.tweens.add({targets:t.visual.sprite,scaleX:.90,scaleY:.90,duration:55,yoyo:true,ease:'Quad.Out'});const col=t.type==='ballista'?0xffb750:0xffe0a0,shot=sceneRef.add.rectangle(t.x,t.y-18,t.type==='ballista'?20:12,t.type==='ballista'?4:2,col,1).setRotation(ang).setDepth(90),glow=sceneRef.add.circle(t.x,t.y-18,t.type==='ballista'?7:4,0xffcf74,.55).setDepth(89);state.shots.push({obj:shot,glow,x:t.x,y:t.y-18,target,damage:t.damage,speed:t.type==='ballista'?560:720,dead:false});sceneRef.tweens.add({targets:glow,alpha:0,scale:2,duration:120,onComplete:()=>glow.destroy()})}
function shotStep(s,dt){if(s.dead||!s.target||s.target.dead){s.obj.destroy();s.glow?.destroy();s.dead=true;return}const dx=s.target.x-s.x,dy=s.target.y-s.y,dist=Math.hypot(dx,dy),step=s.speed*dt;if(dist<=step+7){s.target.hp-=s.damage;s.obj.destroy();s.dead=true;hitEffect(s.target.x,s.target.y);if(s.target.hp<=0)killEnemy(s.target,true);return}s.x+=dx/dist*step;s.y+=dy/dist*step;s.obj.setPosition(s.x,s.y).setRotation(Math.atan2(dy,dx))}
function hitEffect(x,y){const f=sceneRef.add.circle(x,y,8,0xffbe54,.9).setDepth(100);sceneRef.tweens.add({targets:f,scale:2.3,alpha:0,duration:130,onComplete:()=>f.destroy()})}
function particles(x,y,color,n){for(let i=0;i<n;i++){const p=sceneRef.add.circle(x,y,2+Math.random()*2,color,.9).setDepth(100);sceneRef.tweens.add({targets:p,x:x+(Math.random()-.5)*70,y:y+(Math.random()-.5)*55,alpha:0,scale:.2,duration:300+Math.random()*220,onComplete:()=>p.destroy()})}}
function floatText(x,y,text,color){const t=sceneRef.add.text(x,y,text,{fontFamily:'Georgia',fontSize:'14px',fontStyle:'bold',color:'#'+color.toString(16).padStart(6,'0'),stroke:'#17110b',strokeThickness:4}).setOrigin(.5).setDepth(120);sceneRef.tweens.add({targets:t,y:y-28,alpha:0,duration:700,onComplete:()=>t.destroy()})}
function finish(win){if(state.ended)return;state.ended=true;state.active=false;$('start-wave').disabled=true;const d=diffs[activeDiff];if(win){const key=`${activeMap}:${activeDiff}`,first=!profile.clears[key];profile.clears[key]=true;if(first){profile.medals=(profile.medals||0)+1;profile.science=(profile.science||0)+d.rewardScience;profile.coins=(profile.coins||0)+d.rewardCoins}save();$('result-title').textContent='VICTORY';$('result-text').textContent=first?`+${d.rewardScience} Science · +${d.rewardCoins} Coins · Medal earned`:'Map cleared again.';particles(480,250,0xffd36d,60)}else{$('result-title').textContent='DEFEAT';$('result-text').textContent='The defence line was breached.'}$('result').classList.add('show');sync()}
function update(_,delta){if(!state||state.ended)return;const dt=Math.min(delta/1000,.05)*speed;if(state.active){state.spawnTimer-=dt;if(state.left>0&&state.spawnTimer<=0){spawnEnemy();state.left--;state.spawnTimer=Math.max(.35,1.05-state.wave*.025)}if(state.left===0&&!state.enemies.some(e=>!e.dead)){state.active=false;$('start-wave').disabled=false;if(state.wave>=diffs[activeDiff].waves)finish(true);else setMsg(`Wave ${state.wave} repelled. Reinforce and continue.`)}}state.enemies.forEach(e=>!e.dead&&enemyStep(e,dt));state.towers.forEach(t=>{t.cd-=dt;if(t.cd<=0){let best=null,bd=1e9;for(const e of state.enemies){if(e.dead)continue;const d=Phaser.Math.Distance.Between(t.x,t.y,e.x,e.y);if(d<t.range&&d<bd){bd=d;best=e}}if(best)fireTower(t,best)}});state.shots.forEach(s=>!s.dead&&shotStep(s,dt));state.enemies=state.enemies.filter(e=>!e.dead);state.shots=state.shots.filter(s=>!s.dead)}
})();