(()=>{
const $=id=>document.getElementById(id);
const profile=(()=>{try{return JSON.parse(localStorage.getItem('chronicle_phaser_v2'))||{science:0,coins:500,medals:0,clears:{}}}catch{return{science:0,coins:500,medals:0,clears:{}}}})();
const save=()=>localStorage.setItem('chronicle_phaser_v2',JSON.stringify(profile));
const syncResources=()=>{for(const id of ['science','science2'])$(id).textContent=profile.science;for(const id of ['coins','coins2'])$(id).textContent=profile.coins;for(const id of ['medals','medals2'])$(id).textContent=profile.medals};
let activeDiff='recruit';
function screen(name){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$(name).classList.add('active');syncResources();if(name==='battle'&&!window.__phaserStarted)startGame();}
$('play').onclick=()=>screen('maps');$('home-btn').onclick=()=>screen('home');$('back-maps').onclick=()=>screen('maps');$('result-map').onclick=()=>screen('maps');
document.querySelectorAll('[data-diff]').forEach(b=>b.onclick=()=>{activeDiff=b.dataset.diff;screen('battle')});syncResources();
const towers={archer:{name:'Archer Post',cost:180,damage:19,range:135,rate:.82,color:0x8f2d2b},ballista:{name:'Ballista',cost:270,damage:52,range:175,rate:.38,color:0x725933},watchtower:{name:'Watchtower',cost:145,damage:13,range:198,rate:.62,color:0x486c52}};
const diffs={recruit:{waves:12,gold:900,hp:.72,speed:.94,rewardScience:90,rewardCoins:180},veteran:{waves:18,gold:780,hp:1,speed:1,rewardScience:170,rewardCoins:320},general:{waves:24,gold:690,hp:1.34,speed:1.05,rewardScience:290,rewardCoins:520}};
let sceneRef=null,state=null,game=null,speed=1;
function ui(){if(!state)return;const d=diffs[activeDiff];$('wave').textContent=`${state.wave}/${d.waves}`;$('lives').textContent=state.lives;$('gold').textContent=Math.floor(state.gold);}
function setMsg(t){$('message').textContent=t}
function startGame(){window.__phaserStarted=true;const config={type:Phaser.AUTO,parent:'game',width:960,height:600,backgroundColor:'#395c48',render:{antialias:true,pixelArt:false},scale:{mode:Phaser.Scale.RESIZE,autoCenter:Phaser.Scale.CENTER_BOTH},scene:{create,update}};game=new Phaser.Game(config);}
function create(){sceneRef=this;resetBattle();drawWorld(this);setupInput(this);}
function resetBattle(){const d=diffs[activeDiff];state={gold:d.gold,lives:20,wave:0,active:false,left:0,spawnTimer:0,enemies:[],towers:[],shots:[],selected:null,dragType:null,dragGhost:null,lastWaveEnded:true,ended:false};speed=1;$('speed').textContent='×1';$('result').classList.remove('show');$('tower-panel').classList.remove('show');ui();}
const path=[[-20,330],[100,330],[165,270],[260,270],[330,370],[430,370],[505,300],[595,300],[680,225],[770,225],[850,285],[990,285]].map(([x,y])=>new Phaser.Math.Vector2(x,y));
function drawWorld(s){const g=s.add.graphics();g.fillGradientStyle(0x6f8a55,0x6f8a55,0x3f6648,0x3f6648,1);g.fillRect(0,0,960,600);g.fillStyle(0x2b7386,1);g.fillRect(0,0,140,600);g.fillStyle(0xd2bd7e,1);g.fillRect(136,0,18,600);for(let y=18;y<600;y+=25){g.lineStyle(2,0xa7d9de,.28);g.beginPath();g.moveTo(12,y);g.bezierCurveTo(48,y-5,75,y+4,120,y);g.strokePath()}for(let i=0;i<58;i++){const x=(i*173+47)%960,y=(i*97+31)%600;if(x<165||distanceToPath(x,y)<62)continue;const r=6+(i%6);g.fillStyle(i%5===0?0x777567:0x315d39,1);g.fillCircle(x,y,r);if(i%5!==0){g.fillStyle(0x243c2c,1);g.fillRect(x-2,y,4,10)}}g.lineStyle(58,0x322b24,.45);drawPath(g);g.lineStyle(47,0xb39968,1);drawPath(g);g.lineStyle(3,0xe8d7a0,.2);drawPath(g);g.fillStyle(0x71604b,1);g.fillRect(910,210,50,125);g.fillStyle(0x9a8a6d,1);for(let i=0;i<4;i++)g.fillRect(910+i*14,198,9,16);g.fillStyle(0x30261f,1);g.fillRect(928,275,18,60);g.fillStyle(0xc98a3d,1);g.fillRect(860,170,15,70);g.fillStyle(0x8d2b28,1);g.fillTriangle(875,170,875,205,915,184);s.add.text(22,76,'CONSTANTINOPLE',{fontFamily:'Georgia',fontSize:'17px',color:'#f6dfab',stroke:'#17221e',strokeThickness:4});}
function drawPath(g){g.beginPath();path.forEach((p,i)=>i?g.lineTo(p.x,p.y):g.moveTo(p.x,p.y));g.strokePath()}
function distanceToPath(x,y){let best=999;for(let i=0;i<path.length-1;i++){const a=path[i],b=path[i+1],dx=b.x-a.x,dy=b.y-a.y,l=dx*dx+dy*dy,t=Math.max(0,Math.min(1,((x-a.x)*dx+(y-a.y)*dy)/l)),px=a.x+t*dx,py=a.y+t*dy;best=Math.min(best,Math.hypot(x-px,y-py))}return best}
function validPos(x,y){return x>170&&x<900&&y>85&&y<555&&distanceToPath(x,y)>52&&!state.towers.some(t=>Phaser.Math.Distance.Between(x,y,t.x,t.y)<58)}
function setupInput(s){document.querySelectorAll('.tower-card').forEach(btn=>{btn.onpointerdown=e=>{if(state.ended)return;const type=btn.dataset.tower,t=towers[type];if(state.gold<t.cost){setMsg('Not enough Gold.');return}state.dragType=type;const p=toWorld(e);state.dragGhost=createTowerVisual(s,p.x,p.y,type,true);window.addEventListener('pointermove',dragMove,{passive:false});window.addEventListener('pointerup',dragEnd,{once:true})}});$('start-wave').onclick=startWave;$('speed').onclick=()=>{speed=speed===1?2:1;$('speed').textContent=`×${speed}`};$('close-tower').onclick=()=>{$('tower-panel').classList.remove('show');state.selected=null};$('sell').onclick=sellSelected;}
function toWorld(e){const rect=$('game').getBoundingClientRect();return{x:(e.clientX-rect.left)*960/rect.width,y:(e.clientY-rect.top)*600/rect.height}}
function dragMove(e){if(!state.dragGhost)return;e.preventDefault();const p=toWorld(e);state.dragGhost.container.setPosition(p.x,p.y);const ok=validPos(p.x,p.y);state.dragGhost.ring.setStrokeStyle(3,ok?0x85e39a:0xff7a72,.9);state.dragGhost.container.setAlpha(ok?.92:.55)}
function dragEnd(e){window.removeEventListener('pointermove',dragMove);if(!state.dragGhost)return;const p=toWorld(e),type=state.dragType,ghost=state.dragGhost;ghost.container.destroy();state.dragGhost=null;state.dragType=null;if(validPos(p.x,p.y))placeTower(type,p.x,p.y);}
function createTowerVisual(s,x,y,type,ghost=false){const t=towers[type],c=s.add.container(x,y),shadow=s.add.ellipse(4,18,48,16,0x000000,.28),base=s.add.ellipse(0,10,42,20,0x665f42,1),ring=s.add.circle(0,0,t.range,0x000000,0).setStrokeStyle(ghost?3:0,0x85e39a,.75),parts=[];c.add([shadow,ring,base]);if(type==='ballista'){const body=s.add.rectangle(0,-2,34,16,0x625744).setStrokeStyle(2,0x2a2b25);const arm=s.add.rectangle(12,-10,44,5,0x292d29).setRotation(-.25);parts.push(body,arm)}else{for(let i=0;i<2;i++){const man=s.add.circle(-6+i*12,-8,6,t.color);const torso=s.add.rectangle(-6+i*12,4,7,16,0xe2ceb0);parts.push(man,torso)}}c.add(parts);c.setDepth(20+y/10);if(!ghost)c.setInteractive(new Phaser.Geom.Circle(0,0,28),Phaser.Geom.Circle.Contains).on('pointerdown',()=>selectTower(c.__tower));return{container:c,ring}}
function placeTower(type,x,y){const d=towers[type];state.gold-=d.cost;const visual=createTowerVisual(sceneRef,x,y,type,false),tower={type,x,y,tier:1,branch:null,damage:d.damage,range:d.range,rate:d.rate,cd:0,spent:d.cost,visual};visual.container.__tower=tower;visual.ring.setRadius(1).setVisible(false);state.towers.push(tower);particles(x,y,0xd7bb72,10);setMsg(`${d.name} deployed.`);ui()}
function selectTower(t){state.selected=t;$('tower-panel').classList.add('show');$('tower-name').textContent=towers[t.type].name;$('tower-stats').textContent=`Tier ${t.tier} · Damage ${Math.round(t.damage)} · Range ${Math.round(t.range)} · Rate ${t.rate.toFixed(2)}/s`;state.towers.forEach(x=>x.visual.ring.setVisible(x===t).setRadius(x.range));const options=t.tier===1?[{name:'Heavy Training',cost:.75,damage:1.35,range:1.05,branch:'power'},{name:'Rapid Drill',cost:.7,rate:1.32,range:1.08,branch:'speed'}]:t.tier===2?[{name:t.branch==='power'?'Elite Battery':'Veteran Crew',cost:1.15,damage:1.38,rate:1.18,range:1.12,branch:t.branch}]:[];$('upgrade-options').innerHTML=options.map((o,i)=>`<button data-up="${i}">${o.name}<br><small>${Math.round(towers[t.type].cost*o.cost)} GOLD</small></button>`).join('')||'<p>Maximum tier reached.</p>';document.querySelectorAll('[data-up]').forEach((b,i)=>b.onclick=()=>upgradeTower(options[i]))}
function upgradeTower(o){const t=state.selected,cost=Math.round(towers[t.type].cost*o.cost);if(state.gold<cost){setMsg('Not enough Gold.');return}state.gold-=cost;t.spent+=cost;t.tier++;t.branch=o.branch;t.damage*=o.damage||1;t.range*=o.range||1;t.rate*=o.rate||1;particles(t.x,t.y,0xeac863,16);selectTower(t);ui()}
function sellSelected(){const t=state.selected;if(!t)return;state.gold+=Math.round(t.spent*.62);t.visual.container.destroy();state.towers.splice(state.towers.indexOf(t),1);state.selected=null;$('tower-panel').classList.remove('show');ui()}
function startWave(){const d=diffs[activeDiff];if(state.active||state.ended||state.wave>=d.waves)return;state.wave++;state.left=4+Math.ceil(state.wave*1.15);state.spawnTimer=0;state.active=true;$('start-wave').disabled=true;setMsg(`Wave ${state.wave}: enemy formations approaching.`);ui()}
function spawnEnemy(){const d=diffs[activeDiff],heavy=state.wave>7&&Math.random()<.28,runner=Math.random()<.2;const hp=(heavy?220:runner?68:95)*d.hp*(1+state.wave*.04),speed0=(heavy?34:runner?70:44)*d.speed;const c=sceneRef.add.container(path[0].x,path[0].y),shadow=sceneRef.add.ellipse(2,12,28,8,0x000000,.25),body=sceneRef.add.rectangle(0,2,14,22,heavy?0x584339:0x743f35).setStrokeStyle(1,0x2a211e),head=sceneRef.add.circle(0,-10,6,0xd2ae88),barBg=sceneRef.add.rectangle(0,-24,32,5,0x131918),bar=sceneRef.add.rectangle(-15,-24,30,3,0x6ed783).setOrigin(0,.5);c.add([shadow,body,head,barBg,bar]);c.setDepth(30);state.enemies.push({x:path[0].x,y:path[0].y,pi:0,hp,maxHp:hp,speed:speed0,reward:heavy?24:runner?16:14,container:c,bar})}
function update(time,delta){if(!state||state.ended)return;const dt=Math.min(.035,delta/1000)*speed;if(state.active&&state.left>0){state.spawnTimer-=dt;if(state.spawnTimer<=0){spawnEnemy();state.left--;state.spawnTimer=.8}}for(let i=state.enemies.length-1;i>=0;i--){const e=state.enemies[i],q=path[e.pi+1];if(!q){e.container.destroy();state.enemies.splice(i,1);state.lives--;if(state.lives<=0){finish(false);return}continue}const dx=q.x-e.x,dy=q.y-e.y,dist=Math.hypot(dx,dy),m=e.speed*dt;if(dist<=m){e.x=q.x;e.y=q.y;e.pi++}else{e.x+=dx/dist*m;e.y+=dy/dist*m}e.container.setPosition(e.x,e.y);e.bar.width=30*Math.max(0,e.hp/e.maxHp)}for(const t of state.towers){t.cd-=dt;if(t.cd>0)continue;let target=null,best=-1;for(const e of state.enemies){if(Phaser.Math.Distance.Between(t.x,t.y,e.x,e.y)<=t.range&&e.pi>=best){target=e;best=e.pi}}if(target){t.cd=1/t.rate;shoot(t,target)}}for(let i=state.shots.length-1;i>=0;i--){const p=state.shots[i];if(!state.enemies.includes(p.target)){p.obj.destroy();state.shots.splice(i,1);continue}const dx=p.target.x-p.x,dy=p.target.y-p.y,dist=Math.hypot(dx,dy),m=760*dt;if(dist<m+7){p.target.hp-=p.damage;p.obj.destroy();state.shots.splice(i,1);particles(p.target.x,p.target.y,p.kind==='ballista'?0xb58b52:0xffd785,5);if(p.target.hp<=0){const idx=state.enemies.indexOf(p.target);if(idx>=0){p.target.container.destroy();state.enemies.splice(idx,1);state.gold+=p.target.reward}}}else{p.x+=dx/dist*m;p.y+=dy/dist*m;p.obj.setPosition(p.x,p.y)}}if(state.active&&!state.left&&!state.enemies.length){state.active=false;$('start-wave').disabled=false;if(state.wave>=diffs[activeDiff].waves)finish(true);else setMsg(`Wave ${state.wave} cleared. Upgrade or continue.`)}ui()}
function shoot(t,target){const obj=sceneRef.add.circle(t.x,t.y,t.type==='ballista'?4:3,t.type==='ballista'?0x3c3024:0xffe0a1).setDepth(40);state.shots.push({x:t.x,y:t.y,target,damage:t.damage,obj,kind:t.type});}
function particles(x,y,color,n){for(let i=0;i<n;i++){const p=sceneRef.add.circle(x,y,2+Math.random()*3,color,.9).setDepth(50),tx=x+(Math.random()-.5)*70,ty=y+(Math.random()-.6)*55;sceneRef.tweens.add({targets:p,x:tx,y:ty,alpha:0,scale:.2,duration:350+Math.random()*250,onComplete:()=>p.destroy()})}}
function finish(win){state.ended=true;$('start-wave').disabled=true;$('result').classList.add('show');if(win){const d=diffs[activeDiff],first=!profile.clears[activeDiff];profile.science+=d.rewardScience;profile.coins+=d.rewardCoins;if(first){profile.medals++;profile.clears[activeDiff]=true}save();syncResources();$('result-title').textContent='CONSTANTINOPLE CLEARED';$('result-text').textContent=`${first?'New medal earned. ':'Replay complete. '}+${d.rewardScience} Science · +${d.rewardCoins} Coins. Progress saved.`}else{$('result-title').textContent='DEFEAT';$('result-text').textContent=`Reached wave ${state.wave}/${diffs[activeDiff].waves}. No permanent progress lost.`}}
})();