(()=>{
const $=id=>document.getElementById(id);
const profile=(()=>{try{return JSON.parse(localStorage.getItem('chronicle_phaser_v2'))||{science:0,coins:500,medals:0,clears:{}}}catch{return{science:0,coins:500,medals:0,clears:{}}}})();
const save=()=>localStorage.setItem('chronicle_phaser_v2',JSON.stringify(profile));
const syncResources=()=>{for(const id of ['science','science2'])$(id).textContent=profile.science;for(const id of ['coins','coins2'])$(id).textContent=profile.coins;for(const id of ['medals','medals2'])$(id).textContent=profile.medals;document.querySelector('.stars').textContent=['recruit','veteran','general'].map(k=>profile.clears[k]?'★':'☆').join(' ')};
let activeDiff='recruit',sceneRef=null,state=null,game=null,speed=1;
const towers={archer:{name:'Archer Post',cost:180,damage:19,range:135,rate:.86,color:0x9e302b},ballista:{name:'Ballista',cost:270,damage:58,range:178,rate:.36,color:0x725933},watchtower:{name:'Watchtower',cost:145,damage:13,range:202,rate:.68,color:0x486c52}};
const diffs={recruit:{waves:12,gold:900,hp:.72,speed:.94,rewardScience:90,rewardCoins:180},veteran:{waves:18,gold:780,hp:1,speed:1,rewardScience:170,rewardCoins:320},general:{waves:24,gold:690,hp:1.34,speed:1.05,rewardScience:290,rewardCoins:520}};
function screen(name){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$(name).classList.add('active');syncResources();if(name==='battle'){if(!window.__phaserStarted)startGame();else if(sceneRef){sceneRef.scene.restart();sceneRef.scene.resume();}}else if(sceneRef&&!sceneRef.scene.isPaused())sceneRef.scene.pause();}
$('play').onclick=()=>screen('maps');$('home-btn').onclick=()=>screen('home');$('back-maps').onclick=()=>screen('maps');$('result-map').onclick=()=>screen('maps');
document.querySelectorAll('[data-diff]').forEach(b=>b.onclick=()=>{activeDiff=b.dataset.diff;screen('battle')});syncResources();
function ui(){if(!state)return;const d=diffs[activeDiff];$('wave').textContent=`${state.wave}/${d.waves}`;$('lives').textContent=state.lives;$('gold').textContent=Math.floor(state.gold);document.querySelectorAll('.tower-card').forEach(b=>b.classList.toggle('poor',state.gold<towers[b.dataset.tower].cost));}
const setMsg=t=>$('message').textContent=t;
function startGame(){window.__phaserStarted=true;const config={type:Phaser.AUTO,parent:'game',width:960,height:600,backgroundColor:'#365b45',render:{antialias:true,pixelArt:false},scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH},scene:{create,update}};game=new Phaser.Game(config)}
function create(){sceneRef=this;resetBattle();drawWorld(this);setupInput(this);this.cameras.main.fadeIn(320,5,15,13);}
function resetBattle(){const d=diffs[activeDiff];state={gold:d.gold,lives:20,wave:0,active:false,left:0,spawnTimer:0,enemies:[],towers:[],shots:[],selected:null,dragType:null,dragGhost:null,ended:false,water:[],boats:[],embers:[]};speed=1;$('speed').textContent='×1';$('result').classList.remove('show');$('tower-panel').classList.remove('show');$('start-wave').disabled=false;setMsg('Drag a defence from the arsenal onto open ground.');ui();}
const path=[[-20,330],[100,330],[165,270],[260,270],[330,370],[430,370],[505,300],[595,300],[680,225],[770,225],[850,285],[990,285]].map(([x,y])=>new Phaser.Math.Vector2(x,y));
function drawPath(g){g.beginPath();path.forEach((p,i)=>i?g.lineTo(p.x,p.y):g.moveTo(p.x,p.y));g.strokePath()}
function distanceToPath(x,y){let best=999;for(let i=0;i<path.length-1;i++){const a=path[i],b=path[i+1],dx=b.x-a.x,dy=b.y-a.y,l=dx*dx+dy*dy,t=Math.max(0,Math.min(1,((x-a.x)*dx+(y-a.y)*dy)/l)),px=a.x+t*dx,py=a.y+t*dy;best=Math.min(best,Math.hypot(x-px,y-py))}return best}
function drawWorld(s){const g=s.add.graphics();g.fillGradientStyle(0x86a371,0x729163,0x436b4e,0x365c45,1);g.fillRect(0,0,960,600);
// soft terrain bands
g.fillStyle(0x567a54,.28);g.fillEllipse(570,170,520,260);g.fillStyle(0x294c3d,.18);g.fillEllipse(690,520,680,240);
// Bosphorus
g.fillGradientStyle(0x2d8297,0x337b8b,0x1d667a,0x225b6b,1);g.fillRect(0,0,145,600);g.fillStyle(0xd8c38e,1);g.fillRect(139,0,19,600);g.fillStyle(0x8d7956,.5);g.fillRect(156,0,8,600);
for(let y=18;y<600;y+=22){const wave=s.add.rectangle(66,y,105,2,0xbde7e7,.28).setDepth(1);state.water.push({obj:wave,base:y,phase:y*.07})}
// shoreline rocks
for(let i=0;i<20;i++){const y=(i*47+13)%600,x=148+(i%3)*5;g.fillStyle(i%2?0x7f755f:0x96876b,.85);g.fillCircle(x,y,4+(i%4))}
// terrain details
for(let i=0;i<84;i++){const x=(i*173+47)%960,y=(i*97+31)%600;if(x<170||distanceToPath(x,y)<66)continue;const r=5+(i%8);if(i%7===0){g.fillStyle(0x897e67,.8);g.fillCircle(x,y,r*.7);g.fillCircle(x+6,y+2,r*.45)}else{g.fillStyle(0x243f2e,1);g.fillRect(x-2,y+1,4,10);g.fillStyle(i%3?0x3d7044:0x4b7b50,1);g.fillCircle(x,y,r);g.fillStyle(0x6f9660,.55);g.fillCircle(x-4,y-4,r*.5)}}
// road shadows and surface
g.lineStyle(68,0x171915,.28);drawPath(g);g.lineStyle(58,0x7d6748,.42);drawPath(g);g.lineStyle(49,0xc5aa75,1);drawPath(g);g.lineStyle(2,0xf0dfb0,.22);drawPath(g);
// road stones
for(let i=0;i<34;i++){const p=path[Math.min(path.length-2,Math.floor(i/(34/(path.length-1))))],x=p.x+(i%3-1)*8,y=p.y+((i*17)%19-9);g.fillStyle(0x8d7653,.25);g.fillCircle(x,y,2+(i%3))}
// city wall
g.fillStyle(0x74634e,1);g.fillRect(899,183,61,164);g.fillStyle(0xa38e6c,1);for(let i=0;i<5;i++)g.fillRect(900+i*14,171,10,18);g.fillStyle(0x332a22,1);g.fillRect(921,275,23,72);g.lineStyle(3,0x4b3d31,.75);g.strokeRect(899,183,61,164);
// skyline
for(const [x,y,r] of [[824,108,35],[766,129,27],[707,145,23],[650,157,17]]){g.fillStyle(0x253f37,.94);g.fillRect(x-r*.72,y,r*1.44,72);g.fillCircle(x,y,r);g.fillRect(x-3,y-74,6,74);g.fillTriangle(x-7,y-74,x+7,y-74,x,y-95)}
// Ottoman flag
g.fillStyle(0xd19b47,1);g.fillRect(862,169,7,76);g.fillStyle(0xa52825,1);g.fillTriangle(869,169,869,209,917,185);
// boats on water
for(const [x,y] of [[58,118],[91,445]]){const c=s.add.container(x,y).setDepth(3),h=s.add.ellipse(0,0,32,10,0x4d3828).setStrokeStyle(2,0x261b14),mast=s.add.rectangle(0,-16,3,34,0x6d5035),sail=s.add.triangle(11,-23,0,0,0,25,19,19,0xddd2ad);c.add([h,mast,sail]);state.boats.push({obj:c,base:y,phase:y*.03})}
s.add.text(22,76,'CONSTANTINOPLE',{fontFamily:'Georgia',fontSize:'18px',color:'#f6dfab',stroke:'#17221e',strokeThickness:4}).setDepth(5);
}
function validPos(x,y){return x>170&&x<895&&y>88&&y<552&&distanceToPath(x,y)>56&&!state.towers.some(t=>Phaser.Math.Distance.Between(x,y,t.x,t.y)<62)}
function setupInput(s){document.querySelectorAll('.tower-card').forEach(btn=>{btn.onpointerdown=e=>{if(!state||state.ended)return;const type=btn.dataset.tower,t=towers[type];if(state.gold<t.cost){setMsg('Not enough Gold.');return}e.preventDefault();state.dragType=type;const p=toWorld(e);state.dragGhost=createTowerVisual(s,p.x,p.y,type,true);window.addEventListener('pointermove',dragMove,{passive:false});window.addEventListener('pointerup',dragEnd,{once:true})};btn.onclick=()=>{if(state)setMsg(`Hold and drag ${towers[btn.dataset.tower].name} onto the battlefield.`)}});$('start-wave').onclick=startWave;$('speed').onclick=()=>{speed=speed===1?2:1;$('speed').textContent=`×${speed}`;setMsg(speed===2?'Battle speed doubled.':'Battle speed normal.')};$('close-tower').onclick=()=>{$('tower-panel').classList.remove('show');if(state){state.selected=null;state.towers.forEach(x=>x.visual.ring.setVisible(false))}};$('sell').onclick=sellSelected;}
function toWorld(e){const canvas=$('game').querySelector('canvas');const rect=(canvas||$('game')).getBoundingClientRect();return{x:(e.clientX-rect.left)*960/rect.width,y:(e.clientY-rect.top)*600/rect.height}}
function dragMove(e){if(!state?.dragGhost)return;e.preventDefault();const p=toWorld(e);state.dragGhost.container.setPosition(p.x,p.y);const ok=validPos(p.x,p.y);state.dragGhost.ring.setStrokeStyle(4,ok?0x91e9a0:0xff786d,.92);state.dragGhost.zone.setFillStyle(ok?0x59c773:0xe24e45,.13);state.dragGhost.container.setAlpha(ok?.98:.52)}
function dragEnd(e){window.removeEventListener('pointermove',dragMove);if(!state?.dragGhost)return;const p=toWorld(e),type=state.dragType;state.dragGhost.container.destroy();state.dragGhost=null;state.dragType=null;if(validPos(p.x,p.y))placeTower(type,p.x,p.y);else setMsg('Invalid placement — keep towers off the road and shoreline.')}
function createTowerVisual(s,x,y,type,ghost=false){const t=towers[type],c=s.add.container(x,y),shadow=s.add.ellipse(4,20,54,18,0x000000,.3),zone=s.add.circle(0,0,t.range,ghost?0x59c773:0,ghost?.12:0),ring=s.add.circle(0,0,t.range,0,0).setStrokeStyle(ghost?4:0,0x91e9a0,.8),base=s.add.ellipse(0,12,48,23,0x675a40,1).setStrokeStyle(2,0x3a3024),parts=[];c.add([shadow,zone,ring,base]);let aimer=null;
if(type==='ballista'){const wheel1=s.add.circle(-13,10,8,0x382e24).setStrokeStyle(2,0x8b7655),wheel2=s.add.circle(13,10,8,0x382e24).setStrokeStyle(2,0x8b7655),deck=s.add.rectangle(0,0,34,14,0x796548).setStrokeStyle(2,0x3a3025),turret=s.add.container(0,-4),arm=s.add.rectangle(13,0,50,5,0x2c312c),bow=s.add.rectangle(34,0,4,32,0x4a3828);turret.add([arm,bow]);aimer=turret;parts.push(wheel1,wheel2,deck,turret)}
else if(type==='watchtower'){const legs=s.add.rectangle(0,1,29,36,0x665a40).setStrokeStyle(2,0x352d23),deck=s.add.polygon(0,-19,[[-23,10],[23,10],[17,-9],[-17,-9]],0x3f6047).setStrokeStyle(2,0x263a2e),roof=s.add.triangle(0,-34,-25,7,25,7,0,-12,0x7d322d),archer=s.add.circle(0,-23,6,0xd5b790),bow=s.add.arc(7,-21,10,270,90,false,0,0).setStrokeStyle(2,0x33271f);aimer=s.add.container(0,0,[archer,bow]);parts.push(legs,deck,roof,aimer)}
else{const wall=s.add.ellipse(0,1,40,18,0x756e4d).setStrokeStyle(2,0x3b3529);parts.push(wall);aimer=s.add.container(0,0);for(let i=0;i<2;i++){const ox=-8+i*16,body=s.add.rectangle(ox,0,8,18,0xcab893),head=s.add.circle(ox,-12,6,0xd8ba92),cap=s.add.circle(ox,-15,6,t.color),bow=s.add.arc(ox+5,-4,10,270,90,false,0,0).setStrokeStyle(2,0x34281f);aimer.add([body,head,cap,bow])}parts.push(aimer)}
c.add(parts);c.setDepth(20+y/10);if(!ghost)c.setInteractive(new Phaser.Geom.Circle(0,0,31),Phaser.Geom.Circle.Contains).on('pointerdown',()=>selectTower(c.__tower));return{container:c,ring,zone,aimer}}
function placeTower(type,x,y){const d=towers[type];state.gold-=d.cost;const visual=createTowerVisual(sceneRef,x,y,type,false),tower={type,x,y,tier:1,branch:null,damage:d.damage,range:d.range,rate:d.rate,cd:0,spent:d.cost,visual,target:null};visual.container.__tower=tower;visual.ring.setRadius(1).setVisible(false);visual.zone.setVisible(false);state.towers.push(tower);particles(x,y,0xe0c37e,14,60);floatText(x,y-32,'DEPLOYED',0xf6dea4);setMsg(`${d.name} deployed.`);ui()}
function selectTower(t){state.selected=t;$('tower-panel').classList.add('show');$('tower-name').textContent=towers[t.type].name;$('tower-stats').textContent=`Tier ${t.tier} · Damage ${Math.round(t.damage)} · Range ${Math.round(t.range)} · Rate ${t.rate.toFixed(2)}/s`;state.towers.forEach(x=>x.visual.ring.setVisible(x===t).setRadius(x.range));const options=t.tier===1?[{name:'Heavy Training',cost:.75,damage:1.35,range:1.05,branch:'power'},{name:'Rapid Drill',cost:.7,rate:1.32,range:1.08,branch:'speed'}]:t.tier===2?[{name:t.branch==='power'?'Elite Battery':'Veteran Crew',cost:1.15,damage:1.38,rate:1.18,range:1.12,branch:t.branch}]:[];$('upgrade-options').innerHTML=options.map((o,i)=>`<button data-up="${i}"><b>${o.name}</b><br><small>${Math.round(towers[t.type].cost*o.cost)} GOLD</small></button>`).join('')||'<p>Maximum tier reached.</p>';document.querySelectorAll('[data-up]').forEach((b,i)=>b.onclick=()=>upgradeTower(options[i]))}
function upgradeTower(o){const t=state.selected,cost=Math.round(towers[t.type].cost*o.cost);if(state.gold<cost){setMsg('Not enough Gold.');return}state.gold-=cost;t.spent+=cost;t.tier++;t.branch=o.branch;t.damage*=o.damage||1;t.range*=o.range||1;t.rate*=o.rate||1;t.visual.container.setScale(1+.08*(t.tier-1));particles(t.x,t.y,0xffd76d,18,75);floatText(t.x,t.y-42,`TIER ${t.tier}`,0xffdf78);selectTower(t);ui()}
function sellSelected(){const t=state?.selected;if(!t)return;const refund=Math.round(t.spent*.62);state.gold+=refund;floatText(t.x,t.y-30,`+${refund}`,0x9ce6a3);t.visual.container.destroy();state.towers.splice(state.towers.indexOf(t),1);state.selected=null;$('tower-panel').classList.remove('show');ui()}
function startWave(){const d=diffs[activeDiff];if(state.active||state.ended||state.wave>=d.waves)return;state.wave++;state.left=4+Math.ceil(state.wave*1.15);state.spawnTimer=0;state.active=true;$('start-wave').disabled=true;setMsg(`Wave ${state.wave}: enemy formations approaching.`);sceneRef.cameras.main.flash(120,219,183,99,false);ui()}
function spawnEnemy(){const d=diffs[activeDiff],heavy=state.wave>7&&Math.random()<.28,runner=!heavy&&Math.random()<.2;const hp=(heavy?220:runner?68:95)*d.hp*(1+state.wave*.04),speed0=(heavy?34:runner?70:44)*d.speed,c=sceneRef.add.container(path[0].x,path[0].y),shadow=sceneRef.add.ellipse(2,14,31,9,0x000000,.26),leg1=sceneRef.add.rectangle(-4,10,4,12,0x2a231f),leg2=sceneRef.add.rectangle(4,10,4,12,0x2a231f),body=sceneRef.add.rectangle(0,0,16,24,heavy?0x55463c:runner?0x42664b:0x7a4035).setStrokeStyle(1,0x2a211e),head=sceneRef.add.circle(0,-12,6,0xd2ae88),helmet=sceneRef.add.arc(0,-15,12,180,360,false,heavy?0x343b35:0x5d302c),weapon=sceneRef.add.rectangle(10,-1,3,26,0x342b23).setRotation(-.35),barBg=sceneRef.add.rectangle(0,-28,36,5,0x111716),bar=sceneRef.add.rectangle(-17,-28,34,3,0x72d889).setOrigin(0,.5);c.add([shadow,leg1,leg2,body,head,helmet,weapon,barBg,bar]);c.setDepth(30);sceneRef.tweens.add({targets:[leg1,leg2],angle:{from:-14,to:14},duration:180,yoyo:true,repeat:-1});state.enemies.push({x:path[0].x,y:path[0].y,pi:0,hp,maxHp:hp,speed:speed0,reward:heavy?24:runner?16:14,container:c,bar,bob:Math.random()*6.28,kind:heavy?'heavy':runner?'runner':'infantry'})}
function shoot(t,target){t.target=target;if(t.visual.aimer){const a=Phaser.Math.Angle.Between(t.x,t.y,target.x,target.y);t.visual.aimer.setRotation(a)}const isBall=t.type==='ballista',obj=isBall?sceneRef.add.rectangle(t.x,t.y,14,3,0x2f241b).setRotation(Phaser.Math.Angle.Between(t.x,t.y,target.x,target.y)):sceneRef.add.triangle(t.x,t.y,0,-4,12,0,0,4,0xf2d58e).setRotation(Phaser.Math.Angle.Between(t.x,t.y,target.x,target.y));obj.setDepth(40);state.shots.push({x:t.x,y:t.y,target,damage:t.damage,obj,kind:t.type});if(isBall){sceneRef.tweens.add({targets:t.visual.aimer,x:-6,duration:55,yoyo:true});particles(t.x,t.y,0xe2c48a,5,28)}else sceneRef.tweens.add({targets:t.visual.aimer,scaleX:.92,scaleY:.92,duration:45,yoyo:true})}
function particles(x,y,color,n,spread=55){for(let i=0;i<n;i++){const p=sceneRef.add.circle(x,y,2+Math.random()*3,color,.9).setDepth(50),tx=x+(Math.random()-.5)*spread,ty=y+(Math.random()-.6)*spread*.7;sceneRef.tweens.add({targets:p,x:tx,y:ty,alpha:0,scale:.2,duration:260+Math.random()*260,onComplete:()=>p.destroy()})}}
function floatText(x,y,text,color){const t=sceneRef.add.text(x,y,text,{fontFamily:'Georgia',fontSize:'13px',fontStyle:'bold',color:'#'+color.toString(16).padStart(6,'0'),stroke:'#142019',strokeThickness:3}).setOrigin(.5).setDepth(70);sceneRef.tweens.add({targets:t,y:y-26,alpha:0,duration:650,onComplete:()=>t.destroy()})}
function update(time,delta){if(!state||state.ended)return;const dt=Math.min(.035,delta/1000)*speed;
state.water.forEach((w,i)=>{w.obj.x=66+Math.sin(time*.0015+w.phase)*7;w.obj.alpha=.18+.12*Math.sin(time*.002+w.phase)});state.boats.forEach(b=>{b.obj.y=b.base+Math.sin(time*.0018+b.phase)*3;b.obj.angle=Math.sin(time*.001+b.phase)*2});
if(state.active&&state.left>0){state.spawnTimer-=dt;if(state.spawnTimer<=0){spawnEnemy();state.left--;state.spawnTimer=.78}}
for(let i=state.enemies.length-1;i>=0;i--){const e=state.enemies[i],q=path[e.pi+1];if(!q){e.container.destroy();state.enemies.splice(i,1);state.lives--;sceneRef.cameras.main.shake(110,.004);floatText(870,300,'BREACH!',0xff8678);if(state.lives<=0){finish(false);return}continue}const dx=q.x-e.x,dy=q.y-e.y,dist=Math.hypot(dx,dy),m=e.speed*dt;if(dist<=m){e.x=q.x;e.y=q.y;e.pi++}else{e.x+=dx/dist*m;e.y+=dy/dist*m}e.bob+=dt*5;e.container.setPosition(e.x,e.y+Math.sin(e.bob)*1.7);e.container.setDepth(30+e.y/20);e.bar.width=34*Math.max(0,e.hp/e.maxHp)}
for(const t of state.towers){t.cd-=dt;if(t.cd>0)continue;let target=null,best=-1;for(const e of state.enemies)if(Phaser.Math.Distance.Between(t.x,t.y,e.x,e.y)<=t.range&&e.pi>=best){target=e;best=e.pi}if(target){t.cd=1/t.rate;shoot(t,target)}}
for(let i=state.shots.length-1;i>=0;i--){const p=state.shots[i];if(!state.enemies.includes(p.target)){p.obj.destroy();state.shots.splice(i,1);continue}const dx=p.target.x-p.x,dy=p.target.y-p.y,dist=Math.hypot(dx,dy),m=(p.kind==='ballista'?680:850)*dt;if(dist<m+8){p.target.hp-=p.damage;p.obj.destroy();state.shots.splice(i,1);const heavy=p.kind==='ballista';particles(p.target.x,p.target.y,heavy?0xd3a36a:0xffdf8d,heavy?13:6,heavy?80:38);if(heavy)sceneRef.cameras.main.shake(70,.002);if(p.target.hp<=0){const idx=state.enemies.indexOf(p.target);if(idx>=0){const reward=p.target.reward,x=p.target.x,y=p.target.y;p.target.container.destroy();state.enemies.splice(idx,1);state.gold+=reward;floatText(x,y-24,`+${reward}`,0xa4e6a8);particles(x,y,0x6d342f,7,42)}}}else{p.x+=dx/dist*m;p.y+=dy/dist*m;p.obj.setPosition(p.x,p.y);p.obj.setRotation(Phaser.Math.Angle.Between(p.x,p.y,p.target.x,p.target.y))}}
if(state.active&&!state.left&&!state.enemies.length){state.active=false;$('start-wave').disabled=false;if(state.wave>=diffs[activeDiff].waves)finish(true);else{setMsg(`Wave ${state.wave} cleared. Upgrade or continue.`);sceneRef.cameras.main.flash(100,120,200,130,false)}}ui()}
function finish(win){state.ended=true;$('start-wave').disabled=true;$('result').classList.add('show');if(win){const d=diffs[activeDiff],first=!profile.clears[activeDiff];profile.science+=d.rewardScience;profile.coins+=d.rewardCoins;if(first){profile.medals++;profile.clears[activeDiff]=true}save();syncResources();sceneRef.cameras.main.flash(350,236,196,96,false);$('result-title').textContent='CONSTANTINOPLE CLEARED';$('result-text').textContent=`${first?'New medal earned. ':'Replay complete. '}+${d.rewardScience} Science · +${d.rewardCoins} Coins. Progress saved.`}else{$('result-title').textContent='DEFEAT';$('result-text').textContent=`Reached wave ${state.wave}/${diffs[activeDiff].waves}. No permanent progress lost.`}}
})();