import * as THREE from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import * as SkeletonUtils from 'three/addons/utils/SkeletonUtils.js';

const $=id=>document.getElementById(id);
const ui={loading:$('loading'),loadStatus:$('load-status'),loadFill:$('load-fill'),hud:$('hud'),message:$('message'),arsenal:$('arsenal'),start:$('start-wave'),speed:$('speed'),wave:$('wave'),lives:$('lives'),gold:$('gold'),info:$('tower-info'),infoName:$('tower-name'),infoStats:$('tower-stats'),closeInfo:$('close-info'),fatal:$('fatal'),fatalText:$('fatal-text'),result:$('result'),resultTitle:$('result-title'),resultText:$('result-text'),replay:$('replay')};
const stage=$('stage');
const RAW='https://raw.githubusercontent.com/sion-rgb/tactical-slash/main/assets/';
const URLS={
  enemy:RAW+'characters/enemy/enemy_swordsman.glb',
  archer:RAW+'characters/player/player_archer.glb',
  wall:RAW+'environment/dungeon_wall.glb',
  pillar:RAW+'environment/dungeon_pillar.glb',
  tree:RAW+'environment/nature_tree.glb',
  bush:RAW+'environment/nature_bush.glb',
  rock:RAW+'environment/nature_rock.glb',
  crate:RAW+'environment/dungeon_crate.glb'
};
const DEF={
  archer:{name:'ARCHER POST',cost:180,range:4.8,damage:24,rate:.88,color:0xe7c574},
  ballista:{name:'BALLISTA',cost:270,range:6.2,damage:66,rate:.38,color:0xf0a357},
  watchtower:{name:'WATCHTOWER',cost:145,range:5.4,damage:16,rate:1.2,color:0xb7d7c5}
};
const state={gold:900,lives:20,wave:0,maxWaves:12,speed:1,active:false,ended:false,spawnLeft:0,spawnClock:0,enemies:[],towers:[],projectiles:[],effects:[],mixers:[],selected:null,drag:null,time:0};
let scene,camera,renderer,clock,loader,assets={},roadCurve,roadSamples=[],pathLength=1,groundPlane,raycaster,pointer,waterTexture,glowTexture;

function fatal(msg){ui.fatalText.textContent=msg;ui.fatal.classList.remove('hidden');ui.loading.classList.add('hidden');console.error(msg)}
function setMessage(msg){ui.message.textContent=msg}
function updateUI(){ui.wave.textContent=`${state.wave} / ${state.maxWaves}`;ui.lives.textContent=state.lives;ui.gold.textContent=Math.floor(state.gold);document.querySelectorAll('.tower-card').forEach(b=>b.classList.toggle('poor',state.gold<DEF[b.dataset.tower].cost))}
function setProgress(i,total,label){ui.loadStatus.textContent=label;ui.loadFill.style.width=`${Math.max(4,Math.round(i/total*100))}%`}

function canvasTexture(draw,w=512,h=512){const c=document.createElement('canvas');c.width=w;c.height=h;const x=c.getContext('2d');draw(x,c);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.wrapS=t.wrapT=THREE.RepeatWrapping;t.anisotropy=8;return t}
function makeGroundTexture(){return canvasTexture((x,c)=>{x.fillStyle='#4f6843';x.fillRect(0,0,c.width,c.height);for(let i=0;i<4300;i++){const g=63+Math.random()*55;x.fillStyle=`rgba(${g|0},${(g+22)|0},${(g*.64)|0},${.035+Math.random()*.08})`;const r=.5+Math.random()*2.8;x.beginPath();x.arc(Math.random()*c.width,Math.random()*c.height,r,0,Math.PI*2);x.fill()}for(let i=0;i<80;i++){x.strokeStyle='rgba(40,65,34,.11)';x.lineWidth=1+Math.random()*2;x.beginPath();const px=Math.random()*c.width,py=Math.random()*c.height;x.moveTo(px,py);x.lineTo(px+Math.random()*30-15,py+Math.random()*30-15);x.stroke()}},512,512)}
function makeRoadTexture(){return canvasTexture((x,c)=>{x.fillStyle='#b9a172';x.fillRect(0,0,c.width,c.height);for(let y=0;y<c.height;y+=28){const off=(Math.floor(y/28)%2)*23;for(let xx=-30;xx<c.width+30;xx+=46){x.fillStyle=`rgba(${120+Math.random()*28|0},${105+Math.random()*23|0},${75+Math.random()*18|0},.32)`;x.strokeStyle='rgba(74,59,42,.28)';x.lineWidth=2;x.beginPath();if(x.roundRect)x.roundRect(xx+off+2,y+2,40,22,5);else x.rect(xx+off+2,y+2,40,22);x.fill();x.stroke()}}x.fillStyle='rgba(255,234,181,.10)';for(let i=0;i<220;i++)x.fillRect(Math.random()*c.width,Math.random()*c.height,1+Math.random()*3,1+Math.random()*3)},512,256)}
function makeWaterTexture(){return canvasTexture((x,c)=>{const g=x.createLinearGradient(0,0,c.width,c.height);g.addColorStop(0,'#235d70');g.addColorStop(.5,'#164859');g.addColorStop(1,'#0d3545');x.fillStyle=g;x.fillRect(0,0,c.width,c.height);for(let i=0;i<90;i++){x.strokeStyle=`rgba(165,220,225,${.035+Math.random()*.12})`;x.lineWidth=1+Math.random()*2;x.beginPath();const y=Math.random()*c.height,xx=Math.random()*c.width;x.moveTo(xx,y);x.lineTo(xx+40+Math.random()*140,y+Math.random()*4-2);x.stroke()}},512,512)}
function makeGlowTexture(){const t=canvasTexture((x,c)=>{const g=x.createRadialGradient(256,256,0,256,256,250);g.addColorStop(0,'rgba(255,240,178,1)');g.addColorStop(.2,'rgba(255,170,70,.9)');g.addColorStop(.55,'rgba(255,92,20,.25)');g.addColorStop(1,'rgba(255,60,0,0)');x.fillStyle=g;x.fillRect(0,0,512,512)});t.wrapS=t.wrapT=THREE.ClampToEdgeWrapping;return t}
function makeFlagTexture(){const c=document.createElement('canvas');c.width=256;c.height=160;const x=c.getContext('2d');x.fillStyle='#8f1824';x.fillRect(0,0,256,160);x.fillStyle='#f0d9a2';x.beginPath();x.arc(107,80,42,0,Math.PI*2);x.fill();x.fillStyle='#8f1824';x.beginPath();x.arc(122,72,38,0,Math.PI*2);x.fill();x.fillStyle='#f0d9a2';x.font='38px Georgia';x.fillText('✦',137,92);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t}

function makeScene(){scene=new THREE.Scene();scene.background=new THREE.Color(0x738c98);scene.fog=new THREE.Fog(0x7f9296,19,42);const aspect=innerWidth/innerHeight;const span=17;camera=new THREE.OrthographicCamera(-span*aspect/2,span*aspect/2,span/2,-span/2,.1,100);camera.position.set(16,18,20);camera.lookAt(0,0,-.4);renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;stage.appendChild(renderer.domElement);clock=new THREE.Clock();raycaster=new THREE.Raycaster();pointer=new THREE.Vector2();scene.add(new THREE.HemisphereLight(0xbfd4dd,0x3f4934,2.1));const sun=new THREE.DirectionalLight(0xffe0b0,3.8);sun.position.set(-9,20,10);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-18;sun.shadow.camera.right=18;sun.shadow.camera.top=16;sun.shadow.camera.bottom=-16;sun.shadow.camera.near=1;sun.shadow.camera.far=55;sun.shadow.bias=-.0008;scene.add(sun);const fill=new THREE.DirectionalLight(0x7fb0c7,.8);fill.position.set(12,8,-12);scene.add(fill);window.addEventListener('resize',resize);glowTexture=makeGlowTexture()}
function resize(){if(!renderer)return;const aspect=innerWidth/innerHeight,span=17;camera.left=-span*aspect/2;camera.right=span*aspect/2;camera.top=span/2;camera.bottom=-span/2;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)}

function prep(root){root.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;if(o.material){o.material=o.material.clone();o.material.side=THREE.FrontSide}}});return root}
function cloneAsset(key,height=1){const src=assets[key];if(!src)return null;const model=prep(SkeletonUtils.clone(src.scene));const box=new THREE.Box3().setFromObject(model);const h=Math.max(.001,box.max.y-box.min.y);model.scale.setScalar(height/h);const b2=new THREE.Box3().setFromObject(model);model.position.y-=b2.min.y;const holder=new THREE.Group();holder.add(model);holder.userData.model=model;return holder}
function assetClip(key,patterns){const a=assets[key]?.animations||[];for(const p of patterns){const f=a.find(c=>p.test(c.name));if(f)return f}return a[0]||null}
function animateModel(holder,key,mode='idle'){if(!holder?.userData?.model||!assets[key])return null;const mixer=new THREE.AnimationMixer(holder.userData.model);const idle=assetClip(key,[/idle/i,/breathing/i]);const walk=assetClip(key,[/walk/i,/run/i]);const attack=assetClip(key,[/shoot/i,/ranged/i,/attack/i,/slash/i]);const death=assetClip(key,[/death/i,/defeat/i,/die/i]);const ctrl={mixer,idle:idle?mixer.clipAction(idle):null,walk:walk?mixer.clipAction(walk):null,attack:attack?mixer.clipAction(attack):null,death:death?mixer.clipAction(death):null,current:null};const start=mode==='walk'?(ctrl.walk||ctrl.idle):(ctrl.idle||ctrl.walk);if(start){start.play();ctrl.current=start}state.mixers.push(mixer);return ctrl}
function oneShot(ctrl,action){if(!ctrl||!action)return;if(ctrl.current&&ctrl.current!==action)ctrl.current.fadeOut(.08);action.reset();action.setLoop(THREE.LoopOnce,1);action.clampWhenFinished=true;action.fadeIn(.05).play();const restore=()=>{ctrl.mixer.removeEventListener('finished',restore);if(ctrl.idle&&action!==ctrl.death){action.fadeOut(.08);ctrl.idle.reset().fadeIn(.08).play();ctrl.current=ctrl.idle}};ctrl.mixer.addEventListener('finished',restore)}

async function loadAssets(){loader=new GLTFLoader();const entries=Object.entries(URLS),total=entries.length;let done=0;for(const [key,url] of entries){setProgress(done,total,`Loading ${key.replace('_',' ')}…`);try{assets[key]=await loader.loadAsync(url)}catch(e){console.warn('Asset failed',key,e);assets[key]=null}done++;setProgress(done,total,`Loaded ${done} / ${total} scene assets`)}if(!assets.enemy||!assets.archer||!assets.pillar||!assets.wall)throw new Error('Core animated character or fortress assets could not be loaded.');}

function ribbon(curve,width,material,y=.02,segments=150){const pos=[],uv=[],idx=[];for(let i=0;i<=segments;i++){const t=i/segments,p=curve.getPointAt(t),tan=curve.getTangentAt(t).normalize(),n=new THREE.Vector3(-tan.z,0,tan.x).normalize();for(const s of [-1,1]){pos.push(p.x+n.x*width*.5,y,p.z+n.z*width*.5);uv.push(t,s<0?0:1)}if(i<segments){const a=i*2,b=a+1,c=a+2,d=a+3;idx.push(a,c,b,c,d,b)}}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));g.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));g.setIndex(idx);g.computeVertexNormals();return new THREE.Mesh(g,material)}
function distanceToRoad(x,z){let best=999;for(const p of roadSamples)best=Math.min(best,Math.hypot(x-p.x,z-p.z));return best}
function placeModel(key,x,z,height,rot=0,parent=scene){const m=cloneAsset(key,height);if(!m)return null;m.position.set(x,0,z);m.rotation.y=rot;parent.add(m);return m}
function flag(x,y,z,rot=0,parent=scene,scale=1){const pole=new THREE.Mesh(new THREE.CylinderGeometry(.025,.035,2.1,8),new THREE.MeshStandardMaterial({color:0x4a3525,roughness:.8}));pole.position.set(x,y+1,z);pole.castShadow=true;parent.add(pole);const f=new THREE.Mesh(new THREE.PlaneGeometry(1.12,.7),new THREE.MeshStandardMaterial({map:makeFlagTexture(),side:THREE.DoubleSide,roughness:.75}));f.position.set(x+.56*Math.cos(rot),y+1.7,z-.56*Math.sin(rot));f.rotation.y=rot;f.scale.setScalar(scale);f.castShadow=true;parent.add(f);return f}
function simpleHouse(x,z,s=1,rot=0){const g=new THREE.Group();const stone=new THREE.MeshStandardMaterial({color:0xc7b28d,roughness:.92});const plaster=new THREE.MeshStandardMaterial({color:0xd9d0b8,roughness:.92});const roofMat=new THREE.MeshStandardMaterial({color:0x8e4730,roughness:.84});const body=new THREE.Mesh(new THREE.BoxGeometry(1.8*s,1.2*s,1.45*s),Math.random()>.5?stone:plaster);body.position.y=.6*s;body.castShadow=body.receiveShadow=true;g.add(body);const roof=new THREE.Mesh(new THREE.ConeGeometry(1.5*s,.85*s,4),roofMat);roof.position.y=1.55*s;roof.rotation.y=Math.PI/4;roof.castShadow=true;g.add(roof);const door=new THREE.Mesh(new THREE.BoxGeometry(.38*s,.65*s,.06*s),new THREE.MeshStandardMaterial({color:0x513725,roughness:.95}));door.position.set(0,.33*s,.755*s);g.add(door);g.position.set(x,0,z);g.rotation.y=rot;scene.add(g);return g}
function buildWorld(){const groundTex=makeGroundTexture();groundTex.repeat.set(5,3);const groundMat=new THREE.MeshStandardMaterial({map:groundTex,color:0xb8c39e,roughness:.96});groundPlane=new THREE.Mesh(new THREE.PlaneGeometry(29,18),groundMat);groundPlane.rotation.x=-Math.PI/2;groundPlane.position.set(0,-.07,0);groundPlane.receiveShadow=true;scene.add(groundPlane);
 waterTexture=makeWaterTexture();waterTexture.repeat.set(2.4,5);const water=new THREE.Mesh(new THREE.PlaneGeometry(6.2,18),new THREE.MeshPhysicalMaterial({map:waterTexture,color:0x5791a0,roughness:.28,metalness:.05,clearcoat:.55,clearcoatRoughness:.22}));water.rotation.x=-Math.PI/2;water.position.set(-11.8,-.025,0);water.receiveShadow=true;scene.add(water);
 roadCurve=new THREE.CatmullRomCurve3([new THREE.Vector3(-13,0,3.2),new THREE.Vector3(-9.7,0,3.05),new THREE.Vector3(-7.6,0,1.25),new THREE.Vector3(-5.1,0,2.4),new THREE.Vector3(-2.7,0,.45),new THREE.Vector3(-.4,0,1.5),new THREE.Vector3(2.2,0,-.5),new THREE.Vector3(4.9,0,.25),new THREE.Vector3(7.1,0,-2.2),new THREE.Vector3(10.7,0,-2.1),new THREE.Vector3(13,0,-2.1)],false,'catmullrom',.22);pathLength=roadCurve.getLength();roadSamples=Array.from({length:151},(_,i)=>roadCurve.getPointAt(i/150));const borderMat=new THREE.MeshStandardMaterial({color:0x554938,roughness:1});const roadTex=makeRoadTexture();roadTex.repeat.set(13,1.6);const roadMat=new THREE.MeshStandardMaterial({map:roadTex,color:0xe6cf9b,roughness:.98});const edge=ribbon(roadCurve,2.55,borderMat,.005);edge.receiveShadow=true;scene.add(edge);const road=ribbon(roadCurve,2.14,roadMat,.025);road.receiveShadow=true;scene.add(road);
 // coastal quay
 const quayMat=new THREE.MeshStandardMaterial({color:0xb5a382,roughness:.95});const quay=new THREE.Mesh(new THREE.BoxGeometry(.7,.5,18),quayMat);quay.position.set(-8.9,.18,0);quay.castShadow=quay.receiveShadow=true;scene.add(quay);
 // fortress wall and gate
 const wallGroup=new THREE.Group();scene.add(wallGroup);for(const z of [-6.2,-4.9,-.2,1.1,2.4,3.7,5.0,6.3])placeModel('wall',10.9,z,2.3,Math.PI/2,wallGroup);for(const z of [-3.6,-2.0]){const p=placeModel('pillar',10.65,z,4.15,0,wallGroup);if(p)flag(0,2.6,0,0,p,.72)}const archMat=new THREE.MeshStandardMaterial({color:0x79664e,roughness:.93});const gateTop=new THREE.Mesh(new THREE.BoxGeometry(.8,1.0,2.7),archMat);gateTop.position.set(10.85,2.75,-2.8);gateTop.castShadow=true;scene.add(gateTop);
 // houses behind wall and near harbour
 simpleHouse(12.8,-5.2,1.05,.2);simpleHouse(13.1,1.4,.9,-.25);simpleHouse(8.9,4.8,.72,.4);simpleHouse(7.2,5.6,.6,-.2);simpleHouse(-6.7,-5.2,.65,.1);simpleHouse(-4.8,-5.9,.55,-.4);
 // scenery, deterministic placement
 const spots=[[-7.3,-3.5,3.2],[-5.7,-2.9,2.8],[-3.8,-4.7,3.4],[-1.9,-4.2,3.0],[.5,-4.8,3.7],[2.7,-4.8,3.1],[4.6,-4.1,2.9],[6.7,-5.3,3.4],[8.7,-5.3,2.8],[-7.2,5.5,2.7],[-4.9,5.3,3.3],[-2.2,5.7,2.9],[.5,5.3,3.5],[3.0,5.9,3.0],[5.8,5.3,3.5],[8.1,4.5,2.8]];for(const [x,z,h] of spots){if(distanceToRoad(x,z)<1.9)continue;placeModel('tree',x,z,h,(x+z)*.3)}const bushSpots=[[-7.7,-1.7],[-6.1,4.5],[-3.6,4.6],[-1,4.8],[1.2,-3.5],[3.5,3.8],[5.8,3.7],[7.8,2.6],[8.3,-4.1],[-4.8,-3.4]];for(const [x,z] of bushSpots)placeModel('bush',x,z,.7,(x-z));const rocks=[[-7.5,-5.6],[-6.2,-4.7],[-3.3,5.4],[1.5,5.5],[4.7,-4.7],[7.8,3.6]];for(const [x,z] of rocks)placeModel('rock',x,z,.8,(x*z));for(let i=0;i<7;i++){const c=placeModel('crate',-7.9+i*.45,-6.4+(i%2)*.55,.55,i*.3);if(c)c.rotation.y=i*.6}
 // harbour boats
 for(const [x,z,r] of [[-11.5,-4.2,.2],[-12.2,0.2,-.3],[-11.1,5.1,.15]]){const boat=new THREE.Group();const hull=new THREE.Mesh(new THREE.CapsuleGeometry(.32,1.55,4,8),new THREE.MeshStandardMaterial({color:0x513626,roughness:.85}));hull.rotation.z=Math.PI/2;hull.scale.z=.45;hull.castShadow=true;boat.add(hull);const mast=new THREE.Mesh(new THREE.CylinderGeometry(.025,.035,1.8,6),new THREE.MeshStandardMaterial({color:0x6c4b31}));mast.position.y=.8;boat.add(mast);const sail=new THREE.Mesh(new THREE.PlaneGeometry(.85,1.15),new THREE.MeshStandardMaterial({color:0x9b3c36,side:THREE.DoubleSide,roughness:.86}));sail.position.set(.25,1.05,0);sail.rotation.y=Math.PI/2;boat.add(sail);boat.position.set(x,.15,z);boat.rotation.y=r;scene.add(boat)}
 flag(9.85,2.1,-3.65,0,scene,.82);flag(9.85,2.1,-1.95,0,scene,.82);
 // subtle battlefield fire at gate
 const flame=new THREE.Sprite(new THREE.SpriteMaterial({map:glowTexture,color:0xff8b37,transparent:true,opacity:.62,depthWrite:false}));flame.position.set(10.2,1.0,-2.1);flame.scale.set(1.2,1.2,1.2);scene.add(flame);state.effects.push({kind:'pulse',obj:flame,base:1.0,phase:0});}

function towerBase(radius=.78){const g=new THREE.Group();const stone=new THREE.MeshStandardMaterial({color:0x8f8878,roughness:.94});const foot=new THREE.Mesh(new THREE.CylinderGeometry(radius,radius*1.08,.28,12),stone);foot.position.y=.14;foot.castShadow=foot.receiveShadow=true;g.add(foot);return g}
function buildBallistaModel(){const g=towerBase(.82);const wood=new THREE.MeshStandardMaterial({color:0x70472b,roughness:.83});const dark=new THREE.MeshStandardMaterial({color:0x33251e,roughness:.82,metalness:.08});const iron=new THREE.MeshStandardMaterial({color:0x55585a,roughness:.46,metalness:.65});const pivot=new THREE.Group();pivot.position.y=.48;g.add(pivot);for(const x of [-.42,.42]){const beam=new THREE.Mesh(new THREE.BoxGeometry(.18,.18,1.65),wood);beam.position.set(x,.2,0);beam.castShadow=true;pivot.add(beam)}const bed=new THREE.Mesh(new THREE.BoxGeometry(1.05,.18,1.55),dark);bed.position.y=.28;bed.castShadow=true;pivot.add(bed);for(const x of [-.68,.68])for(const z of [-.48,.48]){const w=new THREE.Mesh(new THREE.CylinderGeometry(.29,.29,.12,12),dark);w.rotation.z=Math.PI/2;w.position.set(x,.12,z);w.castShadow=true;pivot.add(w)}const arm=new THREE.Mesh(new THREE.BoxGeometry(2.2,.14,.16),wood);arm.position.set(0,.65,.32);arm.castShadow=true;pivot.add(arm);const bolt=new THREE.Mesh(new THREE.CylinderGeometry(.035,.055,2.2,7),iron);bolt.rotation.x=Math.PI/2;bolt.position.set(0,.75,.62);bolt.castShadow=true;pivot.add(bolt);const bowL=new THREE.Mesh(new THREE.BoxGeometry(1.08,.12,.12),wood);bowL.position.set(-.55,.67,.32);bowL.rotation.y=-.25;pivot.add(bowL);const bowR=bowL.clone();bowR.position.x=.55;bowR.rotation.y=.25;pivot.add(bowR);const points=[new THREE.Vector3(-1.05,.68,.52),new THREE.Vector3(0,.72,-.2),new THREE.Vector3(1.05,.68,.52)];const string=new THREE.Line(new THREE.BufferGeometry().setFromPoints(points),new THREE.LineBasicMaterial({color:0xd8c49d}));pivot.add(string);pivot.userData.restZ=0;g.userData.turret=pivot;g.userData.muzzle=new THREE.Vector3(0,1.25,1.35);return g}
function addPlatformTower(type){const g=towerBase(type==='watchtower'?.72:.86);const pillar=cloneAsset('pillar',type==='watchtower'?3.4:2.75);if(pillar){pillar.position.y=.2;g.add(pillar)}const platformY=type==='watchtower'?3.22:2.63;const wood=new THREE.MeshStandardMaterial({color:0x6f492f,roughness:.88});const platform=new THREE.Mesh(new THREE.CylinderGeometry(.82,.82,.18,8),wood);platform.position.y=platformY;platform.castShadow=platform.receiveShadow=true;g.add(platform);const battlement=new THREE.Mesh(new THREE.TorusGeometry(.67,.11,6,8),new THREE.MeshStandardMaterial({color:0xb5aa91,roughness:.94}));battlement.rotation.x=Math.PI/2;battlement.position.y=platformY+.13;g.add(battlement);const turret=new THREE.Group();turret.position.y=platformY+.13;const archer=cloneAsset('archer',1.05);let anim=null;if(archer){archer.rotation.y=Math.PI;turret.add(archer);anim=animateModel(archer,'archer','idle')}g.add(turret);flag(.52,platformY-.15,-.2,Math.PI/2,g,.48);g.userData.turret=turret;g.userData.archerAnim=anim;g.userData.muzzle=new THREE.Vector3(0,platformY+1.0,.55);return g}
function buildTower(type,ghost=false){let g=type==='ballista'?buildBallistaModel():addPlatformTower(type);if(ghost){g.traverse(o=>{if(o.isMesh&&o.material){o.material=o.material.clone();o.material.transparent=true;o.material.opacity=.45;o.material.depthWrite=false}})}return g}
function makeRangeRing(range,color=0x76e291){const geo=new THREE.RingGeometry(range-.035,range+.035,96);const mat=new THREE.MeshBasicMaterial({color,transparent:true,opacity:.72,side:THREE.DoubleSide,depthWrite:false});const m=new THREE.Mesh(geo,mat);m.rotation.x=-Math.PI/2;m.position.y=.06;return m}
function validPlacement(x,z){return x>-7.9&&x<9.3&&z>-6.8&&z<6.8&&distanceToRoad(x,z)>1.75&&state.towers.every(t=>Math.hypot(t.x-x,t.z-z)>1.8)}
function placeTower(type,x,z){const d=DEF[type];if(state.gold<d.cost)return;state.gold-=d.cost;const obj=buildTower(type,false);obj.position.set(x,0,z);scene.add(obj);const ring=makeRangeRing(d.range,0xd8bd75);ring.visible=false;ring.position.set(x,.06,z);scene.add(ring);const t={type,x,z,obj,ring,range:d.range,damage:d.damage,rate:d.rate,cd:Math.random()*.3,turret:obj.userData.turret,anim:obj.userData.archerAnim,muzzleLocal:obj.userData.muzzle,recoil:0};state.towers.push(t);obj.traverse(o=>{if(o.isMesh)o.userData.tower=t});flash(new THREE.Vector3(x,.4,z),0xeacb7c,1.4);selectTower(t);updateUI()}
function selectTower(t){state.selected=t;state.towers.forEach(x=>x.ring.visible=x===t);if(!t){ui.info.classList.add('hidden');return}ui.infoName.textContent=DEF[t.type].name;ui.infoStats.textContent=`Damage ${t.damage} · Range ${t.range.toFixed(1)} · Fire rate ${t.rate.toFixed(2)}/s`;ui.info.classList.remove('hidden')}

function eventPoint(ev){const r=renderer.domElement.getBoundingClientRect();pointer.x=((ev.clientX-r.left)/r.width)*2-1;pointer.y=-((ev.clientY-r.top)/r.height)*2+1;raycaster.setFromCamera(pointer,camera);const p=new THREE.Vector3();return raycaster.ray.intersectPlane(new THREE.Plane(new THREE.Vector3(0,1,0),0),p)?p:null}
function beginDrag(ev,type){if(state.ended||state.gold<DEF[type].cost){setMessage('Not enough Gold for that defence.');return}ev.preventDefault();const p=eventPoint(ev)||new THREE.Vector3();const ghost=buildTower(type,true);scene.add(ghost);const ring=makeRangeRing(DEF[type].range,0x75e08e);scene.add(ring);state.drag={type,ghost,ring};moveDrag(ev);window.addEventListener('pointermove',moveDrag,{passive:false});window.addEventListener('pointerup',endDrag,{once:true})}
function moveDrag(ev){if(!state.drag)return;ev.preventDefault();const p=eventPoint(ev);if(!p)return;const ok=validPlacement(p.x,p.z);state.drag.ghost.position.set(p.x,0,p.z);state.drag.ring.position.set(p.x,.06,p.z);state.drag.ring.material.color.setHex(ok?0x72e38d:0xef655c);state.drag.ghost.traverse(o=>{if(o.isMesh&&o.material)o.material.opacity=ok?.5:.22})}
function endDrag(ev){window.removeEventListener('pointermove',moveDrag);if(!state.drag)return;const p=eventPoint(ev),d=state.drag;scene.remove(d.ghost,d.ring);d.ghost.traverse(o=>{if(o.geometry&&!o.userData.shared)o.geometry.dispose?.()});state.drag=null;if(p&&validPlacement(p.x,p.z))placeTower(d.type,p.x,p.z);else setMessage('Place defences on open ground away from the road.')}

function makeHealthBar(){const g=new THREE.Group();const back=new THREE.Mesh(new THREE.PlaneGeometry(.82,.085),new THREE.MeshBasicMaterial({color:0x1b1b18,depthTest:false}));const fill=new THREE.Mesh(new THREE.PlaneGeometry(.78,.055),new THREE.MeshBasicMaterial({color:0x67d66f,depthTest:false}));fill.position.z=.001;g.add(back,fill);g.userData.fill=fill;return g}
function spawnEnemy(){const holder=cloneAsset('enemy',1.22);if(!holder)return;const anim=animateModel(holder,'enemy','walk');const bar=makeHealthBar();bar.position.y=1.55;holder.add(bar);const p=roadCurve.getPointAt(0);holder.position.set(p.x,0,p.z);scene.add(holder);const hp=84+state.wave*18;state.enemies.push({obj:holder,anim,bar,hp,maxHp:hp,t:0,speed:1.08+state.wave*.018,dead:false,removeIn:0})}
function damageEnemy(e,amount){if(e.dead)return;e.hp-=amount;e.bar.userData.fill.scale.x=Math.max(.01,e.hp/e.maxHp);e.bar.userData.fill.position.x=-(.78*(1-e.hp/e.maxHp))/2;if(e.hp<=0){e.dead=true;state.gold+=9+state.wave;updateUI();if(e.anim?.death)oneShot(e.anim,e.anim.death);e.removeIn=.7;flash(e.obj.position.clone().add(new THREE.Vector3(0,.7,0)),0xffa04f,1.1)}}
function removeEnemy(e){scene.remove(e.obj);const i=state.enemies.indexOf(e);if(i>=0)state.enemies.splice(i,1)}
function startWave(){if(state.active||state.ended)return;if(state.wave>=state.maxWaves){win();return}state.wave++;state.active=true;state.spawnLeft=8+state.wave*2;state.spawnClock=.05;ui.start.disabled=true;setMessage(`Wave ${state.wave}: enemy formations approaching.`);updateUI()}
function breach(e){state.lives--;removeEnemy(e);flash(new THREE.Vector3(10.4,.7,-2.1),0xf15d43,1.6);if(state.lives<=0){state.lives=0;state.ended=true;state.active=false;setMessage('The gate has fallen.');ui.resultTitle.textContent='DEFEAT';ui.resultText.textContent='The assault breached Constantinople. Rebuild the defence and try again.';setTimeout(()=>ui.result.classList.remove('hidden'),700)}updateUI()}
function maybeWaveComplete(){if(!state.active||state.spawnLeft>0||state.enemies.some(e=>!e.dead))return;state.active=false;state.gold+=70+state.wave*9;updateUI();if(state.wave>=state.maxWaves){win()}else{ui.start.disabled=false;setMessage(`Wave ${state.wave} repelled. Reinforce the line.`)}}
function win(){if(state.ended)return;state.ended=true;state.active=false;setMessage('Constantinople holds.');ui.resultTitle.textContent='VICTORY';ui.resultText.textContent='The city holds through all twelve waves.';setTimeout(()=>ui.result.classList.remove('hidden'),700)}

function worldMuzzle(t){const p=t.muzzleLocal.clone();return t.obj.localToWorld(p)}
function fire(t,target){if(!target||target.dead)return;const start=worldMuzzle(t),end=target.obj.position.clone().add(new THREE.Vector3(0,.72,0)),dir=end.clone().sub(start);if(t.turret){const localTarget=t.obj.worldToLocal(target.obj.position.clone());t.turret.rotation.y=Math.atan2(localTarget.x,localTarget.z)}if(t.anim?.attack)oneShot(t.anim,t.anim.attack);if(t.type==='ballista')t.recoil=1;const heavy=t.type==='ballista',len=heavy?1.15:.68;const geo=new THREE.CylinderGeometry(heavy?.055:.025,heavy?.065:.03,len,6);const mat=new THREE.MeshStandardMaterial({color:heavy?0xc9b088:0xedd6a0,emissive:heavy?0x3c210e:0x1d1508,emissiveIntensity:.8,roughness:.42,metalness:heavy?.3:.05});const mesh=new THREE.Mesh(geo,mat);mesh.castShadow=true;mesh.position.copy(start);mesh.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),dir.clone().normalize());scene.add(mesh);state.projectiles.push({mesh,start:start.clone(),target,end:end.clone(),enemy:target,t:0,duration:heavy?.23:.15,damage:t.damage,type:t.type});muzzleFlash(start,t.type==='ballista'?0xff9b45:0xffdf8a)}
function muzzleFlash(pos,color){const s=new THREE.Sprite(new THREE.SpriteMaterial({map:glowTexture,color,transparent:true,opacity:.95,depthWrite:false,blending:THREE.AdditiveBlending}));s.position.copy(pos);s.scale.set(.45,.45,.45);scene.add(s);state.effects.push({kind:'flash',obj:s,life:.16,age:0})}
function flash(pos,color=0xffa04d,size=1){const s=new THREE.Sprite(new THREE.SpriteMaterial({map:glowTexture,color,transparent:true,opacity:.8,depthWrite:false,blending:THREE.AdditiveBlending}));s.position.copy(pos);s.scale.set(.3,.3,.3);scene.add(s);state.effects.push({kind:'burst',obj:s,life:.38,age:0,size});for(let i=0;i<5;i++){const spark=new THREE.Mesh(new THREE.SphereGeometry(.025,5,4),new THREE.MeshBasicMaterial({color}));spark.position.copy(pos);scene.add(spark);state.effects.push({kind:'spark',obj:spark,life:.36,age:0,vel:new THREE.Vector3((Math.random()-.5)*2.6,1.2+Math.random()*1.8,(Math.random()-.5)*2.6)})}}

function updateEnemies(dt){if(state.active&&state.spawnLeft>0){state.spawnClock-=dt*state.speed;if(state.spawnClock<=0){spawnEnemy();state.spawnLeft--;state.spawnClock=.78}}for(const e of [...state.enemies]){if(e.dead){e.removeIn-=dt*state.speed;if(e.removeIn<=0)removeEnemy(e);continue}e.anim?.mixer?.update(dt*state.speed);e.t+=dt*state.speed*e.speed/pathLength;const t=Math.min(e.t,1),p=roadCurve.getPointAt(t),tan=roadCurve.getTangentAt(Math.min(.999,t));e.obj.position.set(p.x,0,p.z);e.obj.rotation.y=Math.atan2(tan.x,tan.z);e.bar.quaternion.copy(camera.quaternion);if(e.t>=1)breach(e)}maybeWaveComplete()}
function updateTowers(dt){for(const t of state.towers){t.cd-=dt*state.speed;if(t.recoil>0){t.recoil=Math.max(0,t.recoil-dt*state.speed*5);if(t.turret)t.turret.position.z=-.22*t.recoil}let target=null,best=Infinity;for(const e of state.enemies){if(e.dead)continue;const d=Math.hypot(e.obj.position.x-t.x,e.obj.position.z-t.z);if(d<t.range&&d<best){best=d;target=e}}if(target&&t.turret){const local=t.obj.worldToLocal(target.obj.position.clone());t.turret.rotation.y=Math.atan2(local.x,local.z)}if(target&&t.cd<=0){fire(t,target);t.cd=1/t.rate}}}
function updateProjectiles(dt){for(let i=state.projectiles.length-1;i>=0;i--){const p=state.projectiles[i];p.t+=dt*state.speed/p.duration;const q=Math.min(1,p.t),ease=1-Math.pow(1-q,2);p.mesh.position.lerpVectors(p.start,p.target,ease);if(p.t>=1){if(p.enemy&&!p.enemy.dead)damageEnemy(p.enemy,p.damage);flash(p.target,p.type==='ballista'?0xff8738:0xffd27c,p.type==='ballista'?1.0:.62);scene.remove(p.mesh);p.mesh.geometry.dispose();p.mesh.material.dispose();state.projectiles.splice(i,1)}}}
function updateEffects(dt){for(let i=state.effects.length-1;i>=0;i--){const e=state.effects[i];if(e.kind==='pulse'){e.phase+=dt;const s=e.base*(.9+Math.sin(e.phase*6)*.12);e.obj.scale.setScalar(s);continue}e.age+=dt*state.speed;if(e.kind==='spark'){e.vel.y-=4.5*dt*state.speed;e.obj.position.addScaledVector(e.vel,dt*state.speed);e.obj.material.opacity=Math.max(0,1-e.age/e.life);e.obj.material.transparent=true}else{const q=Math.min(1,e.age/e.life);const size=(e.size||1)*(e.kind==='flash'?(.35+q*.9):(.3+q*1.6));e.obj.scale.setScalar(size);e.obj.material.opacity=(1-q)*(e.kind==='flash'?.95:.78)}if(e.age>=e.life){scene.remove(e.obj);e.obj.material?.dispose?.();e.obj.geometry?.dispose?.();state.effects.splice(i,1)}}}
function updateWater(dt){if(waterTexture){waterTexture.offset.x+=dt*.008;waterTexture.offset.y-=dt*.014}}
function animate(){requestAnimationFrame(animate);const dt=Math.min(.04,clock.getDelta());state.time+=dt;updateWater(dt);updateEnemies(dt);updateTowers(dt);updateProjectiles(dt);updateEffects(dt);renderer.render(scene,camera)}

function setupInput(){document.querySelectorAll('.tower-card').forEach(b=>b.addEventListener('pointerdown',e=>beginDrag(e,b.dataset.tower)));ui.start.addEventListener('click',startWave);ui.speed.addEventListener('click',()=>{state.speed=state.speed===1?2:1;ui.speed.textContent=`×${state.speed}`;setMessage(state.speed===2?'Battle speed doubled.':'Battle speed normal.')});ui.closeInfo.addEventListener('click',()=>selectTower(null));ui.replay.addEventListener('click',()=>location.reload());renderer.domElement.addEventListener('pointerdown',ev=>{if(state.drag)return;const r=renderer.domElement.getBoundingClientRect();pointer.x=((ev.clientX-r.left)/r.width)*2-1;pointer.y=-((ev.clientY-r.top)/r.height)*2+1;raycaster.setFromCamera(pointer,camera);const hits=raycaster.intersectObjects(state.towers.flatMap(t=>{const a=[];t.obj.traverse(o=>{if(o.isMesh)a.push(o)});return a}),true);if(hits.length&&hits[0].object.userData.tower)selectTower(hits[0].object.userData.tower);else selectTower(null)})}

async function init(){try{makeScene();setProgress(0,8,'Loading animated combat units…');await loadAssets();setProgress(8,8,'Building Constantinople…');buildWorld();setupInput();updateUI();ui.loading.classList.add('hidden');ui.hud.classList.remove('hidden');ui.message.classList.remove('hidden');ui.arsenal.classList.remove('hidden');ui.start.classList.remove('hidden');setMessage('Drag a defence onto open ground. Animated enemy formations will follow the stone road.');clock.start();animate()}catch(e){fatal(e?.message||String(e))}}
init();
