(()=>{
'use strict';
const canvas=document.getElementById('game'),ctx=canvas.getContext('2d');
const mapCanvas=document.getElementById('map'),mctx=mapCanvas.getContext('2d');
const ui={cash:document.getElementById('cash'),speed:document.getElementById('speed'),wanted:document.getElementById('wanted'),objective:document.getElementById('objective'),toast:document.getElementById('toast')};
const DPR=Math.min(devicePixelRatio||1,2);let vw=innerWidth,vh=innerHeight,last=performance.now();
function resize(){vw=innerWidth;vh=innerHeight;canvas.width=vw*DPR;canvas.height=vh*DPR;canvas.style.width=vw+'px';canvas.style.height=vh+'px';ctx.setTransform(DPR,0,0,DPR,0,0);mapCanvas.width=300;mapCanvas.height=224}
addEventListener('resize',resize);resize();
const W=3200,H=2400,ROAD=250;
const vRoads=[420,1120,1820,2520],hRoads=[380,1080,1780];
const blocks=[];for(let ix=0;ix<vRoads.length-1;ix++)for(let iy=0;iy<hRoads.length-1;iy++){const x=vRoads[ix]+ROAD/2+36,y=hRoads[iy]+ROAD/2+36,w=vRoads[ix+1]-vRoads[ix]-ROAD-72,h=hRoads[iy+1]-hRoads[iy]-ROAD-72;blocks.push({x,y,w,h,seed:ix*11+iy*17});}
blocks.push({x:35,y:35,w:260,h:250,seed:40},{x:2740,y:55,w:390,h:260,seed:41},{x:45,y:1980,w:300,h:340,seed:42},{x:2730,y:1990,w:410,h:320,seed:43});
const palette=['#966e54','#766b73','#7f745e','#6e7882','#9b8068','#657884','#806a58','#776f60'];
const controls={left:false,right:false,gas:false,brake:false};
const keys={};addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true;if(['arrowup','arrowdown','arrowleft','arrowright',' '].includes(e.key.toLowerCase()))e.preventDefault()});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
[['left','left'],['right','right'],['gas','gas'],['brake','brake']].forEach(([id,k])=>{const b=document.getElementById(id);const on=e=>{e.preventDefault();controls[k]=true;b.classList.add('active')},off=e=>{e.preventDefault();controls[k]=false;b.classList.remove('active')};b.addEventListener('pointerdown',on);b.addEventListener('pointerup',off);b.addEventListener('pointercancel',off);b.addEventListener('pointerleave',off)});
const player={x:760,y:960,a:-Math.PI/2,v:0,steer:0,w:34,h:66,cash:1250,wanted:0,heat:0,damage:0};
const camera={x:player.x,y:player.y,shake:0,zoom:1};
const mission={x:2370,y:1550,phase:0,stage:0};
const skid=[];
const traffic=[];
const carColors=['#c3453f','#d6b54d','#447aa9','#6f8d4e','#8d5e8b','#d7d2c8','#3c6267','#9a7b4f'];
function routeCar(horizontal,lane,pos,dir,color,i){traffic.push({horizontal,lane,pos,dir,speed:70+((i*31)%55),color,a:horizontal?(dir>0?0:Math.PI):(dir>0?Math.PI/2:-Math.PI/2),blink:Math.random()*10})}
for(let i=0;i<18;i++){if(i%2){const y=hRoads[(i>>1)%hRoads.length]+(i%4<2?-44:44);routeCar(true,y,(i*173)%W,i%3?1:-1,carColors[i%carColors.length],i)}else{const x=vRoads[(i>>1)%vRoads.length]+(i%4<2?-44:44);routeCar(false,x,(i*149)%H,i%3?1:-1,carColors[i%carColors.length],i)}}
const police=[];function spawnPolice(){if(police.length>=Math.min(4,player.wanted+1))return;const angle=Math.random()*Math.PI*2,d=650;police.push({x:player.x+Math.cos(angle)*d,y:player.y+Math.sin(angle)*d,a:angle+Math.PI,v:100,flash:0})}
const peds=[];const pedColors=['#d9b27c','#8aa6c4','#c27569','#84a06d','#d1c2a8','#8d79aa'];
function nearestSidewalkPoint(seed){const r=seed%7;if(r<4){const x=vRoads[r%vRoads.length]+(seed%2?155:-155);return{x,y:120+(seed*113)%(H-240),axis:'y',dir:seed%3?1:-1}}const y=hRoads[r%hRoads.length]+(seed%2?155:-155);return{x:100+(seed*181)%(W-200),y,axis:'x',dir:seed%3?1:-1}}
for(let i=0;i<42;i++){const p=nearestSidewalkPoint(i*7+3);peds.push({...p,speed:24+(i*9)%22,color:pedColors[i%pedColors.length],step:i*.7})}
const trees=[];for(let b=0;b<blocks.length;b++){const q=blocks[b];for(let i=0;i<4;i++){trees.push({x:q.x+35+(i*131+q.seed*17)%Math.max(70,q.w-70),y:q.y+28+(i*97+q.seed*29)%Math.max(70,q.h-60),r:16+(i%3)*3})}}
function onRoad(x,y){return vRoads.some(v=>Math.abs(x-v)<ROAD/2)||hRoads.some(h=>Math.abs(y-h)<ROAD/2)}
function buildingCollision(x,y){for(const b of blocks){const inset=20;if(x>b.x+inset&&x<b.x+b.w-inset&&y>b.y+inset&&y<b.y+b.h-inset)return true}return false}
function update(dt){
 const gas=controls.gas||keys['arrowup']||keys['w'],brake=controls.brake||keys['arrowdown']||keys['s'],left=controls.left||keys['arrowleft']||keys['a'],right=controls.right||keys['arrowright']||keys['d'];
 const road=onRoad(player.x,player.y);const accel=road?270:150,max=road?285:150;
 if(gas)player.v+=accel*dt;if(brake)player.v-=340*dt;if(!gas&&!brake)player.v*=Math.pow(road ? .986 : .972,dt*60);player.v=Math.max(-110,Math.min(max,player.v));
 const turn=(right?1:0)-(left?1:0);player.steer+=(turn-player.steer)*Math.min(1,dt*9);const turnGrip=Math.min(1,Math.abs(player.v)/75);player.a+=player.steer*2.15*turnGrip*dt*(player.v>=0?1:-1);
 const ox=player.x,oy=player.y;player.x+=Math.cos(player.a)*player.v*dt;player.y+=Math.sin(player.a)*player.v*dt;
 player.x=Math.max(24,Math.min(W-24,player.x));player.y=Math.max(24,Math.min(H-24,player.y));
 if(buildingCollision(player.x,player.y)){player.x=ox;player.y=oy;player.v*=-.24;player.damage=Math.min(1,player.damage+.08);camera.shake=7;addHeat(.35);showToast('CRUNCH')}
 if(Math.abs(player.steer)>.55&&Math.abs(player.v)>170){const side=12;skid.push({x:player.x+Math.cos(player.a+Math.PI/2)*side,y:player.y+Math.sin(player.a+Math.PI/2)*side,life:1});if(skid.length>200)skid.shift()}
 skid.forEach(s=>s.life-=dt*.2);
 traffic.forEach(c=>{c.pos+=c.speed*c.dir*dt;if(c.horizontal){if(c.pos<-100)c.pos=W+100;if(c.pos>W+100)c.pos=-100;c.x=c.pos;c.y=c.lane}else{if(c.pos<-100)c.pos=H+100;if(c.pos>H+100)c.pos=-100;c.x=c.lane;c.y=c.pos}if(Math.hypot(player.x-c.x,player.y-c.y)<45){player.v*=.72;c.speed*=.97;camera.shake=5;addHeat(.12)}});
 peds.forEach(p=>{p.step+=dt*p.speed*.12;if(p.axis==='x'){p.x+=p.speed*p.dir*dt;if(p.x<70||p.x>W-70)p.dir*=-1}else{p.y+=p.speed*p.dir*dt;if(p.y<70||p.y>H-70)p.dir*=-1}const d=Math.hypot(player.x-p.x,player.y-p.y);if(d<28&&Math.abs(player.v)>60){p.dir*=-1;p.speed=58;player.v*=.86;addHeat(.65);camera.shake=6}});
 mission.phase+=dt;if(Math.hypot(player.x-mission.x,player.y-mission.y)<78){mission.stage++;player.cash+=500;showToast('JOB COMPLETE  +$500');if(mission.stage%3===1){mission.x=620;mission.y=2070}else if(mission.stage%3===2){mission.x=2780;mission.y=570}else{mission.x=2370;mission.y=1550}ui.objective.innerHTML='<b>JOB</b><span>New pickup marked on the map.</span>'}
 if(player.heat>0)player.heat=Math.max(0,player.heat-dt*.055);const newWanted=Math.min(5,Math.floor(player.heat));if(newWanted!==player.wanted){player.wanted=newWanted;if(newWanted>0)showToast('POLICE ALERT');}
 if(player.wanted>0&&Math.random()<dt*(.5+player.wanted*.18))spawnPolice();
 for(let i=police.length-1;i>=0;i--){const p=police[i];p.flash+=dt*9;const ang=Math.atan2(player.y-p.y,player.x-p.x);let da=((ang-p.a+Math.PI*3)%(Math.PI*2))-Math.PI;p.a+=Math.max(-1.8*dt,Math.min(1.8*dt,da));p.v+=(170+player.wanted*22-p.v)*dt*.8;p.x+=Math.cos(p.a)*p.v*dt;p.y+=Math.sin(p.a)*p.v*dt;if(Math.hypot(player.x-p.x,player.y-p.y)<42){player.v*=.82;camera.shake=5}if(player.wanted===0||Math.hypot(player.x-p.x,player.y-p.y)>1400)police.splice(i,1)}
 camera.x+=(player.x-camera.x)*Math.min(1,dt*5.5);camera.y+=(player.y-camera.y)*Math.min(1,dt*5.5);camera.zoom+=(1+Math.min(.13,Math.abs(player.v)/2200)-camera.zoom)*dt*3;camera.shake=Math.max(0,camera.shake-dt*20);
 ui.cash.textContent='$'+player.cash.toLocaleString();ui.speed.textContent=Math.round(Math.abs(player.v)*.72);ui.wanted.textContent='★'.repeat(player.wanted)+'☆'.repeat(5-player.wanted);
}
function addHeat(v){player.heat=Math.min(5.8,player.heat+v)}
let toastTimer=0;function showToast(t){ui.toast.textContent=t;ui.toast.classList.add('show');toastTimer=1.4}
function roundRect(c,x,y,w,h,r){c.beginPath();if(c.roundRect)c.roundRect(x,y,w,h,r);else c.rect(x,y,w,h)}
function drawRoads(){ctx.fillStyle='#2c3438';ctx.fillRect(0,0,W,H);ctx.fillStyle='#242a2d';vRoads.forEach(x=>ctx.fillRect(x-ROAD/2,0,ROAD,H));hRoads.forEach(y=>ctx.fillRect(0,y-ROAD/2,W,ROAD));
 ctx.strokeStyle='#8a8170';ctx.lineWidth=4;ctx.setLineDash([30,26]);vRoads.forEach(x=>{ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()});hRoads.forEach(y=>{ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()});ctx.setLineDash([]);
 ctx.strokeStyle='#d5caa8';ctx.lineWidth=3;vRoads.forEach(x=>[-76,76].forEach(o=>{ctx.beginPath();ctx.moveTo(x+o,0);ctx.lineTo(x+o,H);ctx.stroke()}));hRoads.forEach(y=>[-76,76].forEach(o=>{ctx.beginPath();ctx.moveTo(0,y+o);ctx.lineTo(W,y+o);ctx.stroke()}));
 ctx.fillStyle='#bbb4a3';vRoads.forEach(x=>hRoads.forEach(y=>{for(let i=-4;i<=4;i++){ctx.fillRect(x-100+i*24,y-112,13,44);ctx.fillRect(x-100+i*24,y+68,13,44);ctx.fillRect(x-112,y-100+i*24,44,13);ctx.fillRect(x+68,y-100+i*24,44,13)}}));
 for(let x=120;x<W;x+=310){ctx.fillStyle='#171c1e';ctx.beginPath();ctx.arc(x,380,10,0,Math.PI*2);ctx.fill()} }
function drawBlocks(){blocks.forEach((b,i)=>{ctx.fillStyle='#a7a49a';ctx.fillRect(b.x-24,b.y-24,b.w+48,b.h+48);ctx.fillStyle='#73736e';ctx.fillRect(b.x-18,b.y-18,b.w+36,b.h+36);ctx.save();ctx.translate(12,14);drawBuilding(b,i,true);ctx.restore();drawBuilding(b,i,false)})}
function drawBuilding(b,i,shadow){const color=shadow?'#0005':palette[i%palette.length];ctx.fillStyle=color;roundRect(ctx,b.x,b.y,b.w,b.h,10);ctx.fill();if(shadow)return;ctx.fillStyle='rgba(255,255,255,.08)';ctx.fillRect(b.x+12,b.y+12,b.w-24,10);ctx.fillStyle='rgba(0,0,0,.16)';ctx.fillRect(b.x+12,b.y+b.h-24,b.w-24,12);const roof='#bbb6a7';ctx.fillStyle=roof;for(let k=0;k<3;k++){const rx=b.x+34+(k*97+b.seed*13)%Math.max(60,b.w-90),ry=b.y+30+(k*73+b.seed*9)%Math.max(60,b.h-90);ctx.fillRect(rx,ry,36,24);ctx.fillStyle='#686c6d';ctx.fillRect(rx+5,ry+4,26,16);ctx.fillStyle=roof}ctx.fillStyle='#82939a';for(let k=0;k<4;k++){const sx=b.x+28+(k*89+b.seed*7)%Math.max(50,b.w-70),sy=b.y+24+(k*61+b.seed*3)%Math.max(50,b.h-70);ctx.fillRect(sx,sy,22,14);ctx.fillStyle='#a8d0d6';ctx.fillRect(sx+3,sy+3,16,8);ctx.fillStyle='#82939a'}ctx.strokeStyle='#4d4d48';ctx.lineWidth=2;ctx.strokeRect(b.x+8,b.y+8,b.w-16,b.h-16)}
function drawTrees(){trees.forEach(t=>{ctx.fillStyle='#0004';ctx.beginPath();ctx.ellipse(t.x+8,t.y+10,t.r*.95,t.r*.55,.3,0,Math.PI*2);ctx.fill();ctx.fillStyle='#594635';ctx.fillRect(t.x-3,t.y-3,6,16);ctx.fillStyle='#315f47';ctx.beginPath();ctx.arc(t.x,t.y-8,t.r,0,Math.PI*2);ctx.fill();ctx.fillStyle='#47775a';ctx.beginPath();ctx.arc(t.x-7,t.y-15,t.r*.55,0,Math.PI*2);ctx.fill();ctx.fillStyle='#274f3c';ctx.beginPath();ctx.arc(t.x+8,t.y-9,t.r*.62,0,Math.PI*2);ctx.fill()})}
function drawStreetProps(){ctx.fillStyle='#777d7f';for(const x of vRoads)for(let y=160;y<H;y+=330){ctx.fillRect(x-142,y,5,22);ctx.fillStyle='#d7d0a6';ctx.fillRect(x-147,y-3,15,5);ctx.fillStyle='#777d7f'}for(const y of hRoads)for(let x=180;x<W;x+=350){ctx.fillRect(x,y-142,5,22);ctx.fillStyle='#d7d0a6';ctx.fillRect(x-5,y-147,15,5);ctx.fillStyle='#777d7f'}ctx.fillStyle='#1d2427';for(let i=0;i<14;i++){const x=220+(i*223)%W,y=140+(i*397)%H;ctx.fillRect(x,y,20,30);ctx.fillStyle='#d2a947';ctx.fillRect(x+2,y+4,16,3);ctx.fillStyle='#1d2427'}}
function drawCar(c,policeCar=false,playerCar=false){ctx.save();ctx.translate(c.x,c.y);ctx.rotate(c.a);ctx.fillStyle='#0006';roundRect(ctx,-17,6,34,68,8);ctx.fill();ctx.translate(0,-4);ctx.fillStyle=policeCar?'#e8ecef':c.color||'#c9453f';roundRect(ctx,-17,-32,34,64,8);ctx.fill();ctx.fillStyle=playerCar?'#1b1f21':'#20272b';roundRect(ctx,-13,-18,26,27,5);ctx.fill();ctx.fillStyle='#7db0c1';ctx.fillRect(-11,-16,22,10);ctx.fillStyle='#94c5d1';ctx.fillRect(-11,1,22,6);ctx.fillStyle='#15191b';ctx.fillRect(-18,-22,3,13);ctx.fillRect(15,-22,3,13);ctx.fillRect(-18,10,3,13);ctx.fillRect(15,10,3,13);ctx.fillStyle='#ffe49a';ctx.fillRect(-11,-32,7,3);ctx.fillRect(4,-32,7,3);ctx.fillStyle='#c94a45';ctx.fillRect(-11,29,7,3);ctx.fillRect(4,29,7,3);if(policeCar){ctx.fillStyle=Math.sin(c.flash)>0?'#e34b4b':'#4b7fe3';ctx.fillRect(-11,-3,10,4);ctx.fillStyle=Math.sin(c.flash)>0?'#4b7fe3':'#e34b4b';ctx.fillRect(1,-3,10,4)}ctx.restore()}
function drawPeds(){peds.forEach(p=>{ctx.save();ctx.translate(p.x,p.y);const bob=Math.sin(p.step)*2;ctx.fillStyle='#0004';ctx.beginPath();ctx.ellipse(3,7,6,3,0,0,Math.PI*2);ctx.fill();ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(0,-3+bob,5,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#20262a';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-2,2+bob);ctx.lineTo(-4,8+bob);ctx.moveTo(2,2+bob);ctx.lineTo(4,8+bob);ctx.stroke();ctx.restore()})}
function drawMission(){const r=38+Math.sin(mission.phase*4)*8;ctx.strokeStyle='#ffd94d';ctx.lineWidth=6;ctx.globalAlpha=.85;ctx.beginPath();ctx.arc(mission.x,mission.y,r,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=.18;ctx.fillStyle='#ffd94d';ctx.beginPath();ctx.arc(mission.x,mission.y,r,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;ctx.fillStyle='#ffe577';ctx.font='700 18px system-ui';ctx.textAlign='center';ctx.fillText('JOB',mission.x,mission.y+6)}
function drawSkids(){ctx.strokeStyle='rgba(10,10,10,.32)';ctx.lineWidth=3;for(const s of skid){if(s.life<=0)continue;ctx.globalAlpha=Math.min(.35,s.life);ctx.beginPath();ctx.moveTo(s.x,s.y);ctx.lineTo(s.x-8*Math.cos(player.a),s.y-8*Math.sin(player.a));ctx.stroke()}ctx.globalAlpha=1}
function render(){const sx=(Math.random()-.5)*camera.shake,sy=(Math.random()-.5)*camera.shake;ctx.setTransform(DPR,0,0,DPR,0,0);ctx.fillStyle='#223039';ctx.fillRect(0,0,vw,vh);ctx.save();ctx.translate(vw/2+sx,vh/2+sy);ctx.scale(camera.zoom,camera.zoom);ctx.translate(-camera.x,-camera.y);drawRoads();drawBlocks();drawTrees();drawStreetProps();drawSkids();drawMission();drawPeds();traffic.forEach(c=>drawCar(c));police.forEach(c=>drawCar(c,true));drawCar({...player,color:'#cf4a41'},false,true);ctx.restore();
 const vignette=ctx.createRadialGradient(vw/2,vh/2,Math.min(vw,vh)*.2,vw/2,vh/2,Math.max(vw,vh)*.72);vignette.addColorStop(0,'rgba(0,0,0,0)');vignette.addColorStop(1,'rgba(0,0,0,.32)');ctx.fillStyle=vignette;ctx.fillRect(0,0,vw,vh);drawMiniMap()}
function drawMiniMap(){const mw=mapCanvas.width,mh=mapCanvas.height,sx=mw/W,sy=mh/H;mctx.fillStyle='#10171d';mctx.fillRect(0,0,mw,mh);mctx.fillStyle='#30383c';vRoads.forEach(x=>mctx.fillRect((x-ROAD/2)*sx,0,ROAD*sx,mh));hRoads.forEach(y=>mctx.fillRect(0,(y-ROAD/2)*sy,mw,ROAD*sy));mctx.fillStyle='#71726c';blocks.forEach(b=>mctx.fillRect(b.x*sx,b.y*sy,b.w*sx,b.h*sy));mctx.fillStyle='#ffd94d';mctx.beginPath();mctx.arc(mission.x*sx,mission.y*sy,5,0,Math.PI*2);mctx.fill();mctx.fillStyle='#ef5a4f';mctx.beginPath();mctx.arc(player.x*sx,player.y*sy,5,0,Math.PI*2);mctx.fill();if(player.wanted){mctx.fillStyle='#6da0ff';police.forEach(p=>{mctx.beginPath();mctx.arc(p.x*sx,p.y*sy,3,0,Math.PI*2);mctx.fill()})}}
function loop(now){const dt=Math.min(.035,(now-last)/1000);last=now;if(toastTimer>0){toastTimer-=dt;if(toastTimer<=0)ui.toast.classList.remove('show')}update(dt);render();requestAnimationFrame(loop)}
showToast('WASD / ARROWS OR TOUCH CONTROLS');requestAnimationFrame(loop);
})();