export const CAMPAIGN_VERSION=1;
export const ERA_MIN_TURNS=[18,24,30,36,42,0];
export const REGIONS=[
{id:'istanbul',name:'Constantinople',owner:'ottoman',neighbors:['thrace','marmara'],population:92,prosperity:88,production:82,food:62,trade:96,stability:90,fortification:85,infrastructure:88,resource:'Silk',coastal:true},
{id:'thrace',name:'Thrace',owner:'ottoman',neighbors:['istanbul','edirne','sofia'],population:61,prosperity:66,production:57,food:78,trade:62,stability:78,fortification:52,infrastructure:63,resource:'Grain'},
{id:'marmara',name:'Marmara',owner:'ottoman',neighbors:['istanbul','bursa'],population:68,prosperity:72,production:64,food:69,trade:78,stability:82,fortification:45,infrastructure:70,resource:'Timber',coastal:true},
{id:'edirne',name:'Edirne',owner:'ottoman',neighbors:['thrace','sofia','thessaloniki'],population:55,prosperity:63,production:54,food:82,trade:58,stability:80,fortification:61,infrastructure:60,resource:'Grain'},
{id:'bursa',name:'Bursa',owner:'ottoman',neighbors:['marmara'],population:70,prosperity:74,production:71,food:73,trade:70,stability:85,fortification:48,infrastructure:68,resource:'Silk'},
{id:'sofia',name:'Sofia',owner:'bulgaria',neighbors:['thrace','edirne','thessaloniki','belgrade'],population:48,prosperity:52,production:49,food:74,trade:42,stability:69,fortification:57,infrastructure:49,resource:'Iron'},
{id:'thessaloniki',name:'Thessaloniki',owner:'greece',neighbors:['edirne','sofia','athens'],population:58,prosperity:69,production:55,food:66,trade:82,stability:73,fortification:59,infrastructure:64,resource:'Saltpeter',coastal:true},
{id:'athens',name:'Athens',owner:'greece',neighbors:['thessaloniki'],population:54,prosperity:71,production:48,food:51,trade:88,stability:76,fortification:63,infrastructure:66,resource:'Marble',coastal:true},
{id:'belgrade',name:'Belgrade',owner:'serbia',neighbors:['sofia','budapest'],population:46,prosperity:49,production:51,food:70,trade:45,stability:72,fortification:72,infrastructure:50,resource:'Iron'},
{id:'budapest',name:'Buda',owner:'austria',neighbors:['belgrade'],population:64,prosperity:68,production:67,food:72,trade:63,stability:80,fortification:76,infrastructure:67,resource:'Horses'}];
export const POWERS={ottoman:{name:'Ottoman Empire'},bulgaria:{name:'Bulgaria'},greece:{name:'Greek States'},serbia:{name:'Serbia'},austria:{name:'Habsburg Austria'}};
const defaultRelations={bulgaria:35,greece:22,serbia:42,austria:18};
export function newCampaign(faction='ottoman'){return{version:CAMPAIGN_VERSION,faction,turn:1,treasury:900,knowledge:0,food:500,production:400,manpower:650,era:0,eraEnteredTurn:1,research:[],activeResearch:null,ageTransition:null,strategicAP:3,maxStrategicAP:3,warExhaustion:0,relations:{...defaultRelations},wars:[],alliances:[],tradePartners:[],regions:REGIONS.map(r=>({...r,damage:0,occupied:0})),objectives:[{id:'capital50',name:'Hold Constantinople',description:'Keep Constantinople for 50 turns.',progress:1,target:50,complete:false},{id:'realm20',name:'Regional Power',description:'Control 8 regions for 20 consecutive turns.',progress:0,target:20,complete:false,streak:true}],history:[]}}
export function normalizeCampaign(c){if(!c)return c;if(!Array.isArray(c.research))c.research=[];if(!Number.isInteger(c.era))c.era=0;if(!Array.isArray(c.tradePartners))c.tradePartners=[];if(!Number.isFinite(c.eraEnteredTurn))c.eraEnteredTurn=c.turn||1;if(!Number.isFinite(c.maxStrategicAP))c.maxStrategicAP=3;if(!Number.isFinite(c.strategicAP))c.strategicAP=c.maxStrategicAP;if(!Number.isFinite(c.warExhaustion))c.warExhaustion=0;if(!('activeResearch'in c))c.activeResearch=null;if(!('ageTransition'in c))c.ageTransition=null;return c}
export function owned(c){return c.regions.filter(r=>r.owner===c.faction)}
export function relation(c,p){return c.relations[p]??30}
export function regionEconomy(c,r){let borderPenalty=0,friendlyBonus=0;for(const nid of r.neighbors){const n=c.regions.find(x=>x.id===nid);if(!n||n.owner===c.faction)continue;const rel=relation(c,n.owner);if(c.wars.includes(n.owner))borderPenalty+=.16;else if(rel<30)borderPenalty+=.07;else if(rel>=60)friendlyBonus+=.05}borderPenalty=Math.min(.42,borderPenalty);friendlyBonus=Math.min(.15,friendlyBonus);const damagePenalty=(r.damage||0)/125,stability=r.stability/100,infra=.65+r.infrastructure/285,occupation=(r.occupied||0)>0?.72:1;const exhaustion=Math.max(.72,1-(c.warExhaustion||0)/350);const efficiency=Math.max(.18,(1-borderPenalty+friendlyBonus-damagePenalty)*stability*infra*occupation*exhaustion);return{gold:Math.round((r.prosperity*.65+r.trade*.45)*efficiency),food:Math.round(r.food*.45*efficiency),production:Math.round(r.production*.38*efficiency),knowledge:Math.round((r.population*.12+r.trade*.06)*efficiency),manpower:Math.round(r.population*.18*stability),borderPenalty,friendlyBonus,efficiency}}
export function totals(c){return owned(c).reduce((a,r)=>{const e=regionEconomy(c,r);for(const k of ['gold','food','production','knowledge','manpower'])a[k]+=e[k];return a},{gold:0,food:0,production:0,knowledge:0,manpower:0})}
export function administration(c){const n=owned(c).length;return Math.max(.52,1-Math.max(0,n-8)*.009)}
export function forecastTurn(c){const t=totals(c),admin=administration(c),frontiers=owned(c).filter(r=>r.neighbors.some(id=>{const n=c.regions.find(x=>x.id===id);return n&&c.wars.includes(n.owner)})).length,pop=owned(c).reduce((n,r)=>n+r.population,0),warUpkeep=c.wars.length*45+frontiers*12,armyUpkeep=Math.round(c.manpower*.055),stateUpkeep=Math.round(owned(c).length*14+pop*.055),wealthOverhead=Math.round(Math.max(0,c.treasury-5000)*.0035),maintenance=warUpkeep+armyUpkeep+stateUpkeep+wealthOverhead,foodUse=Math.round(pop*.32+c.manpower*.025+owned(c).length*3),income=Math.round(t.gold*admin),netGold=income-maintenance,netFood=t.food-foodUse;return{...t,admin,frontiers,warUpkeep,armyUpkeep,stateUpkeep,wealthOverhead,maintenance,foodUse,income,netGold,netFood}}
export function researchDuration(tech){return Math.max(2,Math.min(8,2+Math.ceil((tech?.cost||50)/120)))}
export function startResearch(c,tech){normalizeCampaign(c);if(c.activeResearch)return{ok:false,reason:'Research already in progress.'};if(c.research.includes(tech.id))return{ok:false,reason:'Already researched.'};if(!tech.requires.every(id=>c.research.includes(id)))return{ok:false,reason:'Prerequisites missing.'};if(c.knowledge<tech.cost)return{ok:false,reason:'Not enough Knowledge.'};const turns=researchDuration(tech);c.knowledge-=tech.cost;c.activeResearch={id:tech.id,remaining:turns,total:turns};return{ok:true,turns}}
export function ageStatus(c,nextEra,required=[]){const min=ERA_MIN_TURNS[c.era]||0,spent=(c.turn||1)-(c.eraEnteredTurn||1),tech=required.every(id=>c.research.includes(id));return{min,spent,timeReady:spent>=min,tech,transition:c.ageTransition}}
export function startAgeTransition(c,targetEra,required=[]){const s=ageStatus(c,targetEra,required);if(c.ageTransition)return{ok:false,reason:'Age transition already underway.'};if(!s.tech)return{ok:false,reason:'Required technologies are missing.'};if(!s.timeReady)return{ok:false,reason:`Remain in this age for ${s.min-s.spent} more turns.`};const turns=4+c.era;c.ageTransition={target:targetEra,remaining:turns,total:turns};return{ok:true,turns}}
export function spendAction(c,n=1){normalizeCampaign(c);if(c.strategicAP<n)return false;c.strategicAP-=n;return true}
export function investRegion(c,r,amount,type='infrastructure'){amount=Math.max(100,Math.min(Math.floor(amount||0),Math.floor(c.treasury)));if(amount<100)return{ok:false,reason:'Minimum investment is 100.'};const prodCost=Math.max(10,Math.round(amount*.12));if(c.production<prodCost)return{ok:false,reason:`Requires ${prodCost} Production.`};if(!spendAction(c,1))return{ok:false,reason:'No strategic actions remaining this turn.'};c.treasury-=amount;c.production-=prodCost;const scale=Math.sqrt(amount/100);let text='';if(type==='infrastructure'){r.infrastructure=Math.min(100,r.infrastructure+scale*1.7);r.prosperity=Math.min(100,r.prosperity+scale*.7);text='infrastructure'}else if(type==='fortification'){r.fortification=Math.min(100,r.fortification+scale*1.9);text='fortifications'}else if(type==='economy'){r.prosperity=Math.min(100,r.prosperity+scale*1.5);r.trade=Math.min(100,r.trade+scale*.65);text='economy'}else if(type==='agriculture'){r.food=Math.min(100,r.food+scale*1.6);r.stability=Math.min(100,r.stability+scale*.25);text='agriculture'}else if(type==='reconstruction'){r.damage=Math.max(0,(r.damage||0)-scale*3.2);r.stability=Math.min(100,r.stability+scale*.7);text='reconstruction'}return{ok:true,amount,prodCost,text}}
function strategicEvent(c){const own=owned(c);if(!own.length)return null;const r=own[(c.turn*7)%own.length];if(c.turn%11===0){r.stability=Math.max(20,r.stability-5);r.prosperity=Math.max(20,r.prosperity-3);return`Unrest in ${r.name}: stability −5, prosperity −3.`}if(c.turn%9===0){const gain=Math.round(35+r.trade*.8);c.treasury+=gain;return`Merchant boom in ${r.name}: +${gain} Treasury.`}if(c.turn%7===0){r.damage=Math.min(90,(r.damage||0)+4);return`Infrastructure failure in ${r.name}: regional damage +4%.`}return null}
export function advanceTurn(c){normalizeCampaign(c);const f=forecastTurn(c),messages=[];c.treasury+=f.netGold;c.food+=f.netFood;c.production+=Math.round(f.production*f.admin);c.knowledge+=Math.round(f.knowledge*f.admin);c.manpower=Math.min(c.manpower+Math.round(f.manpower*.14),2000);c.turn++;c.strategicAP=c.maxStrategicAP;if(c.wars.length)c.warExhaustion=Math.min(100,c.warExhaustion+c.wars.length*1.6);else c.warExhaustion=Math.max(0,c.warExhaustion-2.5);if(c.food<0){const deficit=Math.abs(c.food);c.food=0;c.manpower=Math.max(0,Math.round(c.manpower*.94));owned(c).forEach(r=>{r.stability=Math.max(15,r.stability-4);r.prosperity=Math.max(15,r.prosperity-2)});messages.push(`Food crisis: shortage of ${deficit}. Stability and manpower fell.`)}if(c.treasury<0){c.treasury=0;owned(c).forEach(r=>r.stability=Math.max(15,r.stability-2));messages.push('Treasury exhausted: public order deteriorated.')}if(c.warExhaustion>35){const loss=Math.min(2.5,c.warExhaustion/40);owned(c).forEach(r=>r.stability=Math.max(15,r.stability-loss));messages.push(`War exhaustion ${Math.round(c.warExhaustion)}% is reducing stability.`)}if(c.activeResearch){c.activeResearch.remaining--;if(c.activeResearch.remaining<=0){const id=c.activeResearch.id;if(!c.research.includes(id))c.research.push(id);messages.push(`Research completed: ${id}.`);c.activeResearch=null}}if(c.ageTransition){c.ageTransition.remaining--;if(c.ageTransition.remaining<=0){c.era=c.ageTransition.target;c.eraEnteredTurn=c.turn;messages.push('A new historical age has begun.');c.ageTransition=null}}for(const r of c.regions){if(r.damage>0)r.damage=Math.max(0,r.damage-1.5);if(r.occupied>0)r.occupied--;if(r.owner===c.faction&&r.occupied<=0)r.stability=Math.min(100,r.stability+.18)}const ev=strategicEvent(c);if(ev)messages.push(ev);updateObjectives(c);const summary=`Turn ${c.turn}: Treasury ${f.netGold>=0?'+':''}${f.netGold}; maintenance ${f.maintenance}; Food ${f.netFood>=0?'+':''}${f.netFood}.`;c.history.unshift({turn:c.turn,text:[summary,...messages].join(' ')});c.history=c.history.slice(0,40);return{...f,messages,summary}}
export function updateObjectives(c){const cap=c.objectives.find(o=>o.id==='capital50'),istanbul=c.regions.find(r=>r.id==='istanbul');if(cap&&!cap.complete){cap.progress=istanbul.owner===c.faction?cap.progress+1:0;cap.complete=cap.progress>=cap.target}const realm=c.objectives.find(o=>o.id==='realm20');if(realm&&!realm.complete){realm.progress=owned(c).length>=8?realm.progress+1:0;realm.complete=realm.progress>=realm.target}}
export function battleBudget(c,regionId,base=700){const r=c.regions.find(x=>x.id===regionId)||owned(c)[0],e=regionEconomy(c,r),supply=Math.min(1.2,.55+r.infrastructure/180),fort=r.owner===c.faction?r.fortification*1.4:0,treasury=Math.min(250,Math.max(0,c.treasury*.08));return{region:r,budget:Math.max(250,Math.round(base*e.efficiency*supply+fort+treasury)),efficiency:e.efficiency,supply,fortification:fort,borderPenalty:e.borderPenalty}}
export function applyBattle(c,regionId,result){const r=c.regions.find(x=>x.id===regionId);if(!r)return;const damage=Math.round((1-(result.baseHealth??.5))*55+(result.breaches||0)*2);r.damage=Math.min(90,(r.damage||0)+damage);r.stability=Math.max(15,r.stability-(result.victory?3:14));c.manpower=Math.max(0,c.manpower-(result.losses||20));c.treasury=Math.max(0,c.treasury-(result.cost||80));c.warExhaustion=Math.min(100,(c.warExhaustion||0)+(result.victory?3:7));if(!result.victory&&result.attacker)r.owner=result.attacker;if(result.victory&&result.conquest){r.owner=c.faction;r.occupied=8;r.stability=Math.min(r.stability,45)}c.history.unshift({turn:c.turn,text:`${result.victory?'Victory':'Defeat'} at ${r.name}. Regional damage now ${r.damage}%.`})}
export function saveCampaign(c){try{normalizeCampaign(c);localStorage.setItem('chronicle_campaign_v1',JSON.stringify(c));return true}catch{return false}}
export function loadCampaign(){try{const x=JSON.parse(localStorage.getItem('chronicle_campaign_v1'));return x?.version===CAMPAIGN_VERSION?normalizeCampaign(x):null}catch{return null}}
