import{DEFENCES,ENEMIES,ERAS}from'./data.js?v=8';
import{loadCampaign,saveCampaign,battleBudget,applyBattle}from'./campaign.js?v=8';
import{serviceable,UPGRADE_PATHS}from'./battle-data.js?v=8';
const $=x=>document.getElementById(x),canvas=$('battle'),ctx=canvas.getContext('2d'),W=960,H=600;
const params=new URLSearchParams(location.search),regionId=params.get('region')||'sofia',C=loadCampaign();if(!C)location.href='campaign.html?v=8';
const target=C?.regions.find(r=>r.id===regionId);if(!target)location.href='campaign.html?v=8';
const source=C.regions.filter(r=>r.owner===C.faction&&r.neighbors.includes(regionId)).sort((a,b)=>b.infrastructure-a.infrastructure)[0]||C.regions.find(r=>r.id==='istanbul');
const budgetData=battleBudget(C,source.id),MAX_WAVES=Math.max(10,Math.min(18,10+Math.round(target.fortification/14))),researched=new Set(C.research||[]);
const route=[[0,318],[90,318],[150,318],[150,250],[245,250],[320,250],[320,360],[410,360],[500,360],[500,275],[590,275],[675,275],[675,205],[765,205],[835,255],[900,255],[960,255]],path=route.map(([x,y])=>({x,y}));
const S={gold:Math.round(budgetData.budget*.86),lives:24,wave:0,towers:[],enemies:[],shots:[],fx:[],build:null,active:false,left:0,timer:0,last:performance.now(),kills:0,breaches:0,spent:0,ended:false,selected:null,drag:null};
const available=Object.entries(DEFENCES).filter(([id,d])=>serviceable(id,C.era)&&(!d.requires||researched.has(d.requires))&&(!d.faction||d.faction===C.faction));
if(!available.length)Object.entries(DEFENCES).filter(([id])=>serviceable(id,C.era)).slice(0,2).forEach(x=>available.push(x));
$('battle-title').textContent=`ASSAULT ON ${target.name.toUpperCase()}`;$('region-name').textContent=target.name;$('era-name').textContent=ERAS[C.era]?.name?.toUpperCase()||'ERA';
function pointerWorld(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*W/r.width,y:(e.clientY-r.top)*H/r.height,inside:e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom}}
function segDist(px,py,a,b){const dx=b.x-a.x,dy=b.y-a.y,l=dx*dx+dy*dy||1,t=Math.max(0,Math.min(1,((px-a.x)*dx+(py-a.y)*dy)/l)),x=a.x+t*dx,y=a.y+t*dy;return Math.hypot(px-x,py-y)}
function validPlacement(x,y){if(x<35||x>W-45||y<45||y>H-45)return false;if(path.slice(0,-1).some((p,i)=>segDist(x,y,p,path[i+1])<48))return false;if(S.towers.some(t=>Math.hypot(t.x-x,t.y-y)<54))return false;return true}
function refresh(){$('gold').textContent=Math.floor(S.gold);$('lives').textContent=S.lives;$('wave').textContent=`${S.wave} / ${MAX_WAVES}`;renderArsenal();renderTowerPanel()}
function renderArsenal(){const el=$('arsenal-list');el.innerHTML='';available.forEach(([id,d])=>{const b=document.createElement('button');b.className=`tower-btn ${d.kind} ${S.build===id?'active':''} ${S.gold<d.cost?'locked':''}`;b.innerHTML=`<b>${d.name}</b><span>${d.cost} GOLD</span><em>${d.role}</em>`;b.addEventListener('click',()=>{S.build=id;S.selected=null;refresh();$('msg').textContent=`${d.name} selected — tap or drag onto open ground.`});b.addEventListener('pointerdown',e=>beginDrag(e,id));el.appendChild(b)})}
function beginDrag(e,id){if(S.ended)return;const d=DEFENCES[id];if(S.gold<d.cost)return;e.preventDefault();S.build=id;S.selected=null;S.drag={type:id,x:-100,y:-100,valid:false};document.body.classList.add('dragging');renderTowerPanel();window.addEventListener('pointermove',dragMove,{passive:false});window.addEventListener('pointerup',dragEnd,{once:true})}
function dragMove(e){if(!S.drag)return;e.preventDefault();const p=pointerWorld(e);S.drag.x=p.x;S.drag.y=p.y;S.drag.valid=p.inside&&validPlacement(p.x,p.y)}
function dragEnd(e){window.removeEventListener('pointermove',dragMove);if(!S.drag)return;const p=pointerWorld(e),drag=S.drag;S.drag=null;document.body.classList.remove('dragging');if(p.inside&&validPlacement(p.x,p.y))placeTower(drag.type,p.x,p.y);refresh()}
function placeTower(id,x,y){const d=DEFENCES[id];if(!d||S.gold<d.cost||!validPlacement(x,y))return false;S.gold-=d.cost;S.spent+=d.cost;S.towers.push({type:id,x,y,tier:1,branch:null,damage:d.damage*2.05,range:d.range,rate:d.rate,splash:d.splash||0,cd:0,recoil:0,spent:d.cost});burst(x,y,'dust',12);$('msg').textContent=`${d.name} deployed. Drag another or begin the wave.`;return true}
canvas.addEventListener('click',e=>{if(S.ended||S.drag)return;const p=pointerWorld(e),near=S.towers.slice().sort((a,b)=>Math.hypot(a.x-p.x,a.y-p.y)-Math.hypot(b.x-p.x,b.y-p.y))[0];if(near&&Math.hypot(near.x-p.x,near.y-p.y)<34){S.selected=near;S.build=null;refresh();return}if(S.build)placeTower(S.build,p.x,p.y)&&refresh();else{S.selected=null;refresh()}});
$('arsenal-toggle').onclick=()=>document.querySelector('.arsenal').classList.toggle('open');$('tower-close').onclick=()=>{S.selected=null;renderTowerPanel()};
function renderTowerPanel(){const p=$('tower-panel');if(!S.selected){p.classList.remove('show');return}const t=S.selected,d=DEFENCES[t.type],kind=UPGRADE_PATHS[d.kind]||UPGRADE_PATHS.infantry;p.classList.add('show');$('tower-info').innerHTML=`<h3>${d.name}</h3><div class="sub">Damage ${Math.round(t.damage)} · Range ${Math.round(t.range)} · Fire rate ${t.rate.toFixed(2)}/s</div><span class="tier">TIER ${t.tier}${t.branch?` · ${t.branch.toUpperCase()}`:''}</span>`;let opts=[];if(t.tier===1)opts=kind[2];else if(t.tier===2&&t.branch)opts=[kind[3][t.branch]];$('upgrade-actions').innerHTML=opts.length?`<div class="upgrade-grid">${opts.map((o,i)=>{const cost=Math.round(d.cost*o.cost);return`<button data-up="${i}" ${S.gold<cost?'disabled':''}><b>${o.name}</b><span>${o.desc}</span><strong>${cost} GOLD</strong></button>`}).join('')}</div>`:`<div class="sub" style="margin-top:8px">Maximum battlefield tier reached.</div>`;[...$('upgrade-actions').querySelectorAll('[data-up]')].forEach((b,i)=>b.onclick=()=>upgradeTower(opts[i]));$('sell-tower').onclick=()=>sellTower()}
function upgradeTower(o){const t=S.selected,d=DEFENCES[t.type],cost=Math.round(d.cost*o.cost);if(S.gold<cost)return;S.gold-=cost;S.spent+=cost;t.spent+=cost;t.tier++;if(t.tier===2)t.branch=o.id;t.damage*=o.damage||1;t.range*=o.range||1;t.rate*=o.rate||1;t.splash*=o.splash||1;burst(t.x,t.y,'upgrade',18);refresh()}
function sellTower(){const t=S.selected;if(!t)return;S.gold+=Math.round(t.spent*.62);S.towers.splice(S.towers.indexOf(t),1);S.selected=null;refresh()}
function enemyType(w,i){if(C.era>=4){if(w>8&&i%5===0)return'tank';if(i%4===0)return'vehicle';return i%3?'heavy':'runner'}if(C.era===3){if(w>9&&i%6===0)return'vehicle';return i%4?'heavy':'runner'}if(w<5)return i%5?'infantry':'runner';if(w<10)return i%6?'heavy':'runner';return i%5?'heavy':'siege'}
function spawn(){const type=enemyType(S.wave,S.left),b=ENEMIES[type],scale=.46*(1+S.wave*.052+target.fortification*.0023);S.enemies.push({...b,type,hp:b.hp*scale,maxHp:b.hp*scale,speed:b.speed*(1+S.wave*.003),pi:0,x:path[0].x,y:path[0].y,bob:Math.random()*6.2})}
function startWave(){if(S.active||S.ended)return;S.wave++;S.active=true;S.left=4+Math.ceil(S.wave*1.18);S.timer=0;S.gold+=42+S.wave*5;$('start-wave').disabled=true;$('msg').textContent=`Wave ${S.wave}: ${target.name}'s defenders are advancing.`;refresh()}$('start-wave').onclick=startWave;
function burst(x,y,type,n=7){for(let i=0;i<n;i++)S.fx.push({x,y,vx:(Math.random()-.5)*100,vy:(Math.random()-.7)*80,life:.45+Math.random()*.35,max:.8,type,r:2+Math.random()*5})}
function hit(p){const ts=p.splash?S.enemies.filter(e=>Math.hypot(e.x-p.target.x,e.y-p.target.y)<p.splash):[p.target];ts.forEach(e=>{e.hp-=p.damage*(1-e.armor*(p.kind==='antiarmor'?.12:1));burst(e.x,e.y,p.type==='shell'?'smoke':'spark',p.type==='shell'?10:4);if(e.hp<=0){const i=S.enemies.indexOf(e);if(i>=0){S.enemies.splice(i,1);S.kills++;S.gold+=Math.round(e.reward*1.18)}}})}
function update(dt){if(S.ended)return;if(S.active&&S.left){S.timer-=dt;if(S.timer<=0){spawn();S.left--;S.timer=.8}}for(let i=S.enemies.length-1;i>=0;i--){const e=S.enemies[i],q=path[e.pi+1];e.bob+=dt*4;if(!q){S.enemies.splice(i,1);S.lives--;S.breaches++;burst(e.x,e.y,'smoke',10);if(S.lives<=0)return finish(false);continue}const dx=q.x-e.x,dy=q.y-e.y,d=Math.hypot(dx,dy),m=e.speed*dt;if(d<=m){e.x=q.x;e.y=q.y;e.pi++}else{e.x+=dx/d*m;e.y+=dy/d*m}}for(const t of S.towers){const d=DEFENCES[t.type];t.cd-=dt;t.recoil=Math.max(0,t.recoil-dt*4);if(t.cd>0)continue;let targetEnemy=null,best=-1;for(const e of S.enemies)if(Math.hypot(e.x-t.x,e.y-t.y)<=t.range&&e.pi>=best){targetEnemy=e;best=e.pi}if(targetEnemy){t.cd=1/t.rate;t.recoil=1;S.shots.push({x:t.x,y:t.y,target:targetEnemy,damage:t.damage,kind:d.kind,type:d.projectile,splash:t.splash||0,trail:[]});burst(t.x+8,t.y-8,'flash',3)}}for(let i=S.shots.length-1;i>=0;i--){const p=S.shots[i];if(!S.enemies.includes(p.target)){S.shots.splice(i,1);continue}p.trail.push([p.x,p.y]);if(p.trail.length>6)p.trail.shift();const dx=p.target.x-p.x,dy=p.target.y-p.y,d=Math.hypot(dx,dy),m=(p.type==='missile'?470:760)*dt;if(d<m+8){hit(p);S.shots.splice(i,1)}else{p.x+=dx/d*m;p.y+=dy/d*m}}for(let i=S.fx.length-1;i>=0;i--){const f=S.fx[i];f.life-=dt;f.x+=f.vx*dt;f.y+=f.vy*dt;f.vy+=35*dt;if(f.life<=0)S.fx.splice(i,1)}if(S.active&&!S.left&&!S.enemies.length){S.active=false;$('start-wave').disabled=false;if(S.wave>=MAX_WAVES)finish(true);else{$('msg').textContent=`Wave ${S.wave} cleared. Upgrade your positions or continue.`;refresh()}}}
function finish(victory){if(S.ended)return;S.ended=true;const health=Math.max(0,S.lives/24),losses=Math.round((1-health)*65+S.breaches*2+S.wave*1.4),cost=Math.round(70+S.spent*.12);applyBattle(C,regionId,{victory,conquest:victory,attacker:target.owner,baseHealth:health,breaches:S.breaches,losses,cost});saveCampaign(C);$('result').classList.add('show');$('result-title').textContent=victory?`${target.name.toUpperCase()} CAPTURED`:'ASSAULT FAILED';$('result-text').textContent=victory?`After ${S.wave} waves, Ottoman forces secured ${target.name}. ${S.breaches} breaches and ${losses} campaign manpower losses were recorded. The region now enters occupation and reconstruction.`:`The assault collapsed after wave ${S.wave}. ${losses} manpower and ${cost} Treasury were lost. ${target.name} remains enemy territory.`;$('start-wave').disabled=true}
$('return-map').onclick=()=>location.href='campaign.html?v=8';$('retreat').onclick=()=>{if(!S.ended)finish(false);else location.href='campaign.html?v=8'};
const seed=[...target.id].reduce((a,c)=>a+c.charCodeAt(0),0),decor=Array.from({length:58},(_,i)=>({x:(i*167+seed*19)%W,y:(i*103+seed*13)%H,k:(i+seed)%5,s:6+(i*7)%15}));
function terrain(){const coastal=target.coastal,g=ctx.createLinearGradient(0,0,W,H);g.addColorStop(0,coastal?'#799063':'#7e965e');g.addColorStop(.58,coastal?'#567a53':'#5f7b4c');g.addColorStop(1,'#385947');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.fillStyle='#ffffff08';for(let y=20;y<H;y+=34)for(let x=(y%68);x<W;x+=68){ctx.beginPath();ctx.ellipse(x,y,28,9,-.25,0,7);ctx.fill()}if(coastal){const shore=138;const wg=ctx.createLinearGradient(0,0,shore,0);wg.addColorStop(0,'#2b6374');wg.addColorStop(1,'#4a8590');ctx.fillStyle=wg;ctx.fillRect(0,0,shore,H);ctx.strokeStyle='#9ed0d455';ctx.lineWidth=2;for(let y=18;y<H;y+=27){ctx.beginPath();ctx.moveTo(14+(y%3)*8,y);ctx.bezierCurveTo(45,y-5,70,y+5,113,y);ctx.stroke()}ctx.fillStyle='#d2bf8a';ctx.beginPath();ctx.moveTo(128,0);for(let y=0;y<=H;y+=40)ctx.lineTo(142+Math.sin(y*.06)*7,y);ctx.lineTo(165,H);ctx.lineTo(165,0);ctx.fill()}decor.forEach(o=>{if(path.slice(0,-1).some((p,i)=>segDist(o.x,o.y,p,path[i+1])<60)||coastal&&o.x<175)return;if(o.k<3)drawTree(o.x,o.y,o.s);else if(o.k===3)drawRock(o.x,o.y,o.s);else drawHouse(o.x,o.y,o.s)});drawRoad();drawFortress()}
function drawRoad(){ctx.lineCap='round';ctx.lineJoin='round';ctx.strokeStyle='#2e2a2255';ctx.lineWidth=58;ctx.beginPath();path.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke();ctx.strokeStyle=C.era>=3?'#77756b':'#b69b6b';ctx.lineWidth=47;ctx.stroke();ctx.strokeStyle='#e7d29f33';ctx.lineWidth=3;ctx.setLineDash([8,15]);ctx.stroke();ctx.setLineDash([])}
function drawTree(x,y,s){ctx.fillStyle='#243a2d';ctx.fillRect(x-2,y,4,s);ctx.fillStyle='#2d5537';ctx.beginPath();ctx.arc(x-5,y-5,s*.55,0,7);ctx.arc(x+5,y-4,s*.6,0,7);ctx.arc(x,y-12,s*.67,0,7);ctx.fill();ctx.fillStyle='#6d925944';ctx.beginPath();ctx.arc(x-4,y-10,s*.34,0,7);ctx.fill()}
function drawRock(x,y,s){ctx.fillStyle='#0003';ctx.beginPath();ctx.ellipse(x+3,y+4,s*.7,s*.3,0,0,7);ctx.fill();ctx.fillStyle='#73786b';ctx.beginPath();ctx.moveTo(x-s*.6,y+3);ctx.lineTo(x-s*.25,y-s*.55);ctx.lineTo(x+s*.45,y-s*.35);ctx.lineTo(x+s*.65,y+4);ctx.closePath();ctx.fill()}
function drawHouse(x,y,s){ctx.fillStyle='#0002';ctx.fillRect(x-s*.55,y,s*1.1,s*.65);ctx.fillStyle='#cfb77e';ctx.fillRect(x-s*.48,y-s*.25,s*.96,s*.7);ctx.fillStyle='#744d3d';ctx.beginPath();ctx.moveTo(x-s*.62,y-s*.22);ctx.lineTo(x,y-s*.75);ctx.lineTo(x+s*.62,y-s*.22);ctx.closePath();ctx.fill()}
function drawFortress(){const x=906,y=214;ctx.fillStyle='#0004';ctx.fillRect(x-8,y+18,64,84);ctx.fillStyle=C.era<3?'#8a806d':'#4f5b55';ctx.fillRect(x,y,54,90);ctx.fillStyle=C.era<3?'#a49a82':'#64716a';for(let i=0;i<4;i++)ctx.fillRect(x+i*15,y-11,9,18);ctx.fillStyle='#2e2924';ctx.fillRect(x+18,y+45,19,45);ctx.fillStyle='#d6ad49';ctx.fillRect(x+7,y+14,30,4)}
function tower(t,ghost=false){const d=DEFENCES[t.type],tier=t.tier||1;ctx.save();ctx.translate(t.x,t.y);if(ghost)ctx.globalAlpha=.68;ctx.fillStyle='#0005';ctx.beginPath();ctx.ellipse(4,18,25+tier*2,9+tier,0,0,7);ctx.fill();ctx.fillStyle=tier===3?'#8a7448':'#6d704f';ctx.beginPath();ctx.ellipse(0,10,19+tier*3,10+tier,0,0,7);ctx.fill();if(d.kind==='artillery'||d.kind==='antiarmor'){ctx.fillStyle=d.kind==='antiarmor'?'#47584c':'#5a5d45';ctx.beginPath();ctx.roundRect(-18-tier*2,-11-tier,36+tier*4,24+tier*2,7);ctx.fill();ctx.strokeStyle='#222b2b';ctx.lineWidth=6+tier;ctx.beginPath();ctx.moveTo(-2,-3);ctx.lineTo(28+tier*5-(t.recoil||0)*4,-19);ctx.stroke();ctx.fillStyle='#222b2b';ctx.beginPath();ctx.arc(-13,14,6+tier,0,7);ctx.arc(13,14,6+tier,0,7);ctx.fill()}else{const count=tier===1?2:tier===2?3:4;for(let i=0;i<count;i++){const ox=(i-(count-1)/2)*9;ctx.fillStyle=C.faction==='ottoman'&&t.type==='janissary'?'#f0e4cd':'#d6c8aa';ctx.fillRect(ox-3,-5,6,17);ctx.fillStyle=C.faction==='ottoman'?'#a52e34':'#465847';ctx.beginPath();ctx.arc(ox,-9,5,0,7);ctx.fill();ctx.strokeStyle='#2c302b';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(ox+2,-2);ctx.lineTo(ox+16-(t.recoil||0)*3,-11);ctx.stroke()}}if(tier>1){ctx.fillStyle='#d9ad46';for(let i=0;i<tier;i++){ctx.beginPath();ctx.arc(-8+i*8,24,2.2,0,7);ctx.fill()}}ctx.restore()}
function enemy(e){const bob=Math.sin(e.bob)*2;ctx.save();ctx.translate(e.x,e.y+bob);ctx.fillStyle='#0004';ctx.beginPath();ctx.ellipse(3,13,16,6,0,0,7);ctx.fill();if(['vehicle','tank'].includes(e.type)){ctx.fillStyle=e.type==='tank'?'#374638':'#55624c';ctx.beginPath();ctx.roundRect(-18,-11,36,22,5);ctx.fill();ctx.fillStyle='#26322b';ctx.fillRect(-8,-16,16,9);ctx.fillRect(1,-14,24,3);ctx.strokeStyle='#1f2722';ctx.lineWidth=3;ctx.strokeRect(-16,-9,32,18)}else{ctx.fillStyle=e.color;ctx.beginPath();ctx.roundRect(-8,-5,16,20,5);ctx.fill();ctx.fillStyle=C.era<2?'#c9ad89':'#d0b18f';ctx.beginPath();ctx.arc(0,-9,6,0,7);ctx.fill();ctx.fillStyle=C.era>=3?'#39443b':'#4d4436';ctx.beginPath();ctx.arc(0,-12,7,Math.PI,0);ctx.fill();if(C.era<2){ctx.strokeStyle='#6c553b';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(-6,0);ctx.lineTo(-13,9);ctx.stroke()}}ctx.fillStyle='#11191c';ctx.fillRect(-17,-25,34,5);ctx.fillStyle=e.hp/e.maxHp>.5?'#73d482':'#ef685e';ctx.fillRect(-16,-24,32*Math.max(0,e.hp/e.maxHp),3);ctx.restore()}
function draw(){terrain();if(S.selected){ctx.fillStyle='#eac46713';ctx.strokeStyle='#f1ca6b77';ctx.lineWidth=2;ctx.beginPath();ctx.arc(S.selected.x,S.selected.y,S.selected.range,0,7);ctx.fill();ctx.stroke()}S.towers.forEach(t=>tower(t));S.enemies.forEach(enemy);S.shots.forEach(p=>{p.trail.forEach((q,i)=>{ctx.globalAlpha=(i+1)/9;ctx.fillStyle=p.type==='missile'?'#f1a56b':'#ffe2a2';ctx.beginPath();ctx.arc(q[0],q[1],2,0,7);ctx.fill()});ctx.globalAlpha=1;ctx.fillStyle='#fff0bc';ctx.beginPath();ctx.arc(p.x,p.y,p.type==='shell'?4:2.5,0,7);ctx.fill()});S.fx.forEach(f=>{ctx.globalAlpha=Math.max(0,f.life/f.max);ctx.fillStyle=f.type==='flash'?'#ffd86a':f.type==='smoke'?'#5d625e':f.type==='upgrade'?'#e3bd5d':'#c7aa70';ctx.beginPath();ctx.arc(f.x,f.y,f.r*(1+(1-f.life/f.max)),0,7);ctx.fill()});ctx.globalAlpha=1;if(S.drag&&S.drag.x>=0){const d=DEFENCES[S.drag.type];ctx.fillStyle=S.drag.valid?'#78d38e18':'#ef6d6818';ctx.strokeStyle=S.drag.valid?'#8ee3a3aa':'#ff827caa';ctx.lineWidth=2;ctx.beginPath();ctx.arc(S.drag.x,S.drag.y,d.range,0,7);ctx.fill();ctx.stroke();tower({...S.drag,tier:1,recoil:0},true)}}
function loop(now){const dt=Math.min(.033,(now-S.last)/1000);S.last=now;update(dt);draw();requestAnimationFrame(loop)}refresh();requestAnimationFrame(loop);
