import{DEFENCES,ENEMIES}from'./data.js';import{loadCampaign,saveCampaign,battleBudget,applyBattle}from'./campaign.js';
const $=x=>document.getElementById(x),canvas=$('battle'),ctx=canvas.getContext('2d'),W=960,H=600,T=60;
const params=new URLSearchParams(location.search),regionId=params.get('region')||'sofia',C=loadCampaign();if(!C)location.href='campaign.html';const target=C?.regions.find(r=>r.id===regionId);if(!target)location.href='campaign.html';const source=C?.regions.filter(r=>r.owner===C.faction&&r.neighbors.includes(regionId)).sort((a,b)=>b.infrastructure-a.infrastructure)[0]||C.regions.find(r=>r.id==='istanbul');const budgetData=battleBudget(C,source.id);const MAX_WAVES=Math.max(10,Math.min(16,9+Math.round(target.fortification/18)));
const route=[[0,5],[1,5],[2,5],[2,4],[3,4],[4,4],[5,4],[5,5],[5,6],[6,6],[7,6],[8,6],[8,5],[8,4],[9,4],[10,4],[11,4],[11,3],[12,3],[13,3],[13,4],[13,5],[14,5],[15,5]],routeSet=new Set(route.map(p=>p.join(','))),path=route.map(([x,y])=>({x:x*T+30,y:y*T+30}));
const S={gold:Math.round(budgetData.budget*.8),lives:24,wave:0,towers:[],enemies:[],shots:[],fx:[],build:'archer',active:false,left:0,timer:0,last:performance.now(),kills:0,breaches:0,spent:0,ended:false};
const available=Object.entries(DEFENCES).filter(([,d])=>d.era<=C.era&&(!d.faction||d.faction===C.faction));
$('battle-title').textContent=`ASSAULT ON ${target.name.toUpperCase()}`;$('region-name').textContent=target.name;$('wave').textContent=`0 / ${MAX_WAVES}`;
function refresh(){$('gold').textContent=Math.floor(S.gold);$('lives').textContent=S.lives;$('wave').textContent=`${S.wave} / ${MAX_WAVES}`;renderArsenal()}
function renderArsenal(){const el=$('arsenal-list');el.innerHTML='';available.forEach(([id,d])=>{const b=document.createElement('button');b.className=`tower-btn ${S.build===id?'active':''}`;b.disabled=S.gold<d.cost;b.innerHTML=`<b>${d.name}</b><span>${d.cost} GOLD</span>`;b.onclick=()=>{S.build=id;renderArsenal()};el.appendChild(b)})}
$('arsenal-toggle').onclick=()=>document.querySelector('.arsenal').classList.toggle('open');
function pos(e){const r=canvas.getBoundingClientRect();return{cx:Math.floor((e.clientX-r.left)*W/r.width/T),cy:Math.floor((e.clientY-r.top)*H/r.height/T)}}canvas.onclick=e=>{if(S.ended)return;const{cx,cy}=pos(e);if(routeSet.has(`${cx},${cy}`)||S.towers.some(t=>t.cx===cx&&t.cy===cy))return;const d=DEFENCES[S.build];if(!d||S.gold<d.cost)return;S.gold-=d.cost;S.spent+=d.cost;S.towers.push({type:S.build,cx,cy,x:cx*T+30,y:cy*T+30,damage:d.damage*2.1,range:d.range,cd:0});refresh()};
function enemyType(w,i){if(w<5)return i%5?'infantry':'runner';if(w<10)return i%6?'heavy':'runner';return i%5?'heavy':'siege'}function spawn(){const type=enemyType(S.wave,S.left),b=ENEMIES[type],scale=.48*(1+S.wave*.05+target.fortification*.0025);S.enemies.push({...b,type,hp:b.hp*scale,maxHp:b.hp*scale,speed:b.speed*(1+S.wave*.003),pi:0,x:path[0].x,y:path[0].y,bob:Math.random()*6.2})}
function startWave(){if(S.active||S.ended)return;S.wave++;S.active=true;S.left=4+Math.ceil(S.wave*1.15);S.timer=0;S.gold+=45+S.wave*5;$('start-wave').disabled=true;$('msg').textContent=`Wave ${S.wave}: defenders of ${target.name} are advancing.`;refresh()}
$('start-wave').onclick=startWave;
function hit(p){const ts=p.splash?S.enemies.filter(e=>Math.hypot(e.x-p.target.x,e.y-p.target.y)<p.splash):[p.target];ts.forEach(e=>{e.hp-=p.damage*(1-e.armor*(p.kind==='antiarmor'?.15:1));if(e.hp<=0){const i=S.enemies.indexOf(e);if(i>=0){S.enemies.splice(i,1);S.kills++;S.gold+=Math.round(e.reward*1.15)}}})}
function update(dt){if(S.ended)return;if(S.active&&S.left){S.timer-=dt;if(S.timer<=0){spawn();S.left--;S.timer=.82}}for(let i=S.enemies.length-1;i>=0;i--){const e=S.enemies[i],q=path[e.pi+1];e.bob+=dt*4;if(!q){S.enemies.splice(i,1);S.lives--;S.breaches++;if(S.lives<=0)return finish(false);continue}const dx=q.x-e.x,dy=q.y-e.y,d=Math.hypot(dx,dy),m=e.speed*dt;if(d<=m){e.x=q.x;e.y=q.y;e.pi++}else{e.x+=dx/d*m;e.y+=dy/d*m}}for(const t of S.towers){const d=DEFENCES[t.type];t.cd-=dt;if(t.cd>0)continue;let targetEnemy=null,best=-1;for(const e of S.enemies)if(Math.hypot(e.x-t.x,e.y-t.y)<=t.range&&e.pi>=best){targetEnemy=e;best=e.pi}if(targetEnemy){t.cd=1/d.rate;S.shots.push({x:t.x,y:t.y,target:targetEnemy,damage:t.damage,kind:d.kind,type:d.projectile,splash:d.splash||0})}}for(let i=S.shots.length-1;i>=0;i--){const p=S.shots[i];if(!S.enemies.includes(p.target)){S.shots.splice(i,1);continue}const dx=p.target.x-p.x,dy=p.target.y-p.y,d=Math.hypot(dx,dy),m=720*dt;if(d<m+8){hit(p);S.shots.splice(i,1)}else{p.x+=dx/d*m;p.y+=dy/d*m}}if(S.active&&!S.left&&!S.enemies.length){S.active=false;$('start-wave').disabled=false;if(S.wave>=MAX_WAVES)finish(true);else{$('msg').textContent=`Wave ${S.wave} cleared. Reinforce before the next assault.`;refresh()}}}
function finish(victory){if(S.ended)return;S.ended=true;const health=Math.max(0,S.lives/24),losses=Math.round((1-health)*65+S.breaches*2+S.wave*1.5),cost=Math.round(70+S.spent*.12);applyBattle(C,regionId,{victory,conquest:victory,attacker:target.owner,baseHealth:health,breaches:S.breaches,losses,cost});saveCampaign(C);$('result').classList.add('show');$('result-title').textContent=victory?`${target.name.toUpperCase()} CAPTURED`:'ASSAULT FAILED';$('result-text').textContent=victory?`After ${S.wave} waves, Ottoman forces secured ${target.name}. ${S.breaches} breaches and ${losses} campaign manpower losses have been recorded. The region enters occupation and reconstruction.`:`The assault collapsed after wave ${S.wave}. ${losses} manpower and ${cost} Treasury were lost. ${target.name} remains enemy territory.`;$('start-wave').disabled=true}
$('return-map').onclick=()=>location.href='campaign.html';$('retreat').onclick=()=>{if(!S.ended)finish(false);else location.href='campaign.html'};
function terrain(){const coastal=target.coastal,g=ctx.createLinearGradient(0,0,W,H);g.addColorStop(0,coastal?'#5e805d':'#6d8757');g.addColorStop(1,coastal?'#345f62':'#405f3e');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);if(coastal){ctx.fillStyle='#397688';ctx.fillRect(0,0,150,H);ctx.fillStyle='#d1bd84';ctx.fillRect(145,0,20,H)}for(let i=0;i<55;i++){const x=(i*173)%W,y=(i*97+41)%H,cx=Math.floor(x/T),cy=Math.floor(y/T);if(routeSet.has(`${cx},${cy}`))continue;ctx.fillStyle=i%4?'#345637':'#7d805d';ctx.beginPath();ctx.arc(x,y,3+i%5,0,7);ctx.fill()}ctx.lineCap='round';ctx.lineJoin='round';ctx.strokeStyle='#40342555';ctx.lineWidth=50;ctx.beginPath();path.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke();ctx.strokeStyle='#a99060';ctx.lineWidth=40;ctx.stroke();ctx.fillStyle='#6f5c49';ctx.fillRect(920,270,40,90);ctx.fillStyle='#dfbd6d';ctx.font='800 9px Inter';ctx.fillText(target.name.toUpperCase(),805,25)}
function tower(t){const d=DEFENCES[t.type];ctx.save();ctx.translate(t.x,t.y);ctx.fillStyle='#0004';ctx.beginPath();ctx.ellipse(3,15,20,7,0,0,7);ctx.fill();ctx.fillStyle=d.kind==='artillery'?'#4b513b':'#425b3d';ctx.beginPath();ctx.roundRect(-13,-11,26,27,5);ctx.fill();if(d.kind==='artillery'){ctx.strokeStyle='#252925';ctx.lineWidth=6;ctx.beginPath();ctx.moveTo(0,-2);ctx.lineTo(24,-15);ctx.stroke()}else{ctx.fillStyle='#eadac1';ctx.beginPath();ctx.arc(0,-12,6,0,7);ctx.fill()}ctx.restore()}
function enemy(e){ctx.save();ctx.translate(e.x,e.y+Math.sin(e.bob)*2);ctx.fillStyle='#0004';ctx.beginPath();ctx.ellipse(2,11,14,5,0,0,7);ctx.fill();ctx.fillStyle=e.color;ctx.beginPath();ctx.roundRect(-8,-5,16,20,5);ctx.fill();ctx.fillStyle='#d0b18f';ctx.beginPath();ctx.arc(0,-9,6,0,7);ctx.fill();ctx.fillStyle='#111b20';ctx.fillRect(-16,-24,32,4);ctx.fillStyle=e.hp/e.maxHp>.5?'#77d782':'#ff7868';ctx.fillRect(-15,-23,30*Math.max(0,e.hp/e.maxHp),2);ctx.restore()}
function draw(){terrain();S.towers.forEach(tower);S.enemies.forEach(enemy);S.shots.forEach(p=>{ctx.fillStyle='#ffe29a';ctx.beginPath();ctx.arc(p.x,p.y,p.type==='shell'?4:2.5,0,7);ctx.fill()})}
function loop(now){const dt=Math.min(.033,(now-S.last)/1000);S.last=now;update(dt);draw();requestAnimationFrame(loop)}refresh();requestAnimationFrame(loop);
