import {ERAS,FACTIONS,DEFENCES,TECHNOLOGIES,ENEMIES} from './data.js';

const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d');
const ui=Object.fromEntries(['era','gold','science','lives','wave','build-list','message','selected-info','upgrade','sell','start-wave','research-button','advance-era','faction','faction-desc','intel','tech-dialog','tech-tree','close-tech'].map(id=>[id,document.querySelector('#'+id)]));
const W=canvas.width,H=canvas.height,COLS=16,ROWS=10,TW=W/COLS,TH=H/ROWS;
const pathCells=[[0,5],[1,5],[2,5],[2,4],[3,4],[4,4],[5,4],[5,5],[5,6],[6,6],[7,6],[8,6],[8,5],[8,4],[9,4],[10,4],[11,4],[11,3],[12,3],[13,3],[13,4],[13,5],[14,5],[15,5]];
const pathSet=new Set(pathCells.map(([x,y])=>`${x},${y}`));
const path=pathCells.map(([x,y])=>({x:x*TW+TW/2,y:y*TH+TH/2}));
let state={gold:300,science:0,lives:20,wave:0,era:0,research:new Set(),towers:[],enemies:[],projectiles:[],selectedBuild:'archer',selectedTower:null,waveActive:false,spawnLeft:0,spawnTimer:0,last:performance.now(),faction:'british',gameOver:false};
let lastUiKey='';

function faction(){return FACTIONS[state.faction]}
function unlocked(d){return d.era<=state.era&&(!d.requires||state.research.has(d.requires))}
function price(d){return Math.round(d.cost*(d.kind==='artillery'?(faction().artilleryCost||1):1))}
function setMessage(m){ui.message.textContent=m}
function updateUI(force=false){
  ui.era.textContent=ERAS[state.era].name.toUpperCase();ui.gold.textContent=Math.floor(state.gold);ui.science.textContent=Math.floor(state.science);ui.lives.textContent=state.lives;ui.wave.textContent=`${state.wave} / 48`;ui['faction-desc'].textContent=faction().desc;
  const key=[state.era,state.faction,[...state.research].sort().join(','),state.selectedBuild,state.selectedTower?.cx,state.selectedTower?.cy,state.towers.length].join('|');
  if(force||key!==lastUiKey){lastUiKey=key;renderBuildList();renderSelected();}
  checkEra();
}
function renderBuildList(){ui['build-list'].innerHTML='';Object.entries(DEFENCES).forEach(([id,d])=>{const b=document.createElement('button');b.className=`build-card ${state.selectedBuild===id?'active':''} ${!unlocked(d)?'locked':''}`;b.disabled=!unlocked(d);b.innerHTML=`<div class="build-name">${d.name}</div><div class="build-meta">${price(d)} gold · ${ERAS[d.era].name}</div><div class="build-role">${d.role}</div>`;b.onclick=()=>{state.selectedBuild=id;state.selectedTower=null;lastUiKey='';updateUI(true);setMessage(`${d.name} selected. Choose a free tile.`)};ui['build-list'].appendChild(b)})}
function renderSelected(){const t=state.selectedTower;if(!t){ui['selected-info'].textContent='No defence selected.';ui.upgrade.disabled=true;ui.sell.disabled=true;return}const d=DEFENCES[t.type];ui['selected-info'].innerHTML=`<strong>${d.name}</strong><br>Level ${t.level}<br>Damage ${Math.round(t.damage)} · Range ${Math.round(t.range)}<br>${d.role}`;ui.upgrade.disabled=false;ui.sell.disabled=false}
function checkEra(){if(state.era>=ERAS.length-1){ui['advance-era'].disabled=true;return}const n=ERAS[state.era+1],okWave=state.wave>=n.start-1,okTech=n.required.every(x=>state.research.has(x)),okScience=state.science>=n.science;ui['advance-era'].disabled=!(okWave&&okTech&&okScience&&!state.waveActive);ui['advance-era'].textContent=`ADVANCE ERA · ${n.science} SCIENCE`;}
function cellAt(e){const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)*W/r.width,y=(e.clientY-r.top)*H/r.height;return {cx:Math.floor(x/TW),cy:Math.floor(y/TH)}}
canvas.onclick=e=>{if(state.gameOver)return;const {cx,cy}=cellAt(e);const existing=state.towers.find(t=>t.cx===cx&&t.cy===cy);if(existing){state.selectedTower=existing;state.selectedBuild=null;lastUiKey='';updateUI(true);return}if(pathSet.has(`${cx},${cy}`)){setMessage('The enemy route cannot be blocked.');return}if(!state.selectedBuild){setMessage('Select a defence from the left panel first.');return}const d=DEFENCES[state.selectedBuild],cost=price(d);if(!unlocked(d)||state.gold<cost){setMessage('Insufficient Gold or technology.');return}state.gold-=cost;state.towers.push({type:state.selectedBuild,cx,cy,x:cx*TW+TW/2,y:cy*TH+TH/2,level:1,damage:d.damage,range:d.range*faction().range,cooldown:0});lastUiKey='';updateUI(true)};

function waveEnemyType(w,i){if(w<4)return i%4===0?'runner':'infantry';if(w<9)return i%5===0?'heavy':i%3===0?'runner':'infantry';if(w<17)return i%5===0?'siege':i%3===0?'heavy':'infantry';if(w<29)return i%4===0?'vehicle':i%5===0?'siege':'heavy';return i%4===0?'tank':i%3===0?'vehicle':'heavy'}
function spawnEnemy(){const type=waveEnemyType(state.wave,state.spawnLeft),base=ENEMIES[type],scale=1+state.wave*.095;state.enemies.push({...base,type,hp:base.hp*scale,maxHp:base.hp*scale,speed:base.speed*(1+state.wave*.008),pathIndex:0,x:path[0].x,y:path[0].y});}
function startWave(){if(state.waveActive||state.gameOver||state.wave>=48)return;state.wave++;state.waveActive=true;state.spawnLeft=7+state.wave*2;state.spawnTimer=0;const bonus=state.research.has('commerce')?15:0;state.gold+=Math.round((35+state.wave*3+bonus)*faction().income);ui['start-wave'].disabled=true;ui.intel.textContent=`Wave ${state.wave}: ${state.wave<4?'Light infantry formations':state.wave<9?'Armored troops mixed with fast units':state.wave<17?'Siege formations':state.wave<29?'Industrial vehicles and heavy troops':'Heavy armored formations'} approaching.`;updateUI()}
function endWaveIfDone(){if(state.waveActive&&state.spawnLeft<=0&&state.enemies.length===0){state.waveActive=false;ui['start-wave'].disabled=false;setMessage(`Wave ${state.wave} defeated. Reorganize your defence.`);if(state.wave===48){state.gameOver=true;setMessage('VICTORY — your civilization survived the centuries.')}updateUI()}}

function update(dt){if(state.gameOver)return;if(state.waveActive&&state.spawnLeft>0){state.spawnTimer-=dt;if(state.spawnTimer<=0){spawnEnemy();state.spawnLeft--;state.spawnTimer=.62}}
 for(let i=state.enemies.length-1;i>=0;i--){const e=state.enemies[i],target=path[e.pathIndex+1];if(!target){state.enemies.splice(i,1);state.lives--;if(state.lives<=0){state.gameOver=true;setMessage('DEFEAT — the defensive line has collapsed.')}continue}const dx=target.x-e.x,dy=target.y-e.y,dist=Math.hypot(dx,dy),move=e.speed*dt;if(dist<=move){e.x=target.x;e.y=target.y;e.pathIndex++}else{e.x+=dx/dist*move;e.y+=dy/dist*move}}
 for(const t of state.towers){const d=DEFENCES[t.type];t.cooldown-=dt;if(t.cooldown>0)continue;let target=null,best=-1;for(const e of state.enemies){const dist=Math.hypot(e.x-t.x,e.y-t.y);if(dist<=t.range&&e.pathIndex>best){target=e;best=e.pathIndex}}if(target){let rate=d.rate*(d.kind==='infantry'?faction().fireRate:1);t.cooldown=1/rate;state.projectiles.push({x:t.x,y:t.y,target,damage:t.damage,kind:d.kind,splash:d.splash||0,type:d.projectile,life:1})}}
 for(let i=state.projectiles.length-1;i>=0;i--){const p=state.projectiles[i];if(!state.enemies.includes(p.target)){state.projectiles.splice(i,1);continue}const dx=p.target.x-p.x,dy=p.target.y-p.y,dist=Math.hypot(dx,dy),speed=p.type==='missile'?430:650,move=speed*dt;if(dist<move+8){hit(p);state.projectiles.splice(i,1)}else{p.x+=dx/dist*move;p.y+=dy/dist*move}}
 endWaveIfDone();updateUI();}
function hit(p){const targets=p.splash?state.enemies.filter(e=>Math.hypot(e.x-p.target.x,e.y-p.target.y)<=p.splash):[p.target];for(const e of targets){let armor=e.armor;let dmg=p.damage*(faction().damage||1);if(p.kind==='antiarmor')armor*=.15;if(p.kind==='artillery')dmg*=faction().artilleryDamage||1;e.hp-=dmg*(1-armor);if(e.hp<=0){const idx=state.enemies.indexOf(e);if(idx>=0){state.enemies.splice(idx,1);state.gold+=Math.round(e.reward*(state.research.has('logistics')?1.1:1));state.science+=Math.round(e.science*(state.research.has('academies')?1.2:1))}}}}

function draw(){ctx.clearRect(0,0,W,H);const era=state.era;const ground=['#66734e','#68704b','#706a45','#65614d','#575746','#4e5548'][era];ctx.fillStyle=ground;ctx.fillRect(0,0,W,H);for(let y=0;y<ROWS;y++)for(let x=0;x<COLS;x++){ctx.strokeStyle='#ffffff10';ctx.strokeRect(x*TW,y*TH,TW,TH);if((x*7+y*11)%13===0&&!pathSet.has(`${x},${y}`)){ctx.fillStyle=era<3?'#48573b':'#4b493e';ctx.beginPath();ctx.arc(x*TW+15,y*TH+17,era<3?8:5,0,7);ctx.fill()}}
 ctx.lineCap='round';ctx.lineJoin='round';ctx.strokeStyle=era<2?'#8c7857':era<4?'#776b58':'#66645d';ctx.lineWidth=TH*.62;ctx.beginPath();path.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke();ctx.strokeStyle='#b5a27b55';ctx.lineWidth=2;ctx.stroke();
 for(const t of state.towers)drawTower(t);for(const e of state.enemies)drawEnemy(e);for(const p of state.projectiles){ctx.fillStyle=p.type==='missile'?'#e4d4a0':'#e0c47b';ctx.beginPath();ctx.arc(p.x,p.y,p.type==='shell'?4:2.2,0,7);ctx.fill()}if(state.selectedTower){ctx.strokeStyle='#e0c77a';ctx.lineWidth=2;ctx.beginPath();ctx.arc(state.selectedTower.x,state.selectedTower.y,state.selectedTower.range,0,7);ctx.stroke()}}
function drawTower(t){const d=DEFENCES[t.type];ctx.save();ctx.translate(t.x,t.y);ctx.fillStyle='#0005';ctx.beginPath();ctx.ellipse(4,13,20,9,0,0,7);ctx.fill();if(d.kind==='artillery'||d.kind==='antiarmor'){ctx.fillStyle=d.kind==='antiarmor'?'#3c4638':'#554d3b';ctx.fillRect(-15,-8,30,20);ctx.strokeStyle='#222';ctx.lineWidth=6;ctx.beginPath();ctx.moveTo(0,-2);ctx.lineTo(24,-15);ctx.stroke()}else{ctx.fillStyle=t.type==='tower'?'#5d4631':'#3f4936';ctx.fillRect(-12,-13,24,27);ctx.fillStyle='#282820';ctx.beginPath();ctx.arc(0,-14,8,0,7);ctx.fill();ctx.strokeStyle='#2c241b';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(0,-7);ctx.lineTo(15,-16);ctx.stroke()}ctx.fillStyle='#d6bd78';ctx.font='bold 8px Inter';ctx.textAlign='center';ctx.fillText(`L${t.level}`,0,27);ctx.restore()}
function drawEnemy(e){ctx.save();ctx.translate(e.x,e.y);ctx.fillStyle='#0005';ctx.beginPath();ctx.ellipse(3,9,13,6,0,0,7);ctx.fill();ctx.fillStyle=e.color;if(e.type==='tank'||e.type==='vehicle'){ctx.fillRect(-15,-9,30,18);ctx.fillStyle='#252a23';ctx.fillRect(-7,-13,14,8);ctx.fillRect(0,-11,20,3)}else if(e.type==='siege'){ctx.fillRect(-13,-9,26,17);ctx.strokeStyle='#29251e';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(0,-4);ctx.lineTo(18,-17);ctx.stroke()}else{ctx.beginPath();ctx.arc(0,-5,9,0,7);ctx.fill();ctx.fillRect(-7,1,14,14)}ctx.fillStyle='#1a1814';ctx.fillRect(-17,-22,34,4);ctx.fillStyle=e.hp/e.maxHp>.45?'#738b58':'#a65a49';ctx.fillRect(-17,-22,34*Math.max(0,e.hp/e.maxHp),4);ctx.restore()}

ui['start-wave'].onclick=startWave;ui.faction.onchange=()=>{state.faction=ui.faction.value;state.towers.forEach(t=>t.range=DEFENCES[t.type].range*faction().range);lastUiKey='';updateUI(true)};ui.upgrade.onclick=()=>{const t=state.selectedTower;if(!t)return;const cost=Math.round((55+t.level*45)*(faction().upgradeCost||1));if(state.gold<cost){setMessage(`Upgrade requires ${cost} Gold.`);return}state.gold-=cost;t.level++;t.damage*=1.32;t.range*=1.05;lastUiKey='';updateUI(true)};ui.sell.onclick=()=>{const t=state.selectedTower;if(!t)return;state.gold+=Math.round(price(DEFENCES[t.type])*.55);state.towers=state.towers.filter(x=>x!==t);state.selectedTower=null;lastUiKey='';updateUI(true)};
ui['research-button'].onclick=()=>{renderTech();ui['tech-dialog'].showModal()};ui['close-tech'].onclick=()=>ui['tech-dialog'].close();
function renderTech(){ui['tech-tree'].innerHTML='';for(const branch of ['Infantry','Engineering','Statecraft']){const col=document.createElement('section');col.className='tech-column';col.innerHTML=`<h3>${branch}</h3>`;TECHNOLOGIES.filter(t=>t.branch===branch).forEach(t=>{const done=state.research.has(t.id),req=t.requires.every(r=>state.research.has(r)),card=document.createElement('div');card.className=`tech-card ${done?'researched':req?'available':''}`;card.innerHTML=`<h4>${t.name}</h4><p>${t.effect}</p><div class="tech-cost">${done?'RESEARCHED':`${t.cost} SCIENCE${!req?' · Requires '+t.requires.join(', '):''}`}</div>`;if(!done){const b=document.createElement('button');b.textContent=req?'RESEARCH':'LOCKED';b.disabled=!req||state.science<t.cost;b.onclick=()=>{state.science-=t.cost;state.research.add(t.id);lastUiKey='';renderTech();updateUI(true)};card.appendChild(b)}col.appendChild(card)});ui['tech-tree'].appendChild(col)}}
ui['advance-era'].onclick=()=>{const n=ERAS[state.era+1];if(!n)return;state.science-=n.science;state.era++;lastUiKey='';setMessage(`A new age begins: ${ERAS[state.era].name}. Existing positions remain on the battlefield.`);updateUI(true)};

function loop(now){const dt=Math.min(.033,(now-state.last)/1000);state.last=now;update(dt);draw();requestAnimationFrame(loop)}updateUI(true);requestAnimationFrame(loop);
