import{ERAS,MAPS,DIFFICULTIES,ARSENAL,RESEARCH,loadProfile,saveProfile,refreshUnlocks,eraStatus,completedMaps,earnedMedals,newProfile}from'./ottoman-data.js';
const $=id=>document.getElementById(id);let P=loadProfile();refreshUnlocks(P);saveProfile(P);let screen='home',researchBranch='Warfare',researchEra=P.era,selectedTech=null,arsenalFilter='All',selectedTower=null;
const branches=['Warfare','Engineering','Artillery','Economy','Command'];const filters=['All','Infantry','Siege','Support','Advanced'];
function toast(t){const e=$('toast');e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),2800)}
function resourcesHTML(){return`<div class="resource"><span>COINS</span><b>${P.coins.toLocaleString()}</b></div><div class="resource science"><span>SCIENCE</span><b>${P.science.toLocaleString()}</b></div><div class="resource medals"><span>MEDALS</span><b>${earnedMedals(P)}</b></div>`}
function setScreen(v){screen=v;document.querySelectorAll('.screen').forEach(s=>s.classList.toggle('active',s.id===`${v}-screen`));if(v==='home')renderHome();if(v==='maps')renderMaps();if(v==='research')renderResearch();if(v==='arsenal')renderArsenal()}
function renderEraTrack(target){target.innerHTML=ERAS.map((e,i)=>`<div class="era-step ${i===P.era?'active':''} ${i>P.era?'locked':''}"><i>${['▥','◈','◉','⚙','★'][i]}</i><span>${e.name.toUpperCase()}</span></div>`).join('')}
function renderHome(){refreshUnlocks(P);$('home-resources').innerHTML=resourcesHTML();$('profile-progress').textContent=`${completedMaps(P)} maps conquered · ${earnedMedals(P)} medals`;$('home-maps').textContent=`${completedMaps(P)} / ${MAPS.length}`;$('home-medals').textContent=earnedMedals(P);renderEraTrack($('home-era-strip'));const s=eraStatus(P);$('next-reward').innerHTML=s?`<b>NEXT ERA · ${s.next.name.toUpperCase()}</b><span>${s.maps}/${s.next.maps} maps · ${s.medals}/${s.next.medals} medals · ${s.science}/${s.next.science} science earned</span>${s.ready?`<button id="home-advance">ENTER ${s.next.name.toUpperCase()}</button>`:''}`:`<b>MODERN ERA</b><span>All historical eras unlocked.</span>`;if($('home-advance'))$('home-advance').onclick=()=>{P.era++;refreshUnlocks(P);saveProfile(P);toast(`${s.next.name} Era unlocked.`);renderHome()}}
function mapAvailable(m){return P.unlockedMaps.includes(m.id)&&m.era<=P.era}
function renderMaps(){refreshUnlocks(P);$('maps-resources').innerHTML=resourcesHTML();$('map-era-tabs').innerHTML=ERAS.map((e,i)=>`<button class="${i===P.era?'active':''} ${i>P.era?'locked':''}" ${i>P.era?'disabled':''}>${e.name.toUpperCase()}</button>`).join('');const root=$('map-grid');root.innerHTML='';MAPS.forEach((m,i)=>{const results=P.mapResults[m.id]||{},unlocked=mapAvailable(m),card=document.createElement('article');card.className=`level-card ${unlocked?'':'locked'}`;const earned=Object.values(results).filter(Boolean).length;card.innerHTML=`<div class="level-number">${i+1}</div><div class="level-art art-${i%5}"><span>${unlocked?'':'🔒'}</span></div><h3>${m.name}</h3><small>${m.region} · ${ERAS[m.era].name}</small><div class="stars">${[0,1,2].map(x=>`<i class="${x<earned?'earned':''}">★</i>`).join('')}</div><div class="difficulty-row">${Object.entries(DIFFICULTIES).slice(0,3).map(([id,d])=>`<button data-diff="${id}" ${unlocked?'':'disabled'} class="${results[id]?'done':''}">${d.name}</button>`).join('')}</div>`;card.querySelectorAll('[data-diff]').forEach(b=>b.onclick=()=>launchMap(m,b.dataset.diff));root.appendChild(card)})}
function launchMap(m,diff){if(!mapAvailable(m))return toast('Complete earlier maps and unlock the required era first.');saveProfile(P);location.href=`ottoman-battle.html?v=2&map=${encodeURIComponent(m.id)}&difficulty=${encodeURIComponent(diff)}`}
function techDone(t){return P.research.includes(t.id)}
function techLocked(t){return t.era>P.era}
function renderResearch(){refreshUnlocks(P);$('research-resources').innerHTML=resourcesHTML();$('research-cats').innerHTML=branches.map(b=>{const total=RESEARCH.filter(t=>t.branch===b).length,done=RESEARCH.filter(t=>t.branch===b&&techDone(t)).length;return`<button data-branch="${b}" class="${b===researchBranch?'active':''}"><b>${b.toUpperCase()}</b><span>${done} / ${total}</span></button>`}).join('');document.querySelectorAll('[data-branch]').forEach(b=>b.onclick=()=>{researchBranch=b.dataset.branch;selectedTech=null;renderResearch()});$('research-era-tabs').innerHTML=ERAS.map((e,i)=>`<button data-era="${i}" class="${i===researchEra?'active':''} ${i>P.era?'locked':''}" ${i>P.era?'disabled':''}>${e.name.toUpperCase()}</button>`).join('');document.querySelectorAll('[data-era]').forEach(b=>b.onclick=()=>{researchEra=Number(b.dataset.era);selectedTech=null;renderResearch()});const list=RESEARCH.filter(t=>t.branch===researchBranch&&t.era===researchEra);$('research-tree').innerHTML=list.length?list.map((t,i)=>`<button class="research-node ${techDone(t)?'done':''} ${techLocked(t)?'locked':''}" data-tech="${t.id}"><i>${['⚔','◈','⚙','✦','☼'][branches.indexOf(t.branch)]}</i><b>${t.name}</b><span>${techDone(t)?'UNLOCKED':`${t.cost} SCIENCE`}</span></button>`).join(''):`<div class="empty-state">No ${researchBranch.toLowerCase()} research in this era yet.</div>`;document.querySelectorAll('[data-tech]').forEach(n=>n.onclick=()=>{selectedTech=RESEARCH.find(t=>t.id===n.dataset.tech);renderResearchDetail()});if(!selectedTech)selectedTech=list.find(t=>!techDone(t))||list[0]||null;renderResearchDetail()}
function renderResearchDetail(){const t=selectedTech;if(!t){$('research-detail').innerHTML='<h3>SELECT RESEARCH</h3><p>Choose a node to inspect its permanent benefit.</p>';return}const done=techDone(t),locked=techLocked(t),can=!done&&!locked&&P.science>=t.cost;$('research-detail').innerHTML=`<div class="detail-emblem">${done?'✓':'✦'}</div><h2>${t.name}</h2><p>${t.effect}</p><div class="detail-row"><span>ERA</span><b>${ERAS[t.era].name}</b></div><div class="detail-row"><span>COST</span><b>${t.cost} SCIENCE</b></div><button id="buy-tech" ${can?'':'disabled'}>${done?'UNLOCKED':locked?'LATER ERA':P.science<t.cost?'NOT ENOUGH SCIENCE':'RESEARCH'}</button>`;if(can)$('buy-tech').onclick=()=>{P.science-=t.cost;P.research.push(t.id);saveProfile(P);toast(`${t.name} permanently unlocked.`);renderResearch()}}
function arsenalUnlocked(id,d){return d.era<=P.era&&(!d.requires||P.research.includes(d.requires))}
function towerFilter(d){if(arsenalFilter==='All')return true;if(arsenalFilter==='Infantry')return d.kind==='infantry';if(arsenalFilter==='Siege')return d.kind==='artillery';if(arsenalFilter==='Advanced')return d.kind==='antiarmor'||d.era>=4;return d.kind!=='artillery'&&d.kind!=='infantry'}
function renderArsenal(){refreshUnlocks(P);$('arsenal-resources').innerHTML=resourcesHTML();const entries=Object.entries(ARSENAL),unlockedCount=entries.filter(([id,d])=>arsenalUnlocked(id,d)).length,totalMastery=Object.values(P.mastery||{}).reduce((a,b)=>a+b,0);$('roster-count').textContent=`ROSTER ${unlockedCount} / ${entries.length}`;$('mastery-total').textContent=totalMastery;$('arsenal-tabs').innerHTML=filters.map(f=>`<button data-filter="${f}" class="${f===arsenalFilter?'active':''}">${f.toUpperCase()}</button>`).join('');document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{arsenalFilter=b.dataset.filter;selectedTower=null;renderArsenal()});const root=$('arsenal-grid');root.innerHTML='';entries.filter(([,d])=>towerFilter(d)).forEach(([id,d])=>{const unlocked=arsenalUnlocked(id,d),xp=P.mastery[id]||0,card=document.createElement('button');card.className=`tower-card ${unlocked?'':'locked'} ${selectedTower===id?'active':''}`;card.dataset.tower=id;card.innerHTML=`<div class="tower-art kind-${d.kind}"><span>${d.kind==='artillery'?'●':d.kind==='antiarmor'?'⌖':'♜'}</span></div><b>${d.name}</b><small>${ERAS[d.era].name}</small><div class="mastery"><i style="width:${Math.min(100,xp)}%"></i></div><em>${unlocked?`Mastery ${xp}`:'LOCKED'}</em>`;card.onclick=()=>{selectedTower=id;renderArsenal()};root.appendChild(card)});if(!selectedTower){const first=entries.find(([id,d])=>towerFilter(d));selectedTower=first?.[0]||null}renderArsenalDetail()}
function renderArsenalDetail(){const d=ARSENAL[selectedTower];if(!d){$('arsenal-detail').innerHTML='';return}const unlocked=arsenalUnlocked(selectedTower,d),xp=P.mastery[selectedTower]||0;$('arsenal-detail').innerHTML=`<div class="detail-tower kind-${d.kind}">${d.kind==='artillery'?'●':d.kind==='antiarmor'?'⌖':'♜'}</div><h2>${d.name}</h2><p>${d.role}</p><div class="detail-row"><span>ERA</span><b>${ERAS[d.era].name}</b></div><div class="detail-row"><span>STATUS</span><b>${unlocked?'AVAILABLE':'LOCKED'}</b></div><h3>UPGRADE PATH</h3><div class="upgrade-preview"><div><b>I</b><span>Base defence</span></div><div><b>II</b><span>Specialise</span></div><div><b>III</b><span>Elite form</span></div></div><div class="detail-row"><span>MASTERY</span><b>${xp}</b></div>`}
document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{const v=b.dataset.go;if(v==='settings'||v==='profile')return toast(`${v[0].toUpperCase()+v.slice(1)} screen comes next.`);setScreen(v)});$('main-play').onclick=()=>setScreen('maps');$('reset').onclick=()=>{if(!confirm('Reset Ottoman progression on this device?'))return;P=newProfile();refreshUnlocks(P);saveProfile(P);toast('New Ottoman profile created.');setScreen('home')};setScreen('home');