import{ERAS,MAPS,DIFFICULTIES,ARSENAL,RESEARCH,loadProfile,saveProfile,refreshUnlocks,eraStatus,completedMaps,earnedMedals,newProfile}from'./ottoman-data.js';
const $=id=>document.getElementById(id);let P=loadProfile(),selectedDifficulty='recruit',view='play';refreshUnlocks(P);saveProfile(P);
function toast(t){const e=$('toast');e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),3000)}
function renderResources(){$('resources').innerHTML=`<div class="resource"><span>SCIENCE</span><b>${P.science.toLocaleString()}</b></div><div class="resource"><span>MEDALS</span><b>${earnedMedals(P)}</b></div><div class="resource"><span>COINS</span><b>${P.coins.toLocaleString()}</b></div>`}
function renderEraStrip(){$('era-strip').innerHTML=ERAS.map((e,i)=>`<span class="era-pill ${i===P.era?'active':''} ${i>P.era?'locked':''}">${e.name.toUpperCase()}</span>`).join('');const s=eraStatus(P);$('era-gate').innerHTML=s?`<b>NEXT ERA · ${s.next.name.toUpperCase()}</b><br>Maps ${s.maps}/${s.next.maps} · Medals ${s.medals}/${s.next.medals}<br>Science earned ${s.science}/${s.next.science}<button id="advance-era" ${s.ready?'':'disabled'}>ENTER ${s.next.name.toUpperCase()}</button>`:`<b>MODERN ERA</b><br>All historical eras unlocked.`;if(s){$('advance-era').onclick=()=>{if(!s.ready)return;P.era++;refreshUnlocks(P);saveProfile(P);toast(`${s.next.name} Era unlocked.`);render()}}}
function mapAvailable(m){return P.unlockedMaps.includes(m.id)&&m.era<=P.era}
function renderMaps(){const root=$('map-scroll');root.innerHTML='';MAPS.forEach((m,i)=>{const unlocked=mapAvailable(m),results=P.mapResults[m.id]||{},card=document.createElement('article');card.className=`map-card ${unlocked?'':'locked'} ${i===0?'active':''}`;const medals=Object.keys(DIFFICULTIES).map(d=>`<span class="medal ${results[d]?'earned':''}">★</span>`).join('');card.innerHTML=`<div class="map-art"></div><h3>${m.name}</h3><div class="region">${m.region} · ${ERAS[m.era].name}</div><p class="desc">${m.desc}</p><div class="medals">${medals}</div><div class="play-row">${Object.entries(DIFFICULTIES).slice(0,2).map(([id,d])=>`<button data-diff="${id}" class="${selectedDifficulty===id?'selected':''}" ${unlocked?'':'disabled'}>${d.name}</button>`).join('')}</div>`;card.querySelectorAll('[data-diff]').forEach(b=>b.onclick=()=>{selectedDifficulty=b.dataset.diff;launchMap(m)});root.appendChild(card)})}
function launchMap(m){if(!mapAvailable(m))return toast('Complete earlier maps and unlock the required era first.');saveProfile(P);location.href=`ottoman-battle.html?v=1&map=${encodeURIComponent(m.id)}&difficulty=${encodeURIComponent(selectedDifficulty)}`}
function renderResearch(){const root=$('research-grid');root.innerHTML='';const branches=['Warfare','Engineering','Economy','Command','Artillery'];branches.forEach(branch=>{const wrap=document.createElement('section');wrap.className='branch';wrap.innerHTML=`<h3>${branch.toUpperCase()}</h3>`;RESEARCH.filter(t=>t.branch===branch).forEach(t=>{const done=P.research.includes(t.id),locked=t.era>P.era,node=document.createElement('div');node.className=`tech ${done?'done':''} ${locked?'locked':''}`;node.innerHTML=`<b>${done?'✓ ':''}${t.name}</b><span>${t.effect}</span><span>${ERAS[t.era].name} · ${t.cost} Science</span><button ${done||locked||P.science<t.cost?'disabled':''}>${done?'UNLOCKED':'RESEARCH'}</button>`;node.querySelector('button').onclick=()=>{if(done||locked||P.science<t.cost)return;P.science-=t.cost;P.research.push(t.id);saveProfile(P);toast(`${t.name} permanently unlocked.`);render()};wrap.appendChild(node)});root.appendChild(wrap)})}
function arsenalUnlocked(id,d){return d.era<=P.era&&(!d.requires||P.research.includes(d.requires))}
function renderArsenal(){const root=$('arsenal-grid');root.innerHTML='';Object.entries(ARSENAL).forEach(([id,d])=>{const unlocked=arsenalUnlocked(id,d),xp=P.mastery[id]||0,card=document.createElement('article');card.className=`arsenal-card ${unlocked?'':'locked'}`;const icon=d.kind==='artillery'?'💥':d.kind==='antiarmor'?'🎯':'⚔';card.innerHTML=`<div class="arsenal-icon">${icon}</div><h3>${d.name}</h3><span>${ERAS[d.era].name} · ${d.role}</span><div class="mastery"><i style="width:${Math.min(100,xp/10)}%"></i></div><span>Mastery ${xp}</span>`;root.appendChild(card)})}
function setView(v){view=v;document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));$('play-view').style.display=v==='play'?'flex':'none';$('research-overlay').classList.toggle('show',v==='research');$('arsenal-overlay').classList.toggle('show',v==='arsenal');if(v==='research')renderResearch();if(v==='arsenal')renderArsenal()}
function render(){refreshUnlocks(P);renderResources();renderEraStrip();renderMaps();renderResearch();renderArsenal();$('profile-progress').textContent=`${completedMaps(P)} maps conquered · ${earnedMedals(P)} medals`;saveProfile(P)}
document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>setView(b.dataset.view));$('research-close').onclick=()=>setView('play');$('arsenal-close').onclick=()=>setView('play');$('reset').onclick=()=>{if(!confirm('Reset Ottoman progression on this device?'))return;P=newProfile();saveProfile(P);render();setView('play');toast('New Ottoman profile created.')};render();setView('play');
