import{MAPS,DIFFICULTIES,ARSENAL,loadProfile,saveProfile,refreshUnlocks}from'./ottoman-data.js';
const $=id=>document.getElementById(id),canvas=$('battle'),ctx=canvas.getContext('2d'),W=960,H=600,params=new URLSearchParams(location.search),mapId=params.get('map')||'constantinople',difficultyId=params.get('difficulty')||'recruit',P=loadProfile(),M=MAPS.find(x=>x.id===mapId)||MAPS[0],D=DIFFICULTIES[difficultyId]||DIFFICULTIES.recruit;
const path=[[0,330],[100,330],[165,280],[255,280],[320,365],[420,365],[500,300],[590,300],[665,235],[760,235],[840,285],[960,285]].map(([x,y])=>({x,y}));
const available=Object.entries(ARSENAL).filter(([id,d])=>d.era<=P.era&&(!d.requires||P.research.includes(d.requires)));let selectedBuild=available[0]?.[0]||'watchtower';
const S={gold:D.startGold+(P.research.includes('fieldcraft')?80:0)+(P.research.includes('supply-officers')?120:0)+(P.research.includes('logistics')?180:0),lives:20,wave:0,active:false,left:0,timer:0,towers:[],enemies:[],shots:[],fx:[],selected:null,ended:false,last:performance.now(),spent:0,kills:0,breaches:0};
$('battle-name').textContent=M.name.toUpperCase();$('mode').textContent=D.name.toUpperCase();
function segDist(px,py,a,b){const dx=b.x-a.x,dy=b.y-a.y,l=dx*dx+dy*dy||1,t=Math.max(0,Math.min(1,((px-a.x)*dx+(py-a.y)*dy)/l));return Math.hypot(px-(a.x+t*dx),py-(a.y+t*dy))}
function world(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*W/r.width,y:(e.clientY-r.top)*H/r.height}}
function valid(x,y){return x>38&&x<W-38&&y>42&&y<H-42&&!path.slice(0,-1).some((p,i)=>segDist(x,y,p,path[i+1])<48)&&!S.towers.some(t=>Math.hypot(t.x-x,t.y-y)<54)}
function refresh(){$('wave').textContent=`${S.wave}/${D.waves}`;$('lives').textContent=S.lives;$('gold').textContent=Math.floor(S.gold);renderArsenal();renderTower()}
function renderArsenal(){const root=$('arsenal-list');root.innerHTML='';available.forEach(([id,d])=>{const b=document.createElement('button');b.className=`tower-btn ${selectedBuild===id?'selected':''} ${S.gold<d.cost?'locked':''}`;b.innerHTML=`<b>${d.name}</b><span>${d.cost} GOLD</span><em>${d.role}</em>`;b.onclick=()=>{selectedBuild=id;S.selected=null;refresh();$('mission').textContent=`${d.name} selected — tap open ground to deploy.`};root.appendChild(b)})}
function place(id,x,y){const d=ARSENAL[id];if(!d||S.gold<d.cost||!valid(x,y))return;S.gold-=d.cost;S.spent+=d.cost;S.towers.push({type:id,x,y,tier:1,branch:null,damage:d.damage,range:d.range,rate:d.rate,splash:d.splash||0,cd:0,spent:d.cost});burst(x,y,10);P.mastery[id]=(P.mastery[id]||0)+1;refresh()}
canvas.addEventListener('click',e=>{if(S.ended)return;const p=world(e),near=S.towers.find(t=>Math.hypot(t.x-p.x,t.y-p.y)<34);if(near){S.selected=near;renderTower();return}place(selectedBuild,p.x,p.y)});
function renderTower(){const p=$('tower-panel');if(!S.selected){p.classList.remove('show');return}const t=S.selected,d=ARSENAL[t.type];p.classList.add('show');$('tower-info').innerHTML=`<h3>${d.name}</h3><div class="sub">Tier ${t.tier} · Damage ${Math.round(t.damage)} · Range ${Math.round(t.range)} · Rate ${t.rate.toFixed(2)}/s</div>`;const opts=t.tier===1?[{id:'power',name:'Heavy Training',cost:.75,damage:1.35,range:1.05},{id:'speed',name:'Rapid Drill',cost:.7,rate:1.32,range:1.08}]:t.tier===2?[{id:'elite',name:t.branch==='power'?'Elite Battery':'Veteran Crew',cost:1.15,damage:1.38,rate:1.18,range:1.12}]:[];$('upgrades').innerHTML=opts.length?`<div class="upgrade-grid">${opts.map((o,i)=>`<button data-i="${i}"><b>${o.name}</b><span>Permanent battlefield specialization</span><strong>${Math.round(d.cost*o.cost)} GOLD</strong></button>`).join('')}</div>`:'<div class="sub">Maximum tier reached.</div>';[...$('upgrades').querySelectorAll('button')].forEach((b,i)=>b.onclick=()=>upgrade(opts[i]));}
function upgrade(o){const t=S.selected,d=ARSENAL[t.type],cost=Math.round(d.cost*o.cost);if(S.gold<cost)return;S.gold-=cost;t.spent+=cost;t.tier++;if(t.tier===2)t.branch=o.id;t.damage*=o.damage||1;t.range*=o.range||1;t.rate*=o.rate||1;burst(t.x,t.y,14);refresh()}
$('sell').onclick=()=>{if(!S.selected)return;S.gold+=Math.round(S.selected.spent*.6);S.towers.splice(S.towers.indexOf(S.selected),1);S.selected=null;refresh()};$('tower-close').onclick=()=>{S.selected=null;renderTower()};$('arsenal-toggle').onclick=()=>document.querySelector('.arsenal').classList.toggle('open');
function enemyType(){if(P.era>=4&&S.wave>12)return Math.random()<.25?'tank':'heavy';if(P.era>=3&&S.wave>10)return Math.random()<.2?'vehicle':'heavy';return S.wave>8&&Math.random()<.25?'heavy':Math.random()<.22?'runner':'infantry'}
const enemyBase={infantry:{hp:90,speed:42,reward:14,armor:0},runner:{hp:65,speed:68,reward:16,armor:0},heavy:{hp:210,speed:33,reward:24,armor:.15},vehicle:{hp:720,speed:46,reward:48,armor:.38},tank:{hp:1600,speed:28,reward:78,armor:.55}};
function spawn(){const type=enemyType(),b=enemyBase[type],scale=D.hp*(1+S.wave*.045);S.enemies.push({type,hp:b.hp*scale,maxHp:b.hp*scale,speed:b.speed*D.speed,reward:b.reward,armor:b.armor,pi:0,x:path[0].x,y:path[0].y,bob:Math.random()*6})}
$('start-wave').onclick=()=>{if(S.active||S.ended)return;S.wave++;S.left=4+Math.ceil(S.wave*1.08);S.timer=0;S.active=true;$('start-wave').disabled=true;$('mission').textContent=`Wave ${S.wave}: enemy formations approaching.`;refresh()};
function burst(x,y,n){for(let i=0;i<n;i++)S.fx.push({x,y,vx:(Math.random()-.5)*110,vy:(Math.random()-.65)*95,life:.5,r:2+Math.random()*4})}
function update(dt){if(S.ended)return;if(S.active&&S.left){S.timer-=dt;if(S.timer<=0){spawn();S.left--;S.timer=.78}}for(let i=S.enemies.length-1;i>=0;i--){const e=S.enemies[i],q=path[e.pi+1];e.bob+=dt*4;if(!q){S.enemies.splice(i,1);S.lives--;S.breaches++;if(S.lives<=0)return finish(false);continue}const dx=q.x-e.x,dy=q.y-e.y,dist=Math.hypot(dx,dy),m=e.speed*dt;if(dist<=m){e.x=q.x;e.y=q.y;e.pi++}else{e.x+=dx/dist*m;e.y+=dy/dist*m}}
for(const t of S.towers){const d=ARSENAL[t.type];t.cd-=dt;if(t.cd>0)continue;let target=null,best=-1;for(const e of S.enemies)if(Math.hypot(e.x-t.x,e.y-t.y)<=t.range&&e.pi>=best){target=e;best=e.pi}if(target){t.cd=1/t.rate;S.shots.push({x:t.x,y:t.y,target,damage:t.damage*(t.type==='bombard'?1.1:1),splash:t.splash,kind:d.kind})}}
for(let i=S.shots.length-1;i>=0;i--){const p=S.shots[i];if(!S.enemies.includes(p.target)){S.shots.splice(i,1);continue}const dx=p.target.x-p.x,dy=p.target.y-p.y,dist=Math.hypot(dx,dy),m=720*dt;if(dist<m+8){const targets=p.splash?S.enemies.filter(e=>Math.hypot(e.x-p.target.x,e.y-p.target.y)<p.splash):[p.target];targets.forEach(e=>{e.hp-=p.damage*(1-e.armor*(p.kind==='antiarmor'?.18:1));if(e.hp<=0){const idx=S.enemies.indexOf(e);if(idx>=0){S.enemies.splice(idx,1);S.kills++;S.gold+=Math.round(e.reward*(P.research.includes('coinage')?1.08:1));burst(e.x,e.y,7)}}});S.shots.splice(i,1)}else{p.x+=dx/dist*m;p.y+=dy/dist*m}}
for(let i=S.fx.length-1;i>=0;i--){const f=S.fx[i];f.life-=dt;f.x+=f.vx*dt;f.y+=f.vy*dt;f.vy+=50*dt;if(f.life<=0)S.fx.splice(i,1)}if(S.active&&!S.left&&!S.enemies.length){S.active=false;$('start-wave').disabled=false;if(S.wave>=D.waves)finish(true);else{$('mission').textContent=`Wave ${S.wave} cleared. Upgrade or continue.`;refresh()}}}
function finish(win){if(S.ended)return;S.ended=true;if(win){const prior=P.mapResults[M.id]?.[difficultyId];P.science+=D.rewardScience;P.totalScienceEarned+=D.rewardScience;P.coins+=Math.round(D.rewardCoins*(P.research.includes('war-treasury')?1.12:1));P.mapResults[M.id]=P.mapResults[M.id]||{};P.mapResults[M.id][difficultyId]=true;refreshUnlocks(P);saveProfile(P);$('result-title').textContent=`${M.name.toUpperCase()} CLEARED`;$('result-text').textContent=`${prior?'Replay reward':'New medal earned'} · +${D.rewardScience} Science · +${D.rewardCoins} Coins. Your arsenal mastery and permanent progression have been saved.`}else{$('result-title').textContent='DEFEAT';$('result-text').textContent=`Reached wave ${S.wave}/${D.waves}. No progression was lost.`}$('result').classList.add('show');$('start-wave').disabled=true}
$('return-home').onclick=()=>location.href='index.html?v=1';$('quit').onclick=()=>location.href='index.html?v=1';
function terrain(){const coastal=['strait','coast','harbor','river'].includes(M.theme),g=ctx.createLinearGradient(0,0,W,H);g.addColorStop(0,coastal?'#789465':'#829760');g.addColorStop(1,'#405f45');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);if(coastal){ctx.fillStyle='#367588';ctx.fillRect(0,0,142,H);ctx.fillStyle='#cdb77a';ctx.fillRect(138,0,18,H)}ctx.strokeStyle='#3a302455';ctx.lineWidth=58;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();path.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke();ctx.strokeStyle='#b39563';ctx.lineWidth=46;ctx.stroke();for(let i=0;i<45;i++){const x=(i*173+M.id.length*31)%W,y=(i*97+61)%H;if(path.slice(0,-1).some((p,j)=>segDist(x,y,p,path[j+1])<62)||coastal&&x<165)continue;ctx.fillStyle=i%4===0?'#786e55':'#2f5837';ctx.beginPath();ctx.arc(x,y,5+i%7,0,7);ctx.fill()}ctx.fillStyle='#6b5b47';ctx.fillRect(912,220,48,118);ctx.fillStyle='#d6b45f';ctx.font='700 13px Georgia';ctx.fillText(M.name.toUpperCase(),20,28)}
function tower(t){const d=ARSENAL[t.type],tier=t.tier;ctx.save();ctx.translate(t.x,t.y);ctx.fillStyle='#0004';ctx.beginPath();ctx.ellipse(3,16,22+tier*2,7+tier,0,0,7);ctx.fill();ctx.fillStyle=d.kind==='artillery'?'#4c5540':'#6b6947';ctx.beginPath();ctx.arc(0,4,16+tier*2,0,7);ctx.fill();if(d.kind==='artillery'||d.kind==='antiarmor'){ctx.strokeStyle='#232923';ctx.lineWidth=7;ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(28+tier*5,-16);ctx.stroke()}else{for(let i=0;i<tier+1;i++){const ox=(i-tier/2)*9;ctx.fillStyle='#aa3030';ctx.beginPath();ctx.arc(ox,-8,5,0,7);ctx.fill();ctx.fillStyle='#ead7b7';ctx.fillRect(ox-3,-3,6,14)}}ctx.restore()}
function enemy(e){ctx.save();ctx.translate(e.x,e.y+Math.sin(e.bob)*2);ctx.fillStyle='#0004';ctx.beginPath();ctx.ellipse(2,12,14,5,0,0,7);ctx.fill();ctx.fillStyle=e.type==='tank'?'#394638':e.type==='vehicle'?'#58614d':'#6e4335';if(e.type==='tank'||e.type==='vehicle')ctx.fillRect(-15,-9,30,18);else{ctx.beginPath();ctx.roundRect(-7,-5,14,19,4);ctx.fill();ctx.fillStyle='#d0ad88';ctx.beginPath();ctx.arc(0,-9,5,0,7);ctx.fill()}ctx.fillStyle='#101719';ctx.fillRect(-15,-22,30,4);ctx.fillStyle=e.hp/e.maxHp>.5?'#78d584':'#ef6f65';ctx.fillRect(-14,-21,28*Math.max(0,e.hp/e.maxHp),2);ctx.restore()}
function draw(){terrain();if(S.selected){ctx.strokeStyle='#f0c56c88';ctx.fillStyle='#f0c56c12';ctx.beginPath();ctx.arc(S.selected.x,S.selected.y,S.selected.range,0,7);ctx.fill();ctx.stroke()}S.towers.forEach(tower);S.enemies.forEach(enemy);S.shots.forEach(p=>{ctx.fillStyle='#fff0ad';ctx.beginPath();ctx.arc(p.x,p.y,3,0,7);ctx.fill()});S.fx.forEach(f=>{ctx.globalAlpha=Math.max(0,f.life/.5);ctx.fillStyle='#d7ba77';ctx.beginPath();ctx.arc(f.x,f.y,f.r,0,7);ctx.fill()});ctx.globalAlpha=1}
function loop(now){const dt=Math.min(.033,(now-S.last)/1000);S.last=now;update(dt);draw();requestAnimationFrame(loop)}refresh();requestAnimationFrame(loop);
